project:
  type: manuscript
  output-dir: _manuscript
  render:
    - "index.qmd"
    - "!*.Rmd"

execute:
  enabled: false
  freeze: true
  warning: false
  message: false


format:
  html:
    embed-resources: true
  docx: default
  jats: default
  pdf: default
  elsevier-pdf:
    keep-tex: true
    journal:
      formatting: review
      model: 3p
      layout: onecolumn
      cite-style: number

bibliography: references.bib
# cite-method: natbib
# 