---
title: Learning the Piano and Epigenetic Changes in Neuroplasticity-Associated Genes in a Randomized Active-Controlled Trial
author:
  - name:
      given: "Jonas Janik Ralf"
      family: "Koberschinski"
    orcid: 0009-0008-9633-5601
    corresponding: true
    email: jonas.koberschinski@mhb-fontane.de
    roles:
      - Writing – original draft preparation
      - Methodology
      - Software
      - Formal Analysis
      - Visualization
    affiliations:
      - Brandenburg Medical School, Neuruppin, Germany
      - Laboratory of Molecular Neurosciences (LMN), Dept. of clinical psychiatry, Hannover Medical School, Hannover, Germany
      - Devision of Clinical Psychology and Sexual Medicine, Dept. of Psychiatry, Social Psychiatry and Psychotherapy, Hannover Medical School, Hannover, Germany
  - name: Kirsten Jahn
    corresp nding: false
    roles:
      - Methodology
      - Software
      - Formal Analysis
      - Writing – review and editing
    affiliations:
      - Laboratory of Molecular Neurosciences (LMN), Dept. of clinical psychiatry, Hannover Medical School, Hannover, Germany
  - name: Helge Frieling
    corresponding: false
    roles:
      - Resources
    affiliations:
      - Laboratory of Molecular Neurosciences (LMN), Dept. of clinical psychiatry, Hannover Medical School, Hannover, Germany
  - name: Christopher Sinke
    orcid: 0000-0003-1716-6229
    corresponding: false
    roles:
      - Methodology
      - Software
      - Formal Analysis
      - Writing – review and editing
    affiliations:
      - Devision of Clinical Psychology and Sexual Medicine, Dept. of Psychiatry, Social Psychiatry and Psychotherapy, Hannover Medical School, Hannover, Germany
  - name: Kristin Jünemann
    orcid: 0000-0001-6460-3378
    corresponding: false
    roles:
      - Methodology
      - Software
      - Writing – review and editing
      - Measurement of telomere lengths
    affiliations:
      - Devision of Clinical Psychology and Sexual Medicine, Dept. of Psychiatry, Social Psychiatry and Psychotherapy, Hannover Medical School, Hannover, Germany
  - name:
      given: "Clara Eline"
      family: James
    orcid: 0000-0001-7480-0682
    corresponding: false
    roles: []
    affiliations:
      - Geneva Musical Minds Lab, Geneva School of Health Sciences, University of Applied Sciences and Arts Western Switzerland (HES-SO), Geneva, Switzerland
  - name: Florian Worschech
    orcid: 0000-0001-7185-8870
    corresponding: false
    roles: []
    affiliations:
      - Institute of Music Physiology and Musicians′ Medicine, Hannover University of Music, Drama and Media, Hannover, Germany
      - Center for Systems Neuroscience, Hannover, Germany
  - name: Damien Marie
    orcid: 0000-0001-8199-8260
    corresponding: false
    roles: []
    affiliations:
      - Geneva Musical Minds Lab, Geneva School of Health Sciences, University of Applied Sciences and Arts Western Switzerland (HES-SO), Geneva, Switzerland
      - Faculty of Psychology and Educational Sciences,University of Geneva, Geneva, Switzerland
  - name: Eckart Altenmüller
    corresponding: false
    roles:
      - Conceptualization
    affiliations:
      - Institute of Music Physiology and Musicians′ Medicine, Hannover University of Music, Drama and Media, Hannover, Germany
      - Center for Systems Neuroscience, Hannover, Germany
  - name:
      given: "Tillmann Horst Christoph"
      family: Krüger
    orcid: 0000-0002-6583-1433
    corresponding: false
    roles:
      - Conceptualization
      - Resources
      - Supervision
    affiliations:
      - Devision of Clinical Psychology and Sexual Medicine, Dept. of Psychiatry, Social Psychiatry and Psychotherapy, Hannover Medical School, Hannover, Germany
      - Center for Systems Neuroscience, Hannover, Germany
keywords:
  - Music
  - Neuroplasticity
  - Piano Learning
  - Epigenetics
  - DNA Methylation
  - BDNF exon IV
  - MAPT
  - DLG4
abstract: |
  ...
plain-language-summary: |
  ...
key-points:
  -
  -
date: today
bibliography: references.bib
csl: ama.csl
citation:
  container-title: ...
number-sections: true
editor:
  markdown:
    wrap: 72
---

# Background {#sec-background}

To make music is a compllex higly sophisticated activity that reuqires our brain to use of all of his faculties.

# Methods {#sec-data-methods}

## Study flowchart

{{< embed notebooks/flowchart.qmd#fig-flowchart >}}



## Study design

Our study is based on the TBM study (@jamesTrainBrainMusic2020a), a two-site, longitudinal, randomized, activly-controlled, ("open-label" or unblined) intervention study, in which retired healthy older adults, received prcatical piano training once a week (intervention) or theoretical music lesseons (active control) for 18? (between ... and ...) months to assess cognitive, perceptual-motor, and brain plasticity outcomes. 

piano group, that was activly learning the piano by ... Active control group that was only

Blood samples were taken at three different time points. The first (T0) one week before the weekly cycle of practical or theoretical music lessons were started. The second (T1) after 6 months and the third (T2) again after 6 months so one year after T0.

Because multiple tests were performed on each inidivuals time point (not only blood samples but also fMRI as part of the original study) T0 fell between March and June 2019, T1 between August 2019 and February 2020 and T2 between June 2020 and November 2020.

Auch in meiner Untersuchung? *A small subgroup of participants were recruited as early as in January 2019 (T0), and had their consecutive examinations in August 2019 (T1) and in the end of February/beginning of March 2020 (T2). In other words, their T2 was directly before the lockdown started. Therefore, this small subgroup was excluded from the main analyses*

## Study participants

The participants of the study cohort were recruted at the Geneva Musical Minds Lab, Geneva School of Health Sciences, University of Applied Sciences and Arts Western Switzerland (HES-SO), Geneva, Switzerland and the Hannover Medical School, Dept. for Clinical Psychiatry, Social Psychiatry and Psychotherapy, Division of Clinical Psychology and Sexual Medicine in corporation with the Institut für Musikphysiologie und Musiker-Medizin Hochschule für Musik, Theater und Medien affiliated to the Hochschule für Musik, Theater und Medien Hannover. Possibility for participation was made public through newspaper advertisement and posters in public places. @tbl-demographics summarizes relevant demographic information about the study cohort. Some requirements had been to be met for volunteers to participate in the study. They had to be in overall good health, right-handed, retired and not relying on hearing aids.

## Measurement of DNA methylation

### Target Genes

We focused on the primer regions of three genes commonly neuroplasticity-associated and hypthecised being potentially epigenetically modifiable by playing the piano: BDNF4, PSD95, MAPT (Tau).

### DNA isolation

Genomic DNA (gDNA) was isolated at the Institute of Molecular and Translational Therapeutic Strategies of Hannover Medical School from 50 µL blood using the "NucleoMag Blood 200 µl" kit (MACHEREY-NAGEL GmbH & Co. KG, Düren, Deutschland) in concordance with the instructions of the manufacturer. The isolated gDNA was stored at -20 °C. The blood samples have been received anonymized and prior to gDNA isolation. Then the samples were additionaly randomized *(by doing what?)* to minimize potential batch effects. DNA samples were diluted in 96-well plates to a fixed concentration of 10 ng/µl.

### Bisulfite Conversion

The gDNA of all samples was then bisullfite converted via the "EZ-96 DNA Methylation-Lightning™ MagPrep" kit (Zymo Research Corporation, Irvine, CA, USA) also following the manufacturers instructions.

### Primer design

With Ensembl and Geneious Pro 5.6.7 the primer regions of our target genes were located and the sequences of the primer regions analyzed. Aided by Biocalculator (metabion), NetPrimer (Premier Biosoft), Methyl Primer Express v1.0 (Applied Biosystems) and Bisulfite Primer Seeker (Zymo) we designed primers for PCR with bisulfite-converted DNA (see @tbl-primers-pcr) and sequencing primers (@tbl-primers-seq) - later used to prepare Sanger Sequencing - and orderd these primers from metabion GmbH (Martinsried, Deutschland).

| Target    | Primer name             | Sequence (5′→3′)                  |
|-----------|-------------------------|-----------------------------------|
| **BDNF**  | BDNF_fwd1_18            | 5′-GGGGGAGGATTAATTGAGTTAGTTTTG-3′ |
| **BDNF**  | BDNF_rev_20             | 5′-ATATATACTCCTTCTATTCTACAACAA-3′ |
| **BDNF**  | BDNF_fwd2_19            | 5′-TTTGTTGGGGTTGGAAGTGAAAAT-3′    |
| **BDNF**  | BDNF_rev_20             | 5′-ATATATACTCCTTCTATTCTACAACAA-3′ |
| **PSD95** | 1341_PSD95_Fw_a         | 5′-TGGGAATTTGATTTGTTTAGA-3′       |
| **PSD95** | 1342_PDS95_Fw_i         | 5′-AGAGTTAGTTGGGAAAAGAGA-3′       |
| **PSD95** | 1343_PSD95_Rev_i        | 5′-TCCTCTTCTATCCCATCCTAT-3′       |
| **PSD95** | 1344_PSD95_Rev_a        | 5′-TAACTACAATAACTTAAACCCCT-3′     |
| **Tau**   | 271_MEX_Primer_Tau_Fw_a | 5′-TAATAAAAAAGGTGGGAAAAAA-3′      |
| **Tau**   | 272_MEX_Primer_Tau_Fw_i | 5′-AAAGGAAGTAGTTTGGGG-3′          |
| **Tau**   | 273_MEX_Primer_Tau_Rev  | 5′-AACCTCCCCAAAAAAAAAAA-3′        |

: Primers used in PCR {#tbl-primers-pcr}

| Target   | Primer name    | Sequence (5′→3′)           |
|----------|----------------|----------------------------|
| **BDNF** | BDNF_seqrev_21 | 5′-ACAAAAAAATTTCATACTAA-3′ |

: Primers used in sequencing PCR {#tbl-primers-seq}

*Note: Other sequencing primers are missing.*

### Gene Amplification

The primers were dissolved in nuclease-free water. The proportions have been predetermined by the manufacturer. The stock solution 100 pmol. It was then used to derive a working solution of 20 pmol (1:5). Both solutions were prexserved atg -20 °C. Amplification was then performed together with HotStarTaq® PCR Master Mix Kit (Qiagen, Hilden, Deutschland). The samples were then puriefed with the PCR purification kit "CleanNGS" (CleanNA, Waddinxveen, Niederlande).

### Sanger Sequencing

The purfied PCR prodcus were sequenced with the BigDye Terminator v3.1 Cycle Sequencing Kit (Applied Biosystems, Foster City, CA, USA) and th e sequencing primers mentioned above (@tbl-primers-seq). The sequencing product were purifed with the "CleanDTR" kit (CleanNA, Waddinxveen, Niederlande).

Then using the Applied Biosystems' 3500 Genetic Analyzer (ABI 3500xL) Capillary electrophoresis was performed.

### Data Processing via ESME

The data derived from the ABI 3500xL was then processed with Epigenetic Sequencing Methylation (ESME) analysis software.

## Literay Research

pubmed

## Writing Guidelines

JARS and CONSORT The wrting of this paper was guided by the APA journall Artivdle Reporting Standard for qnatuictave reaseach.

## Data Structuring and Statistical Analysis

For data structuring and transformation Excel [@microsoft_excel], SPSS [@ibm_spss_28] and R [@rcoreteamLanguageEnvironmentStatistical2025], using the following packages: tidyverse [@wickhamWelcomeTidyverse2019], dplyr [@wickhamDplyrGrammarData2023], tidyr [@wickhamTidyrTidyMessy2024], readxl [@wickhamReadxlReadExcel2025], writexl [@oomsWritexlExportData2025]... .
After structuring the data, R was used to analyze the data. 
Descriptive statistics we perforemd using the ... 
Plots were designed using the ggplot2 [@wickhamGgplot2ElegantGraphics2016], ggforitfy [@tangGgfortifyUnifiedInterface2016; @horikoshiGgfortifyDataVisualization2018] and ... package.
Lastly, Quarto [@quarto] provided the framework in which all analyses and manuscript preparation were performed.



We performed modelling with 3 different types of models. Linear models. The difference of 2 time points was modelled (T2 - T0, T1 - T0 and T2 - T1) and after that used as the depenedet variable.

Longitudianl Nture, two sided Mixed Models seemed fitting.

Generalized Linear model (GLM) with the ... package

Lastly Zero-Inflated Beta Distribution Regression Models with random effects (ZIBR) were performed using the glmmTMB package for modelling and DHARMa for residual diagnostics.

# Results {#sec-results}

## Descriptive statistics {#sec-results-descriptive}

### Generall demographics {#sec-results-general}


Overall 144 (one with missing T0! ID 141) participants were included in the study. Both groups were nearly equally distributed (46,5 % in the piano group). The mean age was 69.58 years (SD: 3.5 years) with a minimum of 62 and a maximum of 78 years. This was due to the desgin of the TBM study.

Chat: *Continuous variables were compared using the Wilcoxon rank-sum test. Categorical variables were compared using Pearson’s chi-squared test or Fisher’s exact test, as appropriate.*

| Characteristic | Piano (N=67) | Control (N=76) | Overall (N=143) | P value |
|---|---:|---:|---:|---:|
| **Age — yr** | 69.0 (67.0–71.0) | 69.0 (67.0–73.0) | 69.0 (67.0–71.5) | 0.96 |
| **Sex — no. (%)** |  |  |  | 0.52 |
| &nbsp;&nbsp;Female | 37 (55.2) | 46 (60.5) | 83 (58.0) |  |
| &nbsp;&nbsp;Male | 30 (44.8) | 30 (39.5) | 60 (42.0) |  |
| **Study site — no. (%)** |  |  |  | 0.56 |
| &nbsp;&nbsp;Hannover | 40 (59.7) | 49 (64.5) | 89 (62.2) |  |
| &nbsp;&nbsp;Geneva | 27 (40.3) | 27 (35.5) | 54 (37.8) |  |
| **Height — cm** | 170 (163–177) | 168 (164–175) | 169 (163–176) | 0.25 |
| **Weight — kg** | 71 (64–80) | 70 (60–77) | 71 (62–79) | 0.12 |
| **Body-mass index — kg/m²** | 24.5 (22.5–26.3) | 24.1 (22.0–25.6) | 24.3 (22.2–26.1) | 0.20 |
| **Smoking status — no. (%)** |  |  |  | 1.00 |
| &nbsp;&nbsp;Current smoker | 4 (6.2) | 4 (5.5) | 8 (5.8) |  |
| **Alcohol use — no. (%)** |  |  |  | 0.35 |
| &nbsp;&nbsp;None | 19 (29.2) | 22 (31.0) | 41 (30.1) |  |
| &nbsp;&nbsp;Occasional | 12 (18.5) | 7 (9.9) | 19 (14.0) |  |
| &nbsp;&nbsp;Regular | 34 (52.3) | 42 (59.2) | 76 (55.9) |  |
| **Prescription medication use — no. (%)** |  |  |  | 0.55 |
| &nbsp;&nbsp;Yes | 35 (53.8) | 43 (58.9) | 78 (56.5) |  |
| **Illicit drug use — no. (%)** |  |  |  | 1.00 |
| &nbsp;&nbsp;Yes | 3 (4.6) | 3 (4.1) | 6 (4.3) |  |
| **Family status — no. (%)** |  |  |  | 0.83 |
| &nbsp;&nbsp;Single | 7 (10.8) | 11 (15.1) | 18 (13.0) |  |
| &nbsp;&nbsp;Married/Partnered | 41 (63.1) | 41 (56.2) | 82 (59.4) |  |
| &nbsp;&nbsp;Divorced | 10 (15.4) | 13 (17.8) | 23 (16.7) |  |
| &nbsp;&nbsp;Widowed | 7 (10.8) | 8 (11.0) | 15 (10.9) |  |
| **Educational attainment — no. (%)** |  |  |  | 0.94 |
| &nbsp;&nbsp;Primary | 1 (1.5) | 0 (0.0) | 1 (0.7) |  |
| &nbsp;&nbsp;Secondary | 13 (19.4) | 18 (23.7) | 31 (21.7) |  |
| &nbsp;&nbsp;Vocational | 11 (16.4) | 12 (15.8) | 23 (16.1) |  |
| &nbsp;&nbsp;Upper secondary | 10 (14.9) | 12 (15.8) | 22 (15.4) |  |
| &nbsp;&nbsp;University | 27 (40.3) | 27 (35.5) | 54 (37.8) |  |
| &nbsp;&nbsp;Postgraduate | 5 (7.5) | 7 (9.2) | 12 (8.4) |  |
| **Cognitive score (CogTel)** | 31.4 (26.0–35.8) | 32.9 (26.0–38.3) | 31.9 (26.0–37.2) | 0.43 |

: Values are median [IQR] for continuous variables and no. (%) for categorical variables. P values are from the Wilcoxon rank-sum test for continuous variables and Pearson’s chi-squared test or Fisher’s exact test for categorical variables, as appropriate. Baseline characteristics were taken from the earliest available assessment (T0 preferred); one participant had no T0 sample (ID 141). {#tbl-demographics} 


### Metadata sequencing

1,078 blood samples have been sequenced from the participants for three different genes at three different time points (T0, T1, T2). A decline in the number of samples from T0 to T2 can be seen (@tbl-metadata-sequencing-summary), because not every participant provided blood samples at every time point, because of loss to follow up. This is the reason for the difference between the time points.

Furthermore, not every blood sample could be analyzed successfully (cf. @tbl-metadata-sequencing-summary) due to some qualitative differences in the sequencing process. But in the end, a total of 359 BDNF, 362 Tau and 357 PSD95 samples could be successfully sequenced. This is the reason for the slight difference between genes.

Two further Participants had to be excluded from the analysis, because somehow their methylationvalues for timepoints conflated, so they could not be differentiated anymore.

| Characteristic          |      Piano |    Control |    Overall |
|-------------------------|-----------:|-----------:|-----------:|
| BDNF samples at T0 (n)  |         65 |         75 |        140 |
| BDNF samples at T1 (n)  |         61 |         61 |        122 |
| BDNF samples at T2 (n)  |         50 |         47 |         97 |
| BDNF missing T0, n (%)  |   2 (3.0%) |   2 (2.6%) |   4 (2.8%) |
| BDNF missing T1, n (%)  |   6 (9.0%) | 16 (20.8%) | 22 (15.3%) |
| BDNF missing T2, n (%)  | 17 (25.4%) | 30 (39.0%) | 47 (32.6%) |
| TAU samples at T0 (n)   |         67 |         75 |        142 |
| TAU samples at T1 (n)   |         63 |         60 |        123 |
| TAU samples at T2 (n)   |         50 |         47 |         97 |
| TAU missing T0, n (%)   |   1 (1.5%) |   2 (2.6%) |   3 (2.1%) |
| TAU missing T1, n (%)   |   5 (7.4%) | 17 (22.1%) | 22 (15.2%) |
| TAU missing T2, n (%)   | 18 (26.5%) | 30 (39.0%) | 48 (33.1%) |
| PSD95 samples at T0 (n) |         66 |         73 |        139 |
| PSD95 samples at T1 (n) |         63 |         59 |        122 |
| PSD95 samples at T2 (n) |         49 |         47 |         96 |
| PSD95 missing T0, n (%) |   2 (2.9%) |   4 (5.2%) |   6 (4.1%) |
| PSD95 missing T1, n (%) |   5 (7.4%) | 18 (23.4%) | 23 (15.9%) |
| PSD95 missing T2, n (%) | 19 (27.9%) | 30 (39.0%) | 49 (33.8%) |

: Metadata of successfully sequenced samples per gene and time point {#tbl-metadata-sequencing-summary}


### Methylation Level Analysis {#sec-results-methylation-level}

#### Overall and over time {#sec-results-methylation-overall}

Overall the methlation of the three genes was low (Mean \< 0,08, Median \< 0,04). PSD95 had the lowest methylation values.

{{< embed notebooks/eda.qmd#fig-boxplots-genes >}}

#### Per CpG and Gene {#sec-results-methylation-cpg-gene}

Looking at the methlation patterns of every CpG per gene (@fig-boxplots-cpg-all), Tau showed a methylation pattern, that was largely limited to upstream region of the promoter, whereas further downstream CpGs were rarely methylated across individuals. In contrast, for PSD95, CpGs near the end of the promoter region showed notable methylation patterns, while most other sites where mostly none-methylated with little or no inter-individual variability. For BDNF, a comparably localized pattern was less pronounced but further downsstream the CpGs were also less methylated.

{{< embed notebooks/eda.qmd#fig-boxplots-cpg-all >}}

## Principal component analysis (PCA) {#sec-results-pca}

We performed principal component analyses (PCA) separately for each gene, using the correlation matrix. Across genes, the first two principal components explained only a moderate proportion of total variance (BDNF: PC1 28.81%, PC2 16.84%; Tau: PC1 29.02%, PC2 9.22%; PSD95: PC1 17.10%, PC2 11.61%). Accordingly, the scree plots (@fig-scree-all) show only a gradual decrease of explained variance across subsequent components. **(Stimmt nicht für PSD95 und Tau)**

Furthermore, biplots of the first two principal components did not indicate a differing clustering pattern between the two group at any timepoint (@fig-pca-genes). Although the apparent group-wise configuration for PSD95 varied somewhat across time points, this pattern did not amount to a consistent clustering difference.

{{< embed notebooks/PCA/PCA_Covariance_161025.qmd#fig-pca-genes >}}

Noticably, inspecting the loadings revelaed that the variance explained by PC1 was driven primarily by a small fraction of CpGs in every gene (@fig-pc1-loadings). For BDNF, m148, m066, m111 and m058 have been the strongest contributors; for Tau, m331, m337, m310, m315 and m323; and for PSD95: "p95", "p60", "p23". By ranking the absolute PC1 loadings every gene showed an "elbow" pattern (BDNF: between the 4th and 5th CpG; Tau: between the 4th and 5th CpG; PSD95: after the 3rd CpG; @fig-pc1-loadings; see also @tbl-supp-pca-bdnf–@tbl-supp-pca-psd95 for loading ranks).

This concentration of variance is also evident in the methylation distributions across CpGs (@fig-boxplots-cpg-all) already mentioned above (#sec-results-methylation-cpg-gene). These observations motivated stratifying subsequent analyses by considering (i) all CpGs and (ii) only CpGs exhibiting higher inter-individual variability.

{{< embed notebooks/PCA/PCA_Covariance_161025.qmd#fig-pc1-loadings >}}

## Analysis of Methylation differences {#sec-results-methylation-differences}

Our null hypothesis was that there are no differences in methylation levels between groups (piano vs. control) and time points (T0, T1, T2) in the three target genes (BDNF, Tau, PSD95) or said differently that playing the piano has no effect on the methylation of neuroplasticity-associated genes like BDNF, PSD95 and Tau.

### All CpG-sites

#### Overall methylation levels

| Marker | Mean ± SD     |
|--------|---------------|
| BDNF   | 0.070 ± 0.034 |
| Tau    | 0.075 ± 0.020 |
| PSD95  | 0.031 ± 0.014 |

: Mean methylation levels per gene {#tbl-mean-methylation-overall}

| Gene  | Group    |   N | Mean ± SD     |
|-------|----------|----:|---------------|
| BDNF  | Controll | 183 | 0.073 ± 0.034 |
| BDNF  | Piano    | 176 | 0.066 ± 0.033 |
| PSD95 | Controll | 179 | 0.031 ± 0.014 |
| PSD95 | Piano    | 178 | 0.030 ± 0.013 |
| Tau   | Controll | 182 | 0.075 ± 0.020 |
| Tau   | Piano    | 180 | 0.075 ± 0.020 |

: Mean methylation levels per gene and group {#tbl-mean-methylation-group}

#### Time difference overall

| Marker | Time | Mean ± SD     |
|--------|------|---------------|
| BDNF   | T0   | 0.070 ± 0.033 |
| BDNF   | T1   | 0.062 ± 0.029 |
| BDNF   | T2   | 0.079 ± 0.037 |
| Tau    | T0   | 0.073 ± 0.020 |
| Tau    | T1   | 0.076 ± 0.020 |
| Tau    | T2   | 0.076 ± 0.019 |
| PSD95  | T0   | 0.030 ± 0.016 |
| PSD95  | T1   | 0.032 ± 0.013 |
| PSD95  | T2   | 0.031 ± 0.010 |

: Mean methylation levels per gene and time point {#tbl-mean-methylation-time}

##### BDNF

BDNF showed a decrease in methylation from T0 (0,07 ± 0,03) to T1 (0.062 ± 0.029), followed by an increase at T2 (0.079 ± 0.037) surpassing the initial levels at T0.

##### Tau

Tau exhibited a slight increase in methylation from T0 to T1, which remained stable at T2.

##### PSD95

-   Bei PSD95 verbleibt der Median der Methylierung gleichbleibend bei 0, während das arithmetische Mittel der Methylierung von T0 zu T1 steigt aber bei T2 wieder auf das Ausgangsniveau zurückfällt.

PSD95 maintained a consistent median methylation level of 0, while the mean methylation increased from T0 to T1 but returned to baseline levels at T2.

{{< embed notebooks/eda.qmd#fig-interactions-no-group-with-significance >}}

#### Time difference per group

Our main goal we aimed to determine whether the degree of methylation differed between the intervention (piano lessons) and control groups.

-   Bei BDNF zeigt sich eine leichte Differenz zwischen der Kontrollgruppe (Median: 0.07, Mean: 0.07326) und der Pianogruppe (Median: 0.064, Mean: 0.06598), welche eine niedrigere Metyhlierung (Median: -0.006, Mean: -0.00728) aufwies. **Streuungsmaße?**
-   Weiterhin zeigen sich für die arithmetischen Mittel von BDNF und PSD95 zwei Modi.
-   Tau war unimodal.

{{< embed notebooks/eda.qmd#fig-interactions-by-gene-mean-with-significance >}}

### Filtered CpG-sites

according to @sec-results-pca we also filtered for the high variance CpGs.

#### Time

{{< embed notebooks/postpca_data_manipulation_201025.qmd#fig-interactions-no-group-by-filtered-cpg-with-significance >}}

#### Group

{{< embed notebooks/postpca_data_manipulation_201025.qmd#fig-interactions-by-group-filtered-cpg-with-significance >}}

## Models (LM, GLM, ZIBR) {#sec-results-models}
### Linear Models (LM) {#sec-results-lm}
Across biomarkers and time contrasts, change scores were mainly explained by the biomarker’s prior level (strong negative association), while group, sex, age, and CogTel showed no robust associations, and site effects appeared only sporadically (notably PSD95 T1–T0 and borderline BDNF T1–T0).

#### All CpG-sites
##### BDNF
###### Mean model: bdnf_T2T0

We fitted a linear model (estimated using OLS) to predict T2_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.46, F(6, 88) = 12.33, p < .001, adj. R2 = 0.42). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.14 (95% CI [-0.03, 0.30], t(88) = 1.60, p = 0.113). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -7.21e-03, 95% CI [-0.03, 0.01], t(88) = -0.78, p = 0.440; Std. beta = -0.07, 95% CI [-0.24, 0.10])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -5.00e-03, 95% CI [-0.02, 0.01], t(88) = -0.62, p = 0.535; Std. beta = -0.10, 95% CI [-0.42, 0.22])
  - The effect of Sex [M] is statistically non-significant and positive (beta = 2.13e-03, 95% CI [-0.02, 0.02], t(88) = 0.25, p = 0.805; Std. beta = 0.04, 95% CI [-0.30, 0.38])
  - The effect of Age start is statistically non-significant and negative (beta = -4.66e-04, 95% CI [-2.65e-03, 1.72e-03], t(88) = -0.42, p = 0.673; Std. beta = -0.03, 95% CI [-0.20, 0.13])
  - The effect of CogTel is statistically non-significant and negative (beta = -5.86e-04, 95% CI [-1.76e-03, 5.91e-04], t(88) = -0.99, p = 0.325; Std. beta = -0.08, 95% CI [-0.25, 0.08])
  - The effect of T0 is statistically significant and negative (beta = -0.99, 95% CI [-1.23, -0.75], t(88) = -8.10, p < .001; Std. beta = -0.65, 95% CI [-0.81, -0.49])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

###### Mean model: bdnf_T1T0

We fitted a linear model (estimated using OLS) to predict T1_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T1_T0 ~ as.factor(Standort) + as.factor(Gruppe) + as.factor(Sex) + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.58, F(6, 112) = 25.97, p < .001, adj. R2 = 0.56). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.11 (95% CI [-8.25e-03, 0.22], t(112) = 1.84, p = 0.068). Within this model:

  - The effect of Standort [1] is statistically significant and negative (beta = -0.01, 95% CI [-0.02, -4.36e-05], t(112) = -1.99, p = 0.049; Std. beta = 0.15, 95% CI [-0.11, 0.42])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -1.35e-03, 95% CI [-0.01, 0.01], t(112) = -0.23, p = 0.816; Std. beta = -0.25, 95% CI [-0.49, -9.94e-04])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -5.60e-04, 95% CI [-2.10e-03, 9.79e-04], t(112) = -0.72, p = 0.473; Std. beta = -0.03, 95% CI [-0.29, 0.23])
  - The effect of Age start is statistically non-significant and negative (beta = -2.03e-04, 95% CI [-9.82e-04, 5.76e-04], t(112) = -0.52, p = 0.607; Std. beta = -0.05, 95% CI [-0.17, 0.08])
  - The effect of CogTel is statistically significant and negative (beta = -0.99, 95% CI [-1.15, -0.82], t(112) = -11.84, p < .001; Std. beta = -0.03, 95% CI [-0.16, 0.09])
  - The effect of T0 is statistically non-significant and positive (beta = 6.76e-03, 95% CI [-4.87e-03, 0.02], t(112) = 1.15, p = 0.252; Std. beta = -0.74, 95% CI [-0.87, -0.62])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

###### Mean model: bdnf_T2T1

We fitted a linear model (estimated using OLS) to predict T2_T1 with Standort, Gruppe, Sex, Age_start, CogTel and T1 (formula: T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1). The model explains a statistically significant and substantial proportion of variance (R2 = 0.39, F(6, 85) = 9.21, p < .001, adj. R2 = 0.35). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T1 = 0, is at 0.14 (95% CI [-0.04, 0.31], t(85) = 1.58, p = 0.118). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -8.87e-03, 95% CI [-0.03, 0.01], t(85) = -0.93, p = 0.357; Std. beta = -0.09, 95% CI [-0.27, 0.10])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -6.80e-03, 95% CI [-0.02, 0.01], t(85) = -0.80, p = 0.425; Std. beta = -0.14, 95% CI [-0.49, 0.21])
  - The effect of Sex [M] is statistically non-significant and positive (beta = 4.15e-03, 95% CI [-0.01, 0.02], t(85) = 0.47, p = 0.638; Std. beta = 0.09, 95% CI [-0.28, 0.45])
  - The effect of Age start is statistically non-significant and negative (beta = -4.29e-04, 95% CI [-2.66e-03, 1.80e-03], t(85) = -0.38, p = 0.703; Std. beta = -0.03, 95% CI [-0.21, 0.14])
  - The effect of CogTel is statistically non-significant and negative (beta = -6.25e-04, 95% CI [-1.81e-03, 5.60e-04], t(85) = -1.05, p = 0.297; Std. beta = -0.09, 95% CI [-0.27, 0.08])
  - The effect of T1 is statistically significant and negative (beta = -1.01, 95% CI [-1.31, -0.72], t(85) = -6.93, p < .001; Std. beta = -0.61, 95% CI [-0.78, -0.43])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

##### Tau
###### Mean model: tau_T2T0

We fitted a linear model (estimated using OLS) to predict T2_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.40, F(6, 88) = 9.66, p < .001, adj. R2 = 0.36). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.10 (95% CI [9.52e-03, 0.19], t(88) = 2.20, p = 0.030). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -1.73e-04, 95% CI [-9.57e-03, 9.22e-03], t(88) = -0.04, p = 0.971; Std. beta = -3.34e-03, 95% CI [-0.18, 0.18])
  - The effect of Gruppe [Piano] is statistically non-significant and positive (beta = 7.58e-05, 95% CI [-8.02e-03, 8.17e-03], t(88) = 0.02, p = 0.985; Std. beta = 3.13e-03, 95% CI [-0.33, 0.34])
  - The effect of Sex [M] is statistically non-significant and positive (beta = 1.69e-05, 95% CI [-8.74e-03, 8.78e-03], t(88) = 3.83e-03, p = 0.997; Std. beta = 6.97e-04, 95% CI [-0.36, 0.36])
  - The effect of Age start is statistically non-significant and negative (beta = -5.02e-04, 95% CI [-1.63e-03, 6.22e-04], t(88) = -0.89, p = 0.377; Std. beta = -0.08, 95% CI [-0.25, 0.10])
  - The effect of CogTel is statistically non-significant and negative (beta = -1.60e-04, 95% CI [-7.43e-04, 4.24e-04], t(88) = -0.54, p = 0.588; Std. beta = -0.05, 95% CI [-0.22, 0.13])
  - The effect of T0 is statistically significant and negative (beta = -0.75, 95% CI [-0.95, -0.54], t(88) = -7.28, p < .001; Std. beta = -0.61, 95% CI [-0.78, -0.45])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

###### Mean model: tau_T1T0

We fitted a linear model (estimated using OLS) to predict T1_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.36, F(6, 114) = 10.54, p < .001, adj. R2 = 0.32). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 5.13e-03 (95% CI [-0.07, 0.08], t(114) = 0.13, p = 0.897). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -1.28e-03, 95% CI [-8.94e-03, 6.38e-03], t(114) = -0.33, p = 0.741; Std. beta = -0.03, 95% CI [-0.18, 0.13])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -2.78e-03, 95% CI [-9.89e-03, 4.34e-03], t(114) = -0.77, p = 0.441; Std. beta = -0.12, 95% CI [-0.42, 0.18])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -4.86e-03, 95% CI [-0.01, 2.71e-03], t(114) = -1.27, p = 0.206; Std. beta = -0.21, 95% CI [-0.53, 0.11])
  - The effect of Age start is statistically non-significant and positive (beta = 7.57e-04, 95% CI [-2.68e-04, 1.78e-03], t(114) = 1.46, p = 0.146; Std. beta = 0.11, 95% CI [-0.04, 0.27])
  - The effect of CogTel is statistically non-significant and positive (beta = 6.37e-05, 95% CI [-4.46e-04, 5.73e-04], t(114) = 0.25, p = 0.805; Std. beta = 0.02, 95% CI [-0.14, 0.18])
  - The effect of T0 is statistically significant and negative (beta = -0.71, 95% CI [-0.89, -0.53], t(114) = -7.72, p < .001; Std. beta = -0.59, 95% CI [-0.74, -0.44])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

###### Mean model: tau_T2T1

We fitted a linear model (estimated using OLS) to predict T2_T1 with Standort, Gruppe, Sex, Age_start, CogTel and T1 (formula: T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1). The model explains a statistically significant and substantial proportion of variance (R2 = 0.45, F(6, 84) = 11.52, p < .001, adj. R2 = 0.41). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T1 = 0, is at 0.10 (95% CI [6.53e-03, 0.19], t(84) = 2.13, p = 0.036). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -2.03e-04, 95% CI [-0.01, 9.62e-03], t(84) = -0.04, p = 0.967; Std. beta = -3.63e-03, 95% CI [-0.18, 0.17])
  - The effect of Gruppe [Piano] is statistically non-significant and positive (beta = 5.40e-04, 95% CI [-8.21e-03, 9.29e-03], t(84) = 0.12, p = 0.903; Std. beta = 0.02, 95% CI [-0.31, 0.35])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -2.53e-04, 95% CI [-9.46e-03, 8.96e-03], t(84) = -0.05, p = 0.957; Std. beta = -9.66e-03, 95% CI [-0.36, 0.34])
  - The effect of Age start is statistically non-significant and negative (beta = -4.09e-04, 95% CI [-1.60e-03, 7.86e-04], t(84) = -0.68, p = 0.498; Std. beta = -0.06, 95% CI [-0.23, 0.11])
  - The effect of CogTel is statistically non-significant and negative (beta = -1.65e-04, 95% CI [-7.77e-04, 4.48e-04], t(84) = -0.53, p = 0.595; Std. beta = -0.05, 95% CI [-0.22, 0.12])
  - The effect of T1 is statistically significant and negative (beta = -0.85, 95% CI [-1.07, -0.63], t(84) = -7.68, p < .001; Std. beta = -0.65, 95% CI [-0.82, -0.48])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

##### PSD95
###### Mean model: psd95_T2T0

We fitted a linear model (estimated using OLS) to predict T2_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.74, F(6, 86) = 39.83, p < .001, adj. R2 = 0.72). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.05 (95% CI [6.10e-03, 0.10], t(86) = 2.24, p = 0.027). Within this model:

  - The effect of Standort is statistically non-significant and positive (beta = 7.98e-04, 95% CI [-4.31e-03, 5.90e-03], t(86) = 0.31, p = 0.757; Std. beta = 0.02, 95% CI [-0.10, 0.14])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -2.68e-03, 95% CI [-6.93e-03, 1.56e-03], t(86) = -1.26, p = 0.213; Std. beta = -0.14, 95% CI [-0.36, 0.08])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -3.06e-03, 95% CI [-7.71e-03, 1.58e-03], t(86) = -1.31, p = 0.193; Std. beta = -0.16, 95% CI [-0.40, 0.08])
  - The effect of Age start is statistically non-significant and negative (beta = -1.68e-04, 95% CI [-7.63e-04, 4.27e-04], t(86) = -0.56, p = 0.576; Std. beta = -0.03, 95% CI [-0.15, 0.08])
  - The effect of CogTel is statistically non-significant and negative (beta = -1.50e-04, 95% CI [-4.62e-04, 1.61e-04], t(86) = -0.96, p = 0.339; Std. beta = -0.06, 95% CI [-0.17, 0.06])
  - The effect of T0 is statistically significant and negative (beta = -1.16, 95% CI [-1.31, -1.01], t(86) = -15.26, p < .001; Std. beta = -0.86, 95% CI [-0.97, -0.75])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

###### Mean model: psd95_T1T0

We fitted a linear model (estimated using OLS) to predict T1_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.62, F(6, 111) = 30.21, p < .001, adj. R2 = 0.60). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.06 (95% CI [3.00e-03, 0.11], t(111) = 2.10, p = 0.038). Within this model:

  - The effect of Standort is statistically significant and positive (beta = 5.81e-03, 95% CI [6.91e-04, 0.01], t(111) = 2.25, p = 0.026; Std. beta = 0.14, 95% CI [0.02, 0.26])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -2.87e-03, 95% CI [-7.61e-03, 1.87e-03], t(111) = -1.20, p = 0.233; Std. beta = -0.14, 95% CI [-0.38, 0.09])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -4.63e-03, 95% CI [-9.73e-03, 4.70e-04], t(111) = -1.80, p = 0.075; Std. beta = -0.23, 95% CI [-0.48, 0.02])
  - The effect of Age start is statistically non-significant and negative (beta = -3.66e-04, 95% CI [-1.05e-03, 3.15e-04], t(111) = -1.07, p = 0.289; Std. beta = -0.06, 95% CI [-0.18, 0.06])
  - The effect of CogTel is statistically non-significant and negative (beta = -1.52e-04, 95% CI [-4.92e-04, 1.88e-04], t(111) = -0.89, p = 0.378; Std. beta = -0.05, 95% CI [-0.18, 0.07])
  - The effect of T0 is statistically significant and negative (beta = -0.97, 95% CI [-1.12, -0.83], t(111) = -13.09, p < .001; Std. beta = -0.78, 95% CI [-0.90, -0.66])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

###### Mean model: psd95_T2T1

We fitted a linear model (estimated using OLS) to predict T2_T1 with Standort, Gruppe, Sex, Age_start, CogTel and T1 (formula: T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1). The model explains a statistically significant and substantial proportion of variance (R2 = 0.64, F(6, 82) = 24.47, p < .001, adj. R2 = 0.62). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T1 = 0, is at 0.05 (95% CI [-1.42e-03, 0.10], t(82) = 1.93, p = 0.057). Within this model:

  - The effect of Standort is statistically non-significant and positive (beta = 3.25e-04, 95% CI [-4.94e-03, 5.59e-03], t(82) = 0.12, p = 0.902; Std. beta = 8.92e-03, 95% CI [-0.14, 0.15])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -3.68e-03, 95% CI [-8.19e-03, 8.29e-04], t(82) = -1.62, p = 0.108; Std. beta = -0.22, 95% CI [-0.49, 0.05])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -3.61e-03, 95% CI [-8.41e-03, 1.20e-03], t(82) = -1.49, p = 0.139; Std. beta = -0.21, 95% CI [-0.50, 0.07])
  - The effect of Age start is statistically non-significant and negative (beta = -1.12e-04, 95% CI [-7.35e-04, 5.11e-04], t(82) = -0.36, p = 0.720; Std. beta = -0.02, 95% CI [-0.16, 0.11])
  - The effect of CogTel is statistically non-significant and negative (beta = -2.18e-04, 95% CI [-5.41e-04, 1.06e-04], t(82) = -1.34, p = 0.184; Std. beta = -0.09, 95% CI [-0.23, 0.05])
  - The effect of T1 is statistically significant and negative (beta = -1.01, 95% CI [-1.18, -0.84], t(82) = -11.81, p < .001; Std. beta = -0.80, 95% CI [-0.94, -0.67])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

{{< embed notebooks/LM_no_step()_101224.qmd#fig-lm-coef-plots >}}

#### filtered CpGs

##### BDNF


###### Mean model: bdnf_T2T0 

We fitted a linear model (estimated using OLS) to predict T2_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.46, F(6, 88) = 12.33, p < .001, adj. R2 = 0.42). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.14 (95% CI [-0.03, 0.30], t(88) = 1.60, p = 0.113). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -7.21e-03, 95% CI [-0.03, 0.01], t(88) = -0.78, p = 0.440; Std. beta = -0.07, 95% CI [-0.24, 0.10])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -5.00e-03, 95% CI [-0.02, 0.01], t(88) = -0.62, p = 0.535; Std. beta = -0.10, 95% CI [-0.42, 0.22])
  - The effect of Sex [M] is statistically non-significant and positive (beta = 2.13e-03, 95% CI [-0.02, 0.02], t(88) = 0.25, p = 0.805; Std. beta = 0.04, 95% CI [-0.30, 0.38])
  - The effect of Age start is statistically non-significant and negative (beta = -4.66e-04, 95% CI [-2.65e-03, 1.72e-03], t(88) = -0.42, p = 0.673; Std. beta = -0.03, 95% CI [-0.20, 0.13])
  - The effect of CogTel is statistically non-significant and negative (beta = -5.86e-04, 95% CI [-1.76e-03, 5.91e-04], t(88) = -0.99, p = 0.325; Std. beta = -0.08, 95% CI [-0.25, 0.08])
  - The effect of T0 is statistically significant and negative (beta = -0.99, 95% CI [-1.23, -0.75], t(88) = -8.10, p < .001; Std. beta = -0.65, 95% CI [-0.81, -0.49])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.


###### Mean model: bdnf_T1T0 

We fitted a linear model (estimated using OLS) to predict T1_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T1_T0 ~ as.factor(Standort) + as.factor(Gruppe) + as.factor(Sex) + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.58, F(6, 112) = 25.97, p < .001, adj. R2 = 0.56). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.11 (95% CI [-8.25e-03, 0.22], t(112) = 1.84, p = 0.068). Within this model:

  - The effect of Standort [1] is statistically significant and negative (beta = -0.01, 95% CI [-0.02, -4.36e-05], t(112) = -1.99, p = 0.049; Std. beta = 0.15, 95% CI [-0.11, 0.42])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -1.35e-03, 95% CI [-0.01, 0.01], t(112) = -0.23, p = 0.816; Std. beta = -0.25, 95% CI [-0.49, -9.94e-04])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -5.60e-04, 95% CI [-2.10e-03, 9.79e-04], t(112) = -0.72, p = 0.473; Std. beta = -0.03, 95% CI [-0.29, 0.23])
  - The effect of Age start is statistically non-significant and negative (beta = -2.03e-04, 95% CI [-9.82e-04, 5.76e-04], t(112) = -0.52, p = 0.607; Std. beta = -0.05, 95% CI [-0.17, 0.08])
  - The effect of CogTel is statistically significant and negative (beta = -0.99, 95% CI [-1.15, -0.82], t(112) = -11.84, p < .001; Std. beta = -0.03, 95% CI [-0.16, 0.09])
  - The effect of T0 is statistically non-significant and positive (beta = 6.76e-03, 95% CI [-4.87e-03, 0.02], t(112) = 1.15, p = 0.252; Std. beta = -0.74, 95% CI [-0.87, -0.62])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.


###### Mean model: bdnf_T2T1 

We fitted a linear model (estimated using OLS) to predict T2_T1 with Standort, Gruppe, Sex, Age_start, CogTel and T1 (formula: T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1). The model explains a statistically significant and substantial proportion of variance (R2 = 0.39, F(6, 85) = 9.21, p < .001, adj. R2 = 0.35). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T1 = 0, is at 0.14 (95% CI [-0.04, 0.31], t(85) = 1.58, p = 0.118). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -8.87e-03, 95% CI [-0.03, 0.01], t(85) = -0.93, p = 0.357; Std. beta = -0.09, 95% CI [-0.27, 0.10])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -6.80e-03, 95% CI [-0.02, 0.01], t(85) = -0.80, p = 0.425; Std. beta = -0.14, 95% CI [-0.49, 0.21])
  - The effect of Sex [M] is statistically non-significant and positive (beta = 4.15e-03, 95% CI [-0.01, 0.02], t(85) = 0.47, p = 0.638; Std. beta = 0.09, 95% CI [-0.28, 0.45])
  - The effect of Age start is statistically non-significant and negative (beta = -4.29e-04, 95% CI [-2.66e-03, 1.80e-03], t(85) = -0.38, p = 0.703; Std. beta = -0.03, 95% CI [-0.21, 0.14])
  - The effect of CogTel is statistically non-significant and negative (beta = -6.25e-04, 95% CI [-1.81e-03, 5.60e-04], t(85) = -1.05, p = 0.297; Std. beta = -0.09, 95% CI [-0.27, 0.08])
  - The effect of T1 is statistically significant and negative (beta = -1.01, 95% CI [-1.31, -0.72], t(85) = -6.93, p < .001; Std. beta = -0.61, 95% CI [-0.78, -0.43])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

##### Tau
###### Mean model: tau_T2T0 

We fitted a linear model (estimated using OLS) to predict T2_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.40, F(6, 88) = 9.66, p < .001, adj. R2 = 0.36). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.10 (95% CI [9.52e-03, 0.19], t(88) = 2.20, p = 0.030). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -1.73e-04, 95% CI [-9.57e-03, 9.22e-03], t(88) = -0.04, p = 0.971; Std. beta = -3.34e-03, 95% CI [-0.18, 0.18])
  - The effect of Gruppe [Piano] is statistically non-significant and positive (beta = 7.58e-05, 95% CI [-8.02e-03, 8.17e-03], t(88) = 0.02, p = 0.985; Std. beta = 3.13e-03, 95% CI [-0.33, 0.34])
  - The effect of Sex [M] is statistically non-significant and positive (beta = 1.69e-05, 95% CI [-8.74e-03, 8.78e-03], t(88) = 3.83e-03, p = 0.997; Std. beta = 6.97e-04, 95% CI [-0.36, 0.36])
  - The effect of Age start is statistically non-significant and negative (beta = -5.02e-04, 95% CI [-1.63e-03, 6.22e-04], t(88) = -0.89, p = 0.377; Std. beta = -0.08, 95% CI [-0.25, 0.10])
  - The effect of CogTel is statistically non-significant and negative (beta = -1.60e-04, 95% CI [-7.43e-04, 4.24e-04], t(88) = -0.54, p = 0.588; Std. beta = -0.05, 95% CI [-0.22, 0.13])
  - The effect of T0 is statistically significant and negative (beta = -0.75, 95% CI [-0.95, -0.54], t(88) = -7.28, p < .001; Std. beta = -0.61, 95% CI [-0.78, -0.45])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.


###### Mean model: tau_T1T0 

We fitted a linear model (estimated using OLS) to predict T1_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.36, F(6, 114) = 10.54, p < .001, adj. R2 = 0.32). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 5.13e-03 (95% CI [-0.07, 0.08], t(114) = 0.13, p = 0.897). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -1.28e-03, 95% CI [-8.94e-03, 6.38e-03], t(114) = -0.33, p = 0.741; Std. beta = -0.03, 95% CI [-0.18, 0.13])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -2.78e-03, 95% CI [-9.89e-03, 4.34e-03], t(114) = -0.77, p = 0.441; Std. beta = -0.12, 95% CI [-0.42, 0.18])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -4.86e-03, 95% CI [-0.01, 2.71e-03], t(114) = -1.27, p = 0.206; Std. beta = -0.21, 95% CI [-0.53, 0.11])
  - The effect of Age start is statistically non-significant and positive (beta = 7.57e-04, 95% CI [-2.68e-04, 1.78e-03], t(114) = 1.46, p = 0.146; Std. beta = 0.11, 95% CI [-0.04, 0.27])
  - The effect of CogTel is statistically non-significant and positive (beta = 6.37e-05, 95% CI [-4.46e-04, 5.73e-04], t(114) = 0.25, p = 0.805; Std. beta = 0.02, 95% CI [-0.14, 0.18])
  - The effect of T0 is statistically significant and negative (beta = -0.71, 95% CI [-0.89, -0.53], t(114) = -7.72, p < .001; Std. beta = -0.59, 95% CI [-0.74, -0.44])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.


###### Mean model: tau_T2T1 

We fitted a linear model (estimated using OLS) to predict T2_T1 with Standort, Gruppe, Sex, Age_start, CogTel and T1 (formula: T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1). The model explains a statistically significant and substantial proportion of variance (R2 = 0.45, F(6, 84) = 11.52, p < .001, adj. R2 = 0.41). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T1 = 0, is at 0.10 (95% CI [6.53e-03, 0.19], t(84) = 2.13, p = 0.036). Within this model:

  - The effect of Standort is statistically non-significant and negative (beta = -2.03e-04, 95% CI [-0.01, 9.62e-03], t(84) = -0.04, p = 0.967; Std. beta = -3.63e-03, 95% CI [-0.18, 0.17])
  - The effect of Gruppe [Piano] is statistically non-significant and positive (beta = 5.40e-04, 95% CI [-8.21e-03, 9.29e-03], t(84) = 0.12, p = 0.903; Std. beta = 0.02, 95% CI [-0.31, 0.35])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -2.53e-04, 95% CI [-9.46e-03, 8.96e-03], t(84) = -0.05, p = 0.957; Std. beta = -9.66e-03, 95% CI [-0.36, 0.34])
  - The effect of Age start is statistically non-significant and negative (beta = -4.09e-04, 95% CI [-1.60e-03, 7.86e-04], t(84) = -0.68, p = 0.498; Std. beta = -0.06, 95% CI [-0.23, 0.11])
  - The effect of CogTel is statistically non-significant and negative (beta = -1.65e-04, 95% CI [-7.77e-04, 4.48e-04], t(84) = -0.53, p = 0.595; Std. beta = -0.05, 95% CI [-0.22, 0.12])
  - The effect of T1 is statistically significant and negative (beta = -0.85, 95% CI [-1.07, -0.63], t(84) = -7.68, p < .001; Std. beta = -0.65, 95% CI [-0.82, -0.48])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

##### PSD95
###### Mean model: psd95_T2T0 

We fitted a linear model (estimated using OLS) to predict T2_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.74, F(6, 86) = 39.83, p < .001, adj. R2 = 0.72). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.05 (95% CI [6.10e-03, 0.10], t(86) = 2.24, p = 0.027). Within this model:

  - The effect of Standort is statistically non-significant and positive (beta = 7.98e-04, 95% CI [-4.31e-03, 5.90e-03], t(86) = 0.31, p = 0.757; Std. beta = 0.02, 95% CI [-0.10, 0.14])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -2.68e-03, 95% CI [-6.93e-03, 1.56e-03], t(86) = -1.26, p = 0.213; Std. beta = -0.14, 95% CI [-0.36, 0.08])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -3.06e-03, 95% CI [-7.71e-03, 1.58e-03], t(86) = -1.31, p = 0.193; Std. beta = -0.16, 95% CI [-0.40, 0.08])
  - The effect of Age start is statistically non-significant and negative (beta = -1.68e-04, 95% CI [-7.63e-04, 4.27e-04], t(86) = -0.56, p = 0.576; Std. beta = -0.03, 95% CI [-0.15, 0.08])
  - The effect of CogTel is statistically non-significant and negative (beta = -1.50e-04, 95% CI [-4.62e-04, 1.61e-04], t(86) = -0.96, p = 0.339; Std. beta = -0.06, 95% CI [-0.17, 0.06])
  - The effect of T0 is statistically significant and negative (beta = -1.16, 95% CI [-1.31, -1.01], t(86) = -15.26, p < .001; Std. beta = -0.86, 95% CI [-0.97, -0.75])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.


###### Mean model: psd95_T1T0 

We fitted a linear model (estimated using OLS) to predict T1_T0 with Standort, Gruppe, Sex, Age_start, CogTel and T0 (formula: T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0). The model explains a statistically significant and substantial proportion of variance (R2 = 0.62, F(6, 111) = 30.21, p < .001, adj. R2 = 0.60). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T0 = 0, is at 0.06 (95% CI [3.00e-03, 0.11], t(111) = 2.10, p = 0.038). Within this model:

  - The effect of Standort is statistically significant and positive (beta = 5.81e-03, 95% CI [6.91e-04, 0.01], t(111) = 2.25, p = 0.026; Std. beta = 0.14, 95% CI [0.02, 0.26])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -2.87e-03, 95% CI [-7.61e-03, 1.87e-03], t(111) = -1.20, p = 0.233; Std. beta = -0.14, 95% CI [-0.38, 0.09])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -4.63e-03, 95% CI [-9.73e-03, 4.70e-04], t(111) = -1.80, p = 0.075; Std. beta = -0.23, 95% CI [-0.48, 0.02])
  - The effect of Age start is statistically non-significant and negative (beta = -3.66e-04, 95% CI [-1.05e-03, 3.15e-04], t(111) = -1.07, p = 0.289; Std. beta = -0.06, 95% CI [-0.18, 0.06])
  - The effect of CogTel is statistically non-significant and negative (beta = -1.52e-04, 95% CI [-4.92e-04, 1.88e-04], t(111) = -0.89, p = 0.378; Std. beta = -0.05, 95% CI [-0.18, 0.07])
  - The effect of T0 is statistically significant and negative (beta = -0.97, 95% CI [-1.12, -0.83], t(111) = -13.09, p < .001; Std. beta = -0.78, 95% CI [-0.90, -0.66])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.


###### Mean model: psd95_T2T1 

We fitted a linear model (estimated using OLS) to predict T2_T1 with Standort, Gruppe, Sex, Age_start, CogTel and T1 (formula: T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1). The model explains a statistically significant and substantial proportion of variance (R2 = 0.64, F(6, 82) = 24.47, p < .001, adj. R2 = 0.62). The model's intercept, corresponding to Standort = 0, Gruppe = Controll, Sex = F, Age_start = 0, CogTel = 0 and T1 = 0, is at 0.05 (95% CI [-1.42e-03, 0.10], t(82) = 1.93, p = 0.057). Within this model:

  - The effect of Standort is statistically non-significant and positive (beta = 3.25e-04, 95% CI [-4.94e-03, 5.59e-03], t(82) = 0.12, p = 0.902; Std. beta = 8.92e-03, 95% CI [-0.14, 0.15])
  - The effect of Gruppe [Piano] is statistically non-significant and negative (beta = -3.68e-03, 95% CI [-8.19e-03, 8.29e-04], t(82) = -1.62, p = 0.108; Std. beta = -0.22, 95% CI [-0.49, 0.05])
  - The effect of Sex [M] is statistically non-significant and negative (beta = -3.61e-03, 95% CI [-8.41e-03, 1.20e-03], t(82) = -1.49, p = 0.139; Std. beta = -0.21, 95% CI [-0.50, 0.07])
  - The effect of Age start is statistically non-significant and negative (beta = -1.12e-04, 95% CI [-7.35e-04, 5.11e-04], t(82) = -0.36, p = 0.720; Std. beta = -0.02, 95% CI [-0.16, 0.11])
  - The effect of CogTel is statistically non-significant and negative (beta = -2.18e-04, 95% CI [-5.41e-04, 1.06e-04], t(82) = -1.34, p = 0.184; Std. beta = -0.09, 95% CI [-0.23, 0.05])
  - The effect of T1 is statistically significant and negative (beta = -1.01, 95% CI [-1.18, -0.84], t(82) = -11.81, p < .001; Std. beta = -0.80, 95% CI [-0.94, -0.67])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.
R Console

##### Plot
{{< embed notebooks/LM_PostPCA_201025.qmd#fig-lm-group-effect-filtered >}}


### Generalized Linear Models (GLM) {#sec-results-glm}
#### BDNF
#### Tau
#### PSD95

### Mixed Effects Models (LMM) {#sec-results-lmm}
#### BDNF
#### Tau
#### PSD95
We fitted a linear mixed model (estimated using REML and nloptwrap optimizer) to predict M_value with Zeitpunkt and Gruppe
(formula: M_value ~ Zeitpunkt * Gruppe). The model included ID as random effect (formula: ~1 | ID). The model's total
explanatory power is weak (conditional R2 = 0.09) and the part related to the fixed effects alone (marginal R2) is of
0.07. The model's intercept, corresponding to Zeitpunkt = T0 and Gruppe = Controll, is at -2.66 (95% CI [-2.94, -2.39],
t(348) = -19.29, p < .001). Within this model:

  - The effect of Zeitpunkt [T1] is statistically significant and positive (beta = 0.59, 95% CI [0.20, 0.99], t(348) = 2.94,
p = 0.003; Std. beta = 0.50, 95% CI [0.17, 0.84])
  - The effect of Zeitpunkt [T2] is statistically significant and positive (beta = 0.95, 95% CI [0.54, 1.37], t(348) = 4.50,
p < .001; Std. beta = 0.81, 95% CI [0.45, 1.16])
  - The effect of Gruppe [Piano] is statistically non-significant and positive (beta = 0.37, 95% CI [-0.01, 0.76], t(348) =
1.91, p = 0.057; Std. beta = 0.32, 95% CI [-8.97e-03, 0.64])
  - The effect of Zeitpunkt [T1] × Gruppe [Piano] is statistically non-significant and negative (beta = -0.51, 95% CI
[-1.06, 0.05], t(348) = -1.80, p = 0.072; Std. beta = -0.43, 95% CI [-0.90, 0.04])
  - The effect of Zeitpunkt [T2] × Gruppe [Piano] is statistically significant and negative (beta = -1.24, 95% CI [-1.84,
-0.65], t(348) = -4.13, p < .001; Std. beta = -1.05, 95% CI [-1.56, -0.55])

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence
Intervals (CIs) and p-values were computed using a Wald t-distribution approximation.

### Zero-Inflated Beta Regression Models (ZIBR) {#sec-results-zibr}
#### BDNF
#### Tau
#### PSD95
We fitted a logistic mixed model (estimated using ML and nlminb optimizer) to predict prop_adj with Zeitpunkt, Gruppe,
Age_start and Sex (formula: prop_adj ~ Zeitpunkt * Gruppe + Age_start + Sex). The model included ID as random effect
(formula: ~1 | ID). The model's total explanatory power is moderate (conditional R2 = 0.14) and the part related to the
fixed effects alone (marginal R2) is of 0.11. The model's intercept, corresponding to Zeitpunkt = T0, Gruppe = Controll,
Age_start = 0 and Sex = F, is at -1.09 (95% CI [-1.79, -0.38], p = 0.002). Within this model:

  - The effect of Zeitpunkt [T1] is statistically significant and positive (beta = 0.15, 95% CI [0.04, 0.27], p = 0.011)
  - The effect of Zeitpunkt [T2] is statistically significant and positive (beta = 0.26, 95% CI [0.14, 0.38], p < .001)
  - The effect of Gruppe [Piano] is statistically non-significant and positive (beta = 0.09, 95% CI [-0.02, 0.20], p =
0.112)
  - The effect of Age start is statistically non-significant and positive (beta = 1.49e-03, 95% CI [-8.53e-03, 0.01], p =
0.771)
  - The effect of Sex [M] is statistically non-significant and positive (beta = 0.03, 95% CI [-0.04, 0.10], p = 0.419)
  - The effect of Zeitpunkt [T1] × Gruppe [Piano] is statistically non-significant and negative (beta = -0.14, 95% CI
[-0.30, 0.02], p = 0.084)
  - The effect of Zeitpunkt [T2] × Gruppe [Piano] is statistically significant and negative (beta = -0.32, 95% CI [-0.49,
-0.15], p < .001)

Standardized parameters were obtained by fitting the model on a standardized version of the dataset. 95% Confidence
Intervals (CIs) and p-values were computed using a Wald z-distribution approximation.
<!-- Overdispersion! -->

# Discussion {#sec-discussion}

**Hohe Expressionsrate!** aller gene vor allem PSD95 und Tau. The null hypothesis of our study was that playing the piano has no effect on the methylation of neuroplasticity-associated genes like BDNF, PSD95 and Tau. Despite of Tau the null hypothesis could be rejected.

## Limitations

# Conclusion

# Declarations

## Ethics approval and consent to participate

The study protocol was reviewed and approved by the Hannover Medical School ethics committee (approval number 3604-2017). All study participants gave their written informed consent to participate in the study.

## Consent for publication

Not applicable.

## Availability of data and materials

Data are available from the corresponding author upon request via jonas.koberschinski\@mhb-fontane.de and via https://github.com/JKobi-med/Promotion.

## Competing interests

The authors have no competing interests to declare.

## Funding

This work was funded by the Swiss National Science Foundation (grant no. 100019E-170410 to Clara E. James) and the German Research Foundation (grant no. 323965454 to Eckart Altenmüller). Financial support in Switzerland was also provided by the Med. Kurt Fries Foundation, the Dalle Molle Foundation, and the Edith Maryon Foundation (to Clara E. James).

## Author Contributions

Conceptualization: T.H.C.K.

Methodology: K.Jü., C.S., S.C., K.Ja., J.K.

Software: S.C., C.S., K.Jü., K.Ja., J.K.

Formal Analysis: S.C., K.Ja., C.S.

Investigation: S.C., C.B., K.Jü.

Resources: T.H.C.K., C.B., S.B., H.F.

Writing – original draft preparation: J.K.

Writing – review and editing: S.C., C.S., K. Jü., H.F., S.B., C. B., T.H.C.K.

Visualization, K.Ja., J.K.

Supervision, T.H.C.K., C.B., H.F., S.B.

All authors have read and agreed to the published version of the manuscript.

## Use of AI tools

ChatGPT (OpenAI) was used to assist with draft preparation (particularly language and style), development of R code, construction of well-structured tables, and summarizing and clarifying statistical output for reporting.
All analyses, interpretations, and manuscript text were reviewed and verified by the authors.
GitHub Copilot was also used to assist with R code development and manuscript writing.
The first author takes full responsibility for the accuracy and integrity of the work.

## Acknowledgements
*Soli Deo gloria, sine quo hoc manuscriptum perfici non potuit.*

This paper forms part of the doctoral thesis of Jonas Koberschinski and is dedicated to his firstborn son.
He would also like to thank Martin Max Schumacher, PhD, and Kai Wenger, PhD, for their expert assistance and kind support.


# Supplementary material {#sec-supp}

## Supplementary Methods {#sec-supp-methods}

## Supplementary Tables {#sec-supp-tables}

### PCA

#### BDNF

| Rank | CpG  |             |
|------|------|------------:|
| 1    | m148 | \***0.612** |
| 2    | m066 |   **0.453** |
| 3    | m111 |   **0.431** |
| 4    | m058 |   **0.422** |
| 5    | m039 |       0.215 |
| 6    | m035 |       0.076 |
| 7    | m087 |       0.053 |
| 8    | m024 |       0.029 |
| 9    | p020 |       0.022 |
| 10   | p018 |       0.013 |

: PC1 loading ranks for BDNF CpGs. {#tbl-supp-pca-bdnf}

#### Tau

| Rank | CpG  |            |
|------|------|-----------:|
| 1    | m331 | **0.4438** |
| 2    | m337 | **0.4236** |
| 3    | m310 | **0.3856** |
| 4    | m315 | **0.3843** |
| 5    | m323 | **0.3771** |
| 6    | m306 |     0.2459 |
| 7    | m219 |     0.1652 |
| 8    | m300 |     0.1489 |
| 9    | m293 |     0.1295 |
| 10   | m207 |     0.1246 |

: PC1 loading ranks for Tau CpGs (top ten contributors). {#tbl-supp-pca-tau}

#### PSD95

| Rank | CpG  |           |
|------|------|----------:|
| 1    | p95  | **0.664** |
| 2    | p60  | **0.484** |
| 3    | p23  | **0.445** |
| 4    | m35  |     0.153 |
| 5    | m28  |     0.103 |
| 6    | m418 |     0.097 |
| 7    | m24  |     0.094 |
| 8    | p91  |     0.094 |
| 9    | m400 |     0.086 |
| 10   | m11  |     0.078 |

: PC1 loading ranks for PSD95 CpGs (top ten contributors). {#tbl-supp-pca-psd95}

## Supplementary Figures {#sec-supp-figures}

### Scree Plots

{{< embed notebooks/PCA/PCA_Covariance_161025.qmd#fig-scree-all >}}

# References
