{
  "hash": "697eb36ee77d537dd9c18e348708a2a7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploratory Data Analysis\"\nauthor: \"Jonas J.R. Koberschinski\"\ndate: \"14-11-2024\"\n---\n\n\n\n\n\n\n\n\n\n## Data import\n\n\n\n\n\n\n\n\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\n#| include: false\n\n# load mean&median data\n# List of file names (without paths and extension)\nfile_names <- c(\n  \"bdnf_mean.txt\",\n  \"bdnf_median.txt\",\n  \n  \"tau_mean.txt\",\n  \"tau_median.txt\",\n  \n  \"psd95_mean.txt\",\n  \"psd95_median.txt\"\n)\n\n# Folder where the files are located\nsubfolder <- \"/Users/kobi/Desktop/Promotionsdatananalyse mit Excel und Martin/Promotion (Quarto Manuscript)/tables/mean&median_tables\"\n\n# Loop through the file names, read each table, and assign it to a variable\nfor (file_name in file_names) {\n  # Construct the full file path by combining the subfolder and file name\n  file_path <- file.path(subfolder, file_name)\n  \n  # Remove the .txt extension to get the base name for the variable\n  var_name <- tools::file_path_sans_ext(file_name)\n  \n  # Read the table and assign it to a variable with the same name\n  assign(var_name, read.table(file_path, sep = \"\\t\", header = TRUE, row.names = NULL, quote = \"\"))\n}\n\n\n# load cpg-data\ncpg <- read.table(file = '/Users/kobi/Desktop/Promotionsdatananalyse mit Excel und Martin/Promotion (Quarto Manuscript)/tables/Ausgangstabellen/cpg.txt', sep = \"\\t\", header = TRUE, row.names = NULL, quote = \"\")\n\n\n# load wide data\n# List of file names (without paths and extension)\nfile_names_wide <- c(\n  \"bdnf_mean_wide.txt\",\n  \"bdnf_median_wide.txt\",\n  \n  \"tau_mean_wide.txt\",\n  \"tau_median_wide.txt\",\n  \n  \"psd95_mean_wide.txt\",\n  \"psd95_median_wide.txt\"\n)\n\n# Folder where the files are located\nsubfolder_wide <- \"/Users/kobi/Desktop/Promotionsdatananalyse mit Excel und Martin/Promotion (Quarto Manuscript)/tables/wide_format/\"\n\n# Loop through the file names, read each table, and assign it to a variable\nfor (file_name in file_names_wide) {\n  # Construct the full file path by combining the subfolder and file name\n  file_path <- file.path(subfolder_wide, file_name)\n  \n  # Remove the .txt extension to get the base name for the variable\n  var_name <- tools::file_path_sans_ext(file_name)\n  \n  # Read the table and assign it to a variable with the same name\n  assign(var_name, read.table(file_path, sep = \"\\t\", header = TRUE, row.names = NULL, quote = \"\"))\n}\n```\n:::\n\n\n\n\n\n\n\n\n\n\n# EDA \\# Allgenes?\n\n## Gruppendifferenz der Mittelwerte?\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(psych)\nlibrary(DescTools)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'DescTools'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:psych':\n\n    AUC, ICC, SD\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Modes\nMode(bdnf_mean$Mean, na.rm = TRUE) #  8x: 0 u. 0.063 -> bimodal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.051 0.063\nattr(,\"freq\")\n[1] 9\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(tau_mean$Mean, na.rm = TRUE) # 6x 0.066875\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.066875\nattr(,\"freq\")\n[1] 7\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(psd95_mean$Mean, na.rm = TRUE) # 3x: 0.02377778 u. 0.03177778 -> bimodal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02555556 0.03266667 0.03466667 0.03866667\nattr(,\"freq\")\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(bdnf_median$Median, na.rm = TRUE) # 92x: 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\nattr(,\"freq\")\n[1] 92\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(tau_median$Median, na.rm = TRUE) # 65x: 0.02\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02\nattr(,\"freq\")\n[1] 65\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(psd95_median$Median, na.rm = TRUE) # 317x: 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\nattr(,\"freq\")\n[1] 317\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#with tapply\n# Minimale Differenz\ntapply(bdnf_mean$Mean, bdnf_mean$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.04800 0.07000 0.07326 0.09500 0.16900       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.04600 0.06400 0.06598 0.08825 0.18600       4 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(bdnf_median$Median, bdnf_median$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n 0.0000  0.0025  0.0350  0.0397  0.0600  0.2050       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n 0.0000  0.0000  0.0250  0.0344  0.0500  0.2100       4 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# überhaupt keine Differenz\ntapply(tau_mean$Mean, tau_mean$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.02813 0.06294 0.07269 0.07515 0.08583 0.14574       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.01250 0.06270 0.07323 0.07510 0.08625 0.16708       1 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(tau_median$Median, tau_median$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.01000 0.02000 0.02011 0.03000 0.12000       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.01000 0.02000 0.01906 0.03000 0.06500       1 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# überhaupt keine Differenz\ntapply(psd95_mean$Mean, psd95_mean$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.02316 0.03054 0.03131 0.03832 0.13062       3 \n\n$Piano\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.007083 0.021574 0.028556 0.030294 0.036550 0.080000        2 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(psd95_median$Median, psd95_median$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.000000 0.000000 0.000000 0.003101 0.000000 0.060000        3 \n\n$Piano\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.000000 0.000000 0.000000 0.001601 0.000000 0.050000        2 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n-   Bei BDNF zeigt sich eine leichte Differenz zwischen der Kontrollgruppe (Median: 0.07, Mean: 0.07326) und der Pianogruppe (Median: 0.064, Mean: 0.06598), welche eine niedrigere Metyhlierung (Median: -0.006, Mean: -0.00728) aufwies.\n-   Weiterhin zeigen sich für die arithmetischen Mittel von BDNF und PSD95 zwei Modi.\n-   Tau war unimodal.\n\n## Zeitdifferenz der Mittelwerte?\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Methylierung: PSD95 < Tau < BDNF\n\ntapply(bdnf_mean$Mean, bdnf_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 > T1 < T2 (T0 < T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.06991766 0.06213866 0.07886025 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(bdnf_median$Median, bdnf_median$Zeitpunkt, median, na.rm = TRUE) # T0 > T1 < T2 (T0 < T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   T0    T1    T2 \n0.030 0.025 0.040 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(tau_mean$Mean, tau_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 < T1 = T2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.07346318 0.07632020 0.07604121 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(tau_median$Median, tau_median$Zeitpunkt, median, na.rm = TRUE) # T0 = T1 > T2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   T0    T1    T2 \n0.020 0.020 0.015 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# überhaupt keine Differenz\ntapply(psd95_mean$Mean, psd95_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 < T1 > T2 (T0 = T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.02978670 0.03197377 0.03078094 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(psd95_median$Median, psd95_median$Zeitpunkt, median, na.rm = TRUE) # all = 0 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT0 T1 T2 \n 0  0  0 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# noch geringer als Tau und BDNF methyliert\n```\n:::\n\n\n\n\n\n\n\n\n\n\n-   Die Gene sind allgemein eher gering methyliert (Mean \\< 0,08, Median \\< 0,04).\n-   Dabei ist PSD95 am geringsten und BDNF am höchsten metyhyliert.\n-   Bei BDNF zeigt sich, dass sich die Mittelwerte (Arithmetisch und Median) von T0 zu T1 leicht absenken und zu T2 wieder über das Niveau von T0 ansteigen.\n-   Bei Tau steigt das arithmetische Mittel der Methylierung leicht von T0 zu T1 und hält das Niveau bei T2.\n-   Bei PSD95 verbleibt der Median der Methylierun gleichbleibend bei 0, während das arithmetische Mittel der Methylierung von T0 zu T1 steigt aber bei T2 wieder auf das Ausgangsniveau zurückfällt.\n\n## EDA for important point and interval estimators\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(psych)\nlibrary(psychTools)\n\n## BDNF\ndescribe(bdnf_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad  min    max  range  skew\nID           1 144 108.17 62.41 121.50  109.68 80.80  1.0 202.00 201.00 -0.23\nStandort     2 144   0.62  0.49   1.00    0.66  0.00  0.0   1.00   1.00 -0.51\nGruppe*      3 144   1.47  0.50   1.00    1.46  0.00  1.0   2.00   1.00  0.14\nSex*         4 144   1.42  0.50   1.00    1.41  0.00  1.0   2.00   1.00  0.31\nAge_start    5 144  69.58  3.51  69.00   69.37  2.97 62.0  78.00  16.00  0.55\nCogTel       6 144  31.77  7.23  32.15   31.76  8.52 15.5  49.20  33.70  0.00\nT0           7 140   0.07  0.03   0.06    0.07  0.04  0.0   0.17   0.17  0.29\nT1           8 122   0.06  0.03   0.06    0.06  0.03  0.0   0.16   0.16  0.06\nT2           9  97   0.08  0.04   0.08    0.08  0.03  0.0   0.19   0.19  0.27\n          kurtosis   se\nID           -1.36 5.20\nStandort     -1.75 0.04\nGruppe*      -1.99 0.04\nSex*         -1.92 0.04\nAge_start    -0.47 0.29\nCogTel       -0.77 0.60\nT0           -0.30 0.00\nT1            0.18 0.00\nT2            0.18 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ndescribe(bdnf_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad  min    max  range  skew\nID           1 144 108.17 62.41 121.50  109.68 80.80  1.0 202.00 201.00 -0.23\nStandort     2 144   0.62  0.49   1.00    0.66  0.00  0.0   1.00   1.00 -0.51\nGruppe*      3 144   1.47  0.50   1.00    1.46  0.00  1.0   2.00   1.00  0.14\nSex*         4 144   1.42  0.50   1.00    1.41  0.00  1.0   2.00   1.00  0.31\nAge_start    5 144  69.58  3.51  69.00   69.37  2.97 62.0  78.00  16.00  0.55\nCogTel       6 144  31.77  7.23  32.15   31.76  8.52 15.5  49.20  33.70  0.00\nT0           7 140   0.04  0.04   0.03    0.03  0.04  0.0   0.18   0.18  1.14\nT1           8 122   0.03  0.03   0.03    0.03  0.04  0.0   0.12   0.12  0.86\nT2           9  97   0.05  0.04   0.04    0.04  0.04  0.0   0.21   0.21  1.52\n          kurtosis   se\nID           -1.36 5.20\nStandort     -1.75 0.04\nGruppe*      -1.99 0.04\nSex*         -1.92 0.04\nAge_start    -0.47 0.29\nCogTel       -0.77 0.60\nT0            0.78 0.00\nT1           -0.04 0.00\nT2            2.71 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## Tau\ndescribe(tau_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad   min    max  range  skew\nID           1 145 108.39 62.25 122.00  109.95 80.06  1.00 202.00 201.00 -0.24\nStandort     2 145   1.63  0.49   2.00    1.66  0.00  1.00   2.00   1.00 -0.52\nGruppe*      3 145   1.47  0.50   1.00    1.46  0.00  1.00   2.00   1.00  0.12\nSex*         4 145   1.43  0.50   1.00    1.41  0.00  1.00   2.00   1.00  0.29\nAge_start    5 145  69.57  3.50  69.00   69.36  2.97 62.00  78.00  16.00  0.56\nCogTel       6 145  31.77  7.20  32.40   31.77  8.60 15.50  49.20  33.70 -0.01\nT0           7 142   0.07  0.02   0.07    0.07  0.02  0.03   0.17   0.14  0.79\nT1           8 123   0.08  0.02   0.07    0.07  0.02  0.01   0.15   0.13  0.60\nT2           9  97   0.08  0.02   0.07    0.08  0.02  0.03   0.13   0.10  0.37\n          kurtosis   se\nID           -1.35 5.17\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel       -0.75 0.60\nT0            2.54 0.00\nT1            1.01 0.00\nT2            0.10 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ndescribe(tau_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad  min    max  range  skew\nID           1 145 108.39 62.25 122.00  109.95 80.06  1.0 202.00 201.00 -0.24\nStandort     2 145   1.63  0.49   2.00    1.66  0.00  1.0   2.00   1.00 -0.52\nGruppe*      3 145   1.47  0.50   1.00    1.46  0.00  1.0   2.00   1.00  0.12\nSex*         4 145   1.43  0.50   1.00    1.41  0.00  1.0   2.00   1.00  0.29\nAge_start    5 145  69.57  3.50  69.00   69.36  2.97 62.0  78.00  16.00  0.56\nCogTel       6 145  31.77  7.20  32.40   31.77  8.60 15.5  49.20  33.70 -0.01\nT0           7 142   0.02  0.01   0.02    0.02  0.01  0.0   0.05   0.05  0.19\nT1           8 123   0.02  0.02   0.02    0.02  0.01  0.0   0.12   0.12  1.93\nT2           9  97   0.02  0.01   0.01    0.02  0.01  0.0   0.06   0.06  0.69\n          kurtosis   se\nID           -1.35 5.17\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel       -0.75 0.60\nT0           -0.95 0.00\nT1            8.21 0.00\nT2            0.13 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## PSD95\ndescribe(psd95_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad   min    max  range  skew\nID           1 145 108.39 62.25 122.00  109.95 80.06  1.00 202.00 201.00 -0.24\nStandort     2 145   1.63  0.49   2.00    1.66  0.00  1.00   2.00   1.00 -0.52\nGruppe*      3 145   1.47  0.50   1.00    1.46  0.00  1.00   2.00   1.00  0.12\nSex*         4 145   1.43  0.50   1.00    1.41  0.00  1.00   2.00   1.00  0.29\nAge_start    5 145  69.57  3.50  69.00   69.36  2.97 62.00  78.00  16.00  0.56\nCogTel       6 145  31.77  7.20  32.40   31.77  8.60 15.50  49.20  33.70 -0.01\nT0           7 139   0.03  0.02   0.03    0.03  0.01  0.00   0.13   0.13  2.27\nT1           8 122   0.03  0.01   0.03    0.03  0.01  0.01   0.07   0.06  0.68\nT2           9  96   0.03  0.01   0.03    0.03  0.01  0.00   0.06   0.05 -0.09\n          kurtosis   se\nID           -1.35 5.17\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel       -0.75 0.60\nT0           11.51 0.00\nT1            0.03 0.00\nT2           -0.41 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ndescribe(psd95_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad  min    max  range  skew\nID           1 145 108.39 62.25  122.0  109.95 80.06  1.0 202.00 201.00 -0.24\nStandort     2 145   1.63  0.49    2.0    1.66  0.00  1.0   2.00   1.00 -0.52\nGruppe*      3 145   1.47  0.50    1.0    1.46  0.00  1.0   2.00   1.00  0.12\nSex*         4 145   1.43  0.50    1.0    1.41  0.00  1.0   2.00   1.00  0.29\nAge_start    5 145  69.57  3.50   69.0   69.36  2.97 62.0  78.00  16.00  0.56\nCogTel       6 145  31.77  7.20   32.4   31.77  8.60 15.5  49.20  33.70 -0.01\nT0           7 139   0.00  0.01    0.0    0.00  0.00  0.0   0.05   0.05  3.65\nT1           8 122   0.00  0.01    0.0    0.00  0.00  0.0   0.06   0.06  3.28\nT2           9  96   0.00  0.00    0.0    0.00  0.00  0.0   0.02   0.02  5.48\n          kurtosis   se\nID           -1.35 5.17\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel       -0.75 0.60\nT0           13.50 0.00\nT1           12.12 0.00\nT2           31.81 0.00\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n\n\n## Plotting EDA\n\n### Boxplots\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\neda_bdnf <- cpg\nbdnfcols_to_modify <- 5:14\n\neda_tau <- cpg\ntaucols_to_modify <- 19:67\n\neda_psd95 <- cpg\npsd95cols_to_modify <- 74:116\n\n# Remove the suffix 'BDNF' from the column names in columns 5 to 14\ncolnames(eda_bdnf)[bdnfcols_to_modify] <- sub(\"BDNF$\", \"\", colnames(eda_bdnf)[bdnfcols_to_modify])\n\n# remove \"Tau\ncolnames(eda_tau)[taucols_to_modify] <- sub(\"Tau$\", \"\", colnames(eda_tau)[taucols_to_modify])\n\n#remove PSD\ncolnames(eda_psd95)[psd95cols_to_modify] <- sub(\"PSD95$\", \"\", colnames(eda_psd95)[psd95cols_to_modify])\n\n# View the updated column names\nprint(colnames(eda_bdnf[c(5:14)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m148.\" \"m111.\" \"m087.\" \"m066.\" \"m058.\" \"m039.\" \"m035.\" \"m024.\" \"p018.\"\n[10] \"p020.\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(colnames(eda_tau[c(19:67)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m337.\"   \"m331.\"   \"m323.\"   \"m315.\"   \"m310.\"   \"m306.\"   \"m300.\"  \n [8] \"m293.\"   \"m287.\"   \"m277.\"   \"m249.\"   \"m219.\"   \"m210.\"   \"m207.\"  \n[15] \"m187.\"   \"m181.\"   \"m172.\"   \"m152.\"   \"m147.\"   \"m111.1.\" \"m109.\"  \n[22] \"m105.\"   \"m100.\"   \"m95.\"    \"m93.\"    \"m91.\"    \"m87.\"    \"m85.\"   \n[29] \"m80.\"    \"m73.\"    \"m70.\"    \"m68.\"    \"m58.\"    \"m53.\"    \"m41.\"   \n[36] \"m39.\"    \"m28.\"    \"m25.\"    \"m16.\"    \"m11.\"    \"m4.\"     \"m1.\"    \n[43] \"p3.\"     \"p7.\"     \"p11.\"    \"p19.\"    \"p23.\"    \"p25.\"    \"p27.\"   \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(colnames(eda_psd95[c(72:116)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m465.PSD95\" \"m418.PSD95\" \"m405.\"      \"m400.\"      \"m395.\"     \n [6] \"m392.\"      \"m349.\"      \"m340.\"      \"m329.\"      \"m326.\"     \n[11] \"m294.\"      \"m291.\"      \"m284.\"      \"m282.\"      \"m254.\"     \n[16] \"m249.1.\"    \"m236.\"      \"m226.\"      \"m199.\"      \"m193.\"     \n[21] \"m176.\"      \"m165.\"      \"m163.\"      \"m155.\"      \"m150.\"     \n[26] \"m124.\"      \"m113.\"      \"m92.\"       \"m83.\"       \"m77.\"      \n[31] \"m69.\"       \"m49.\"       \"m35.\"       \"m31.\"       \"m28.1.\"    \n[36] \"m24.\"       \"m18.\"       \"m11.1.\"     \"p23.1.\"     \"p31.\"      \n[41] \"p36.\"       \"p60.\"       \"p91.\"       \"p95.\"       \"p122.\"     \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#dev.new(width=14, height=7)\n#par(mfrow = c(3, 3))\n#layout(matrix(c(0, 1, 0, 2, 2, 2, 3, 3, 3), nrow = 3, byrow = TRUE))\n#with()!\nboxplot(eda_bdnf[, c(5:14)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the BDNF-CpGs\")\n```\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-5-1.png)\n:::\n\n```{.r .cell-code .hidden}\nboxplot(eda_tau[, c(19:67)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the Tau-CpGs\")\n```\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-5-2.png)\n:::\n\n```{.r .cell-code .hidden}\nboxplot(eda_psd95[, c(72:116)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the PSD95-CpGs\")\n```\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-5-3.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n#### Zoom to methlyated CpGs in Tau and PSD95\nsiehe \"131124_TBM mit Martin.qmd\" ab Zeile 1074\n\n### Violinplots\nSiehe \"Python_violinplots.ipynb\"\n\n\n### Lineplots\n\n#### BDNF\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#line Plot\nlibrary(ggplot2)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'ggplot2'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:psych':\n\n    %+%, alpha\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(tidyr)\n\n# Reshape the data into long format\neda_bdnf_long <- pivot_longer(eda_bdnf[c(1:14)], \n                              cols = 5:14, \n                              names_to = \"CpG\", \n                              values_to = \"Expression\")\n\n\n# Create the line plot\nggplot(eda_bdnf_long, aes(x = `CpG`, y = Expression, group = `ID.BDNF`, color = `Group.BDNF`)) +\n  geom_line() +  # Connect data points with lines\n  geom_point() + # Optionally add points to show individual values\n  labs(title = \"Line Plot of the BDNF-CpGs by Group\", \n       x = \"CpGs BDNF\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for readability\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 68 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 147 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-6-1.png)\n:::\n\n```{.r .cell-code .hidden}\n# Create the line plot\nggplot(eda_bdnf_long, aes(x = `CpG`, y = Expression, group = `ID.BDNF`, color = `Zeitpunkt.BDNF`)) +\n  geom_line() +  # Connect data points with lines\n  geom_point() + # Optionally add points to show individual values\n  labs(title = \"Line Plot of the BDNF-CpGs by Zeitpunkt\", \n       x = \"CpGs BDNF\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for readability\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 68 rows containing missing values or values outside the scale range\n(`geom_line()`).\nRemoved 147 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-6-2.png)\n:::\n\n```{.r .cell-code .hidden}\n# Create the line plot\nggplot(eda_bdnf_long, aes(x = `CpG`, y = Expression, group = `ID.BDNF`, color = `ID.BDNF`)) +\n  geom_line() +  # Connect data points with lines\n  geom_point() + # Optionally add points to show individual values\n  labs(title = \"Line Plot of the BDNF-CpGs by ID\", \n       x = \"CpGs BDNF\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for readability\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 68 rows containing missing values or values outside the scale range\n(`geom_line()`).\nRemoved 147 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-6-3.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n#### Tau\nto be continued\n\n#### PSD95\nto be continued\n\n\n\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#BDNF\neda_bdnf_long <- pivot_longer(eda_bdnf, \n                              cols = 5:14, \n                              names_to = \"CpG\", \n                              values_to = \"Expression\")\n#Tau\neda_tau_long <- pivot_longer(eda_tau, \n                              cols = 19:67, \n                              names_to = \"CpG\", \n                              values_to = \"Expression\")\n# PSD95\neda_psd95_long <- pivot_longer(eda_psd95, \n                              cols = 72:116, \n                              names_to = \"CpG\", \n                              values_to = \"Expression\")\n\n# Create the line plot showing individual changes between CpGs\n#BDNF\nggplot(eda_bdnf_long, aes(x = CpG, y = Expression, group = `ID.BDNF`, color = `ID.BDNF`)) +\n  geom_line(size = 0.5) +\n  geom_point(size = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, aes(group = CpG), size = 1) +  # Add smooth trend lines\n  labs(title = \"Change in Expression of BDNF-CpGs Between IDs\", \n       x = \"CpGs BDNF\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 147 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 68 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 147 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-7-1.png)\n:::\n\n```{.r .cell-code .hidden}\n#Tau\nggplot(eda_tau_long, aes(x = CpG, y = Expression, group = `ID.Tau`, color = `ID.Tau`)) +\n  geom_line(size = 0.5) +\n  geom_point(size = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, aes(group = CpG), size = 1) +  # Add smooth trend lines\n  labs(title = \"Change in Expression of Tau-CpGs Between IDss\", \n       x = \"CpGs Tau\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 496 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 297 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 496 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-7-2.png)\n:::\n\n```{.r .cell-code .hidden}\n#PSD95\nggplot(eda_psd95_long, aes(x = CpG, y = Expression, group = `ID.PSD95`, color = `ID.PSD95`)) +\n  geom_line(size = 0.5) +\n  geom_point(size = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, aes(group = CpG), size = 1) +  # Add smooth trend lines\n  labs(title = \"Change in Expression of PSD95-CpGs Between IDs\", \n       x = \"CpGs PSD95\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2083 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 450 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2083 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-7-3.png)\n:::\n:::\n\n\n\n\n\n\n\n\n\n**Cave: Vergleich mit Boxplot!**\n\n\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Line für Zeitpunkt\n# Create the line plot showing individual changes between CpGs\n#BDNF\nggplot(eda_bdnf_long, aes(x = CpG, y = Expression, group = `Zeitpunkt.BDNF`, color = `Zeitpunkt.BDNF`)) +\n  geom_line(size = 0.5) +\n  geom_point(size = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, aes(group = CpG), size = 1) +  # Add smooth trend lines\n  labs(title = \"Change in Expression of BDNF-CpGs Between Time Points\", \n       x = \"Group BDNF\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 147 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 60 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 147 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-8-1.png)\n:::\n\n```{.r .cell-code .hidden}\n#Tau\nggplot(eda_tau_long, aes(x = CpG, y = Expression, group = `Zeit.Tau`, color = `Zeit.Tau`)) +\n  geom_line(size = 0.5) +\n  geom_point(size = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, aes(group = CpG), size = 1) +  # Add smooth trend lines\n  labs(title = \"Change in Expression of Tau-CpGs Between Time Points\", \n       x = \"Group Tau\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 496 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 294 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 496 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-8-2.png)\n:::\n\n```{.r .cell-code .hidden}\n#PSD95\nggplot(eda_psd95_long, aes(x = CpG, y = Expression, group = `Zeitpunkt.PSD95`, color = `Zeitpunkt.PSD95`, na.rm = TRUE)) +\n  geom_line(size = 0.5) +\n  geom_point(size = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, aes(group = CpG), size = 1) +  # Add smooth trend lines\n  labs(title = \"Change in Expression of PSD95-CpGs Between Time Points\", \n       x = \"Group PSD95\", \n       y = \"Expression Level\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2083 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 360 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2083 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Exploratory-Data-Analysis_141124_files/figure-jats/unnamed-chunk-8-3.png)\n:::\n:::\n",
    "supporting": [
      "Exploratory-Data-Analysis_141124_files/figure-jats"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}