---
title: "PCA (mixOmics)"
editor: visual
---
## Data import
```{r}
#| echo: true
#| include: false

#data set with all CpGs in columns for EDA and PCA
library(tidyverse)

# load data
 ## BDNF
bdnf <- as_tibble(read.table('/home/kobi/Work/TBM-R-Analysis/tables/Ausgangstabellen/bdnf.txt', 
                   sep = "\t", 
                   header = TRUE, 
                   row.names = NULL, 
                   quote = ""))
bdnf[1:5,]

 ##Tau
tau <- as_tibble(read.table('/home/kobi/Work/TBM-R-Analysis/tables/Ausgangstabellen/tau.txt', 
                   sep = "\t", 
                   header = TRUE, 
                   row.names = NULL, 
                   quote = ""))
tau[1:5,]

 ## PSD95
psd95 <- as_tibble(read.table('/home/kobi/Work/TBM-R-Analysis/tables/Ausgangstabellen/psd95.txt', 
                   sep = "\t", 
                   header = TRUE, 
                   row.names = NULL, 
                   quote = ""))
psd95[1:5,]
```

## PCA with mixOmics

NIPALS means "Non-linear Iterative Partial Least Squares".


```{r}
library(mixOmics)

# Example structure similar to your data
cpg_bdnf <- drop_na(bdnf[, 11:20])    
bdnf_nona <- drop_na(bdnf) 

# CpG methylation columns
metadata <- bdnf[, c("Gruppe", "Sex", "Zeitpunkt")]  # sample info
#view(cpg_bdnf)

# Perform PCA
pca_bdnf_mix <- pca(X = cpg_bdnf, ncomp = 5, center = TRUE, scale = TRUE)

barplot(pca_bdnf_mix$prop_expl_var$X * 100,
        main = "BDNF PCA Scree Plot",
        xlab = "Principal Component",
        ylab = "Percent Variance Explained",
        col = "steelblue")


plotIndiv(pca_bdnf_mix, comp = c(1,2),
          legend = TRUE, title = "BDNF PCA - Group")


```

