{
  "hash": "b176ad15f902ad160bc05c2920bd8c60",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploratory Data Analysis\"\nauthor: \"Jonas J.R. Koberschinski\"\ndate: \"14-11-2024\"\nlast_modified: \"2026-01-29\"\noutput: html\n---\n\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\n#| label: setup\n#| include: false\n# Global setup: libraries & options\n\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup\n#| include: false\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(tibble)\nlibrary(forcats)\nlibrary(rlang)\n\nlibrary(psych)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'psych'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:ggplot2':\n\n    %+%, alpha\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup\n#| include: false\nlibrary(psychTools)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'psychTools'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup\n#| include: false\nlibrary(DescTools)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'DescTools'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:psych':\n\n    AUC, ICC, SD\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup\n#| include: false\nlibrary(crosstable)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'crosstable'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:DescTools':\n\n    N\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: setup\n#| include: false\nlibrary(flextable)\n\n# Global options\noptions(dplyr.summarise.inform = FALSE)\n```\n:::\n\n\n\n## Data import\n\n::: {.cell}\n\n```{.r .cell-code}\n#| label: data-import\n#| echo: true\n\n# load mean&median data\n# List of file names (without paths and extension)\nfile_names <- c(\n  \"bdnf_mean.txt\",\n  \"bdnf_median.txt\",\n  \n  \"tau_mean.txt\",\n  \"tau_median.txt\",\n  \n  \"psd95_mean.txt\",\n  \"psd95_median.txt\"\n)\n\n# Folder where the files are located\nsubfolder <- \"/home/kobi/Work/TBM-R-Analysis/tables/mean&median_tables\"\n\n# Loop through the file names, read each table, and assign it to a variable\nfor (file_name in file_names) {\n  # Construct the full file path by combining the subfolder and file name\n  file_path <- file.path(subfolder, file_name)\n  \n  # Remove the .txt extension to get the base name for the variable\n  var_name <- tools::file_path_sans_ext(file_name)\n  \n  # Read the table and assign it to a variable with the same name\n  assign(var_name, read.table(file_path, sep = \"\\t\", header = TRUE, row.names = NULL, quote = \"\"))\n}\n\n\n# load cpg-data\ncpg <- read.table(file = '/home/kobi/Work/TBM-R-Analysis/tables/Ausgangstabellen/cpg.txt', sep = \"\\t\", header = TRUE, row.names = NULL, quote = \"\")\n\n\n# load wide data\n# List of file names (without paths and extension)\nfile_names_wide <- c(\n  \"bdnf_mean_wide.txt\",\n  \"bdnf_median_wide.txt\",\n  \n  \"tau_mean_wide.txt\",\n  \"tau_median_wide.txt\",\n  \n  \"psd95_mean_wide.txt\",\n  \"psd95_median_wide.txt\"\n)\n\n# Folder where the files are located\nsubfolder_wide <- \"/home/kobi/Work/TBM-R-Analysis/tables/wide_format/\"\n\n# Loop through the file names, read each table, and assign it to a variable\nfor (file_name in file_names_wide) {\n  # Construct the full file path by combining the subfolder and file name\n  file_path <- file.path(subfolder_wide, file_name)\n  \n  # Remove the .txt extension to get the base name for the variable\n  var_name <- tools::file_path_sans_ext(file_name)\n  \n  # Read the table and assign it to a variable with the same name\n  assign(var_name, read.table(file_path, sep = \"\\t\", header = TRUE, row.names = NULL, quote = \"\"))\n}\n```\n:::\n\n\n# EDA (Exploratory Data Analysis)\n\n## Basic demopgrahics (Code to table summarized by chatgpt beyogen auf bdnf)\n\n\n::: {#tbl-demographics .cell}\n\n```{.r .cell-code .hidden}\n#| label: tbl-demographics\n#| results: asis\n\nmean_sd <- function(x, digits_mean = 2, digits_sd = 1) {\n  m <- mean(x, na.rm = TRUE)\n  s <- sd(x, na.rm = TRUE)\n  sprintf(paste0(\"%.\", digits_mean, \"f \\u00B1 %.\", digits_sd, \"f\"), m, s)\n}\n\nmin_max <- function(x, digits = 0) {\n  mn <- min(x, na.rm = TRUE)\n  mx <- max(x, na.rm = TRUE)\n  sprintf(paste0(\"%.\", digits, \"f / %.\", digits, \"f\"), mn, mx)\n}\n\nfemale_male_pct <- function(sex_vec, digits = 1) {\n  tab <- prop.table(table(sex_vec)) * 100\n  f <- unname(tab[\"F\"]); m <- unname(tab[\"M\"])\n  if (is.na(f)) f <- 0\n  if (is.na(m)) m <- 0\n  sprintf(paste0(\"%.\", digits, \"f / %.\", digits, \"f\"), f, m)\n}\n\ngroup_stats <- function(df) {\n  list(\n    mean_age_sd = mean_sd(df$Age_start, 2, 1),\n    min_max     = min_max(df$Age_start, 0),\n    n           = nrow(df),\n    fm_pct      = female_male_pct(df$Sex, 1)\n  )\n}\n\nbdnf_piano   <- subset(bdnf_median_wide, Gruppe == \"Piano\")\nbdnf_control <- subset(bdnf_median_wide, Gruppe == \"Controll\")\n\np <- group_stats(bdnf_piano)\nc <- group_stats(bdnf_control)\n\ncat(paste0(\n  \"| Characteristic        | Piano Group | Control Group |\\n\",\n  \"|-----------------------|------------:|--------------:|\\n\",\n  \"| Mean age \\u00B1 SD (years) | \", p$mean_age_sd, \" | \", c$mean_age_sd, \" |\\n\",\n  \"| Min / Max             | \", p$min_max, \" | \", c$min_max, \" |\\n\",\n  \"| N                     | \", p$n, \" | \", c$n, \" |\\n\",\n  \"| Female / Male (%)     | \", p$fm_pct, \" | \", c$fm_pct, \" |\\n\"\n))\n```\n\n| Characteristic        | Piano Group | Control Group |\n|-----------------------|------------:|--------------:|\n| Mean age ± SD (years) | 69.45 ± 3.2 | 69.70 ± 3.8 |\n| Min / Max             | 64 / 77 | 62 / 78 |\n| N                     | 67 | 77 |\n| Female / Male (%)     | 55.2 / 44.8 | 59.7 / 40.3 |\n:::\n\n\n\n### Extended (bezogen auf bdnf!)\n\n\n```{.r .cell-code .hidden}\n#| label: table1-demographics\n#| results: asis\n\n# ---- (5) robust labels: standardize Gruppe and Sex ----\ndf <- bdnf_median_wide\ndf$Gruppe <- trimws(df$Gruppe)\ndf$Sex    <- trimws(df$Sex)\n\ndf$Sex <- toupper(df$Sex)\ndf$Sex[df$Sex %in% c(\"FEMALE\")] <- \"F\"\ndf$Sex[df$Sex %in% c(\"MALE\")]   <- \"M\"\n\ng_piano   <- \"Piano\"\ng_control <- \"Controll\"\n\ndf_piano   <- subset(df, Gruppe == g_piano)\ndf_control <- subset(df, Gruppe == g_control)\ndf_overall <- df\n\n# ---- helpers ----\nfmt_mean_sd <- function(x, dm = 2, ds = 1) {\n  m <- mean(x, na.rm = TRUE); s <- sd(x, na.rm = TRUE)\n  sprintf(paste0(\"%.\", dm, \"f \\u00B1 %.\", ds, \"f\"), m, s)\n}\nfmt_median_iqr <- function(x, d = 2) {\n  med <- median(x, na.rm = TRUE)\n  q <- quantile(x, probs = c(0.25, 0.75), na.rm = TRUE, names = FALSE)\n  sprintf(paste0(\"%.\", d, \"f (%.\", d, \"f, %.\", d, \"f)\"), med, q[1], q[2])\n}\nfmt_min_max <- function(x, d = 0) {\n  mn <- min(x, na.rm = TRUE); mx <- max(x, na.rm = TRUE)\n  sprintf(paste0(\"%.\", d, \"f / %.\", d, \"f\"), mn, mx)\n}\nn_nonmiss <- function(x) sum(!is.na(x))\n\nfmt_fm_pct <- function(sex_vec, d = 1) {\n  tab <- prop.table(table(sex_vec)) * 100\n  f <- unname(tab[\"F\"]); m <- unname(tab[\"M\"])\n  if (is.na(f)) f <- 0\n  if (is.na(m)) m <- 0\n  sprintf(paste0(\"%.\", d, \"f / %.\", d, \"f\"), f, m)\n}\nfmt_missing <- function(x) {\n  n_miss <- sum(is.na(x))\n  n_tot  <- length(x)\n  sprintf(\"%d (%0.1f%%)\", n_miss, 100 * n_miss / n_tot)\n}\n\nsumm_one <- function(d) {\n  list(\n    n_participants = nrow(d),\n    age_nonmiss    = n_nonmiss(d$Age_start),\n    age_mean_sd    = fmt_mean_sd(d$Age_start, 2, 1),\n    age_median_iqr = fmt_median_iqr(d$Age_start, 2),\n    age_min_max    = fmt_min_max(d$Age_start, 0),\n    sex_fm_pct     = fmt_fm_pct(d$Sex, 1),\n    sex_missing    = fmt_missing(d$Sex),\n\n    t0_n           = n_nonmiss(d$T0),\n    t1_n           = n_nonmiss(d$T1),\n    t2_n           = n_nonmiss(d$T2),\n    t0_missing     = fmt_missing(d$T0),\n    t1_missing     = fmt_missing(d$T1),\n    t2_missing     = fmt_missing(d$T2),\n    total_samples  = n_nonmiss(d$T0) + n_nonmiss(d$T1) + n_nonmiss(d$T2)\n  )\n}\n\nP <- summ_one(df_piano)\nC <- summ_one(df_control)\nO <- summ_one(df_overall)\n\ncat(paste0(\n  \"| Characteristic | Piano | Control | Overall |\\n\",\n  \"|---|---:|---:|---:|\\n\",\n  \"| Participants (N) | \", P$n_participants, \" | \", C$n_participants, \" | \", O$n_participants, \" |\\n\",\n  \"| Age non-missing (n) | \", P$age_nonmiss, \" | \", C$age_nonmiss, \" | \", O$age_nonmiss, \" |\\n\",\n  \"| Mean age \\u00B1 SD (years) | \", P$age_mean_sd, \" | \", C$age_mean_sd, \" | \", O$age_mean_sd, \" |\\n\",\n  \"| Median (IQR) age (years) | \", P$age_median_iqr, \" | \", C$age_median_iqr, \" | \", O$age_median_iqr, \" |\\n\",\n  \"| Min / Max age (years) | \", P$age_min_max, \" | \", C$age_min_max, \" | \", O$age_min_max, \" |\\n\",\n  \"| Female / Male (%) | \", P$sex_fm_pct, \" | \", C$sex_fm_pct, \" | \", O$sex_fm_pct, \" |\\n\",\n  \"| Sex missing, n (%) | \", P$sex_missing, \" | \", C$sex_missing, \" | \", O$sex_missing, \" |\\n\",\n  \"| BDNF samples at T0 (n) | \", P$t0_n, \" | \", C$t0_n, \" | \", O$t0_n, \" |\\n\",\n  \"| BDNF samples at T1 (n) | \", P$t1_n, \" | \", C$t1_n, \" | \", O$t1_n, \" |\\n\",\n  \"| BDNF samples at T2 (n) | \", P$t2_n, \" | \", C$t2_n, \" | \", O$t2_n, \" |\\n\",\n  \"| Total BDNF samples (T0+T1+T2) | \", P$total_samples, \" | \", C$total_samples, \" | \", O$total_samples, \" |\\n\",\n  \"| Missing T0, n (%) | \", P$t0_missing, \" | \", C$t0_missing, \" | \", O$t0_missing, \" |\\n\",\n  \"| Missing T1, n (%) | \", P$t1_missing, \" | \", C$t1_missing, \" | \", O$t1_missing, \" |\\n\",\n  \"| Missing T2, n (%) | \", P$t2_missing, \" | \", C$t2_missing, \" | \", O$t2_missing, \" |\\n\"\n))\n```\n\n| Characteristic | Piano | Control | Overall |\n|---|---:|---:|---:|\n| Participants (N) | 67 | 77 | 144 |\n| Age non-missing (n) | 67 | 77 | 144 |\n| Mean age ± SD (years) | 69.45 ± 3.2 | 69.70 ± 3.8 | 69.58 ± 3.5 |\n| Median (IQR) age (years) | 69.00 (67.00, 71.00) | 69.00 (67.00, 73.00) | 69.00 (67.00, 71.25) |\n| Min / Max age (years) | 64 / 77 | 62 / 78 | 62 / 78 |\n| Female / Male (%) | 55.2 / 44.8 | 59.7 / 40.3 | 57.6 / 42.4 |\n| Sex missing, n (%) | 0 (0.0%) | 0 (0.0%) | 0 (0.0%) |\n| BDNF samples at T0 (n) | 65 | 75 | 140 |\n| BDNF samples at T1 (n) | 61 | 61 | 122 |\n| BDNF samples at T2 (n) | 50 | 47 | 97 |\n| Total BDNF samples (T0+T1+T2) | 176 | 183 | 359 |\n| Missing T0, n (%) | 2 (3.0%) | 2 (2.6%) | 4 (2.8%) |\n| Missing T1, n (%) | 6 (9.0%) | 16 (20.8%) | 22 (15.3%) |\n| Missing T2, n (%) | 17 (25.4%) | 30 (39.0%) | 47 (32.6%) |\n\n### Table with all genes\n\n\n```{.r .cell-code .hidden}\n#| label: table-samples-bdnf-tau-psd95\n#| results: asis\n\n# helper: robust trimming\nprep_df <- function(df) {\n  df$Gruppe <- trimws(df$Gruppe)\n  df\n}\n\nn_nonmiss <- function(x) sum(!is.na(x))\n\n# summarize one biomarker wide-df into a named row\nsumm_marker <- function(df, marker, g_piano = \"Piano\", g_control = \"Controll\") {\n  df <- prep_df(df)\n\n  dP <- subset(df, Gruppe == g_piano)\n  dC <- subset(df, Gruppe == g_control)\n  dO <- df\n\n  c(\n    Marker = marker,\n\n    Piano_T0 = n_nonmiss(dP$T0),\n    Piano_T1 = n_nonmiss(dP$T1),\n    Piano_T2 = n_nonmiss(dP$T2),\n    Piano_Total = n_nonmiss(dP$T0) + n_nonmiss(dP$T1) + n_nonmiss(dP$T2),\n\n    Control_T0 = n_nonmiss(dC$T0),\n    Control_T1 = n_nonmiss(dC$T1),\n    Control_T2 = n_nonmiss(dC$T2),\n    Control_Total = n_nonmiss(dC$T0) + n_nonmiss(dC$T1) + n_nonmiss(dC$T2),\n\n    Overall_T0 = n_nonmiss(dO$T0),\n    Overall_T1 = n_nonmiss(dO$T1),\n    Overall_T2 = n_nonmiss(dO$T2),\n    Overall_Total = n_nonmiss(dO$T0) + n_nonmiss(dO$T1) + n_nonmiss(dO$T2)\n  )\n}\n\nrows <- rbind(\n  summ_marker(bdnf_median_wide,  \"BDNF\"),\n  summ_marker(tau_median_wide,   \"TAU\"),\n  summ_marker(psd95_median_wide, \"PSD95\")\n)\n\n# render as markdown table\ncat(paste0(\n  \"| Marker | Piano T0 | Piano T1 | Piano T2 | Piano Total | Control T0 | Control T1 | Control T2 | Control Total | Overall T0 | Overall T1 | Overall T2 | Overall Total |\\n\",\n  \"|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\\n\",\n  paste(apply(rows, 1, function(r) {\n    paste0(\"| \", r[\"Marker\"], \" | \",\n           r[\"Piano_T0\"], \" | \", r[\"Piano_T1\"], \" | \", r[\"Piano_T2\"], \" | \", r[\"Piano_Total\"], \" | \",\n           r[\"Control_T0\"], \" | \", r[\"Control_T1\"], \" | \", r[\"Control_T2\"], \" | \", r[\"Control_Total\"], \" | \",\n           r[\"Overall_T0\"], \" | \", r[\"Overall_T1\"], \" | \", r[\"Overall_T2\"], \" | \", r[\"Overall_Total\"], \" |\")\n  }), collapse = \"\\n\"),\n  \"\\n\"\n))\n```\n\n| Marker | Piano T0 | Piano T1 | Piano T2 | Piano Total | Control T0 | Control T1 | Control T2 | Control Total | Overall T0 | Overall T1 | Overall T2 | Overall Total |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n| BDNF | 65 | 61 | 50 | 176 | 75 | 61 | 47 | 183 | 140 | 122 | 97 | 359 |\n| TAU | 67 | 63 | 50 | 180 | 75 | 60 | 47 | 182 | 142 | 123 | 97 | 362 |\n| PSD95 | 66 | 63 | 49 | 178 | 73 | 59 | 47 | 179 | 139 | 122 | 96 | 357 |\n### another demopgrahic (bezogen auf BDNF! villeicht ändern)\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nsumm_one <- function(d) {\n  list(\n    n_participants = nrow(d),\n    age_nonmiss    = n_nonmiss(d$Age_start),\n    age_mean_sd    = fmt_mean_sd(d$Age_start, 2, 1),\n    age_median_iqr = fmt_median_iqr(d$Age_start, 2),\n    age_min_max    = fmt_min_max(d$Age_start, 0),\n    sex_fm_pct     = fmt_fm_pct(d$Sex, 1),\n    sex_missing    = fmt_missing(d$Sex)\n  )\n}\n\nP <- summ_one(df_piano)\nC <- summ_one(df_control)\nO <- summ_one(df_overall)\n\ncat(paste0(\n  \"| Characteristic | Piano | Control | Overall |\\n\",\n  \"|---|---:|---:|---:|\\n\",\n  \"| Participants (N) | \", P$n_participants, \" | \", C$n_participants, \" | \", O$n_participants, \" |\\n\",\n  \"| Age non-missing (n) | \", P$age_nonmiss, \" | \", C$age_nonmiss, \" | \", O$age_nonmiss, \" |\\n\",\n  \"| Mean age \\u00B1 SD (years) | \", P$age_mean_sd, \" | \", C$age_mean_sd, \" | \", O$age_mean_sd, \" |\\n\",\n  \"| Median (IQR) age (years) | \", P$age_median_iqr, \" | \", C$age_median_iqr, \" | \", O$age_median_iqr, \" |\\n\",\n  \"| Min / Max age (years) | \", P$age_min_max, \" | \", C$age_min_max, \" | \", O$age_min_max, \" |\\n\",\n  \"| Female / Male (%) | \", P$sex_fm_pct, \" | \", C$sex_fm_pct, \" | \", O$sex_fm_pct, \" |\\n\",\n  \"| Sex missing, n (%) | \", P$sex_missing, \" | \", C$sex_missing, \" | \", O$sex_missing, \" |\\n\"\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n| Characteristic | Piano | Control | Overall |\n|---|---:|---:|---:|\n| Participants (N) | 67 | 77 | 144 |\n| Age non-missing (n) | 67 | 77 | 144 |\n| Mean age ± SD (years) | 69.45 ± 3.2 | 69.70 ± 3.8 | 69.58 ± 3.5 |\n| Median (IQR) age (years) | 69.00 (67.00, 71.00) | 69.00 (67.00, 73.00) | 69.00 (67.00, 71.25) |\n| Min / Max age (years) | 64 / 77 | 62 / 78 | 62 / 78 |\n| Female / Male (%) | 55.2 / 44.8 | 59.7 / 40.3 | 57.6 / 42.4 |\n| Sex missing, n (%) | 0 (0.0%) | 0 (0.0%) | 0 (0.0%) |\n```\n\n\n:::\n:::\n\n\n### all genes with missing\n\n\n```{.r .cell-code .hidden}\n#| label: table-genes-missing\n#| results: asis\n\nprep_df <- function(df) {\n  df$Gruppe <- trimws(df$Gruppe)\n  df\n}\n\nn_nonmiss <- function(x) sum(!is.na(x))\n\nfmt_missing <- function(x) {\n  n_miss <- sum(is.na(x))\n  n_tot  <- length(x)\n  sprintf(\"%d (%0.1f%%)\", n_miss, 100 * n_miss / n_tot)\n}\n\nsumm_marker <- function(df, marker, g_piano = \"Piano\", g_control = \"Controll\") {\n  df <- prep_df(df)\n\n  dP <- subset(df, Gruppe == g_piano)\n  dC <- subset(df, Gruppe == g_control)\n  dO <- df\n\n  # counts\n  P_t0 <- n_nonmiss(dP$T0); P_t1 <- n_nonmiss(dP$T1); P_t2 <- n_nonmiss(dP$T2)\n  C_t0 <- n_nonmiss(dC$T0); C_t1 <- n_nonmiss(dC$T1); C_t2 <- n_nonmiss(dC$T2)\n  O_t0 <- n_nonmiss(dO$T0); O_t1 <- n_nonmiss(dO$T1); O_t2 <- n_nonmiss(dO$T2)\n\n  # missing (%)\n  P_m0 <- fmt_missing(dP$T0); P_m1 <- fmt_missing(dP$T1); P_m2 <- fmt_missing(dP$T2)\n  C_m0 <- fmt_missing(dC$T0); C_m1 <- fmt_missing(dC$T1); C_m2 <- fmt_missing(dC$T2)\n  O_m0 <- fmt_missing(dO$T0); O_m1 <- fmt_missing(dO$T1); O_m2 <- fmt_missing(dO$T2)\n\n  list(\n    marker = marker,\n    Piano   = list(t0 = P_t0, t1 = P_t1, t2 = P_t2,\n                   tot = P_t0 + P_t1 + P_t2,\n                   m0 = P_m0, m1 = P_m1, m2 = P_m2),\n    Control = list(t0 = C_t0, t1 = C_t1, t2 = C_t2,\n                   tot = C_t0 + C_t1 + C_t2,\n                   m0 = C_m0, m1 = C_m1, m2 = C_m2),\n    Overall = list(t0 = O_t0, t1 = O_t1, t2 = O_t2,\n                   tot = O_t0 + O_t1 + O_t2,\n                   m0 = O_m0, m1 = O_m1, m2 = O_m2)\n  )\n}\n\nrows <- list(\n  summ_marker(bdnf_median_wide,  \"BDNF\"),\n  summ_marker(tau_median_wide,   \"TAU\"),\n  summ_marker(psd95_median_wide, \"PSD95\")\n)\n\ncat(paste0(\n  \"| Marker | Piano T0 n | Piano T1 n | Piano T2 n | Piano Total | Piano missing T0 | Piano missing T1 | Piano missing T2 | Control T0 n | Control T1 n | Control T2 n | Control Total | Control missing T0 | Control missing T1 | Control missing T2 | Overall T0 n | Overall T1 n | Overall T2 n | Overall Total | Overall missing T0 | Overall missing T1 | Overall missing T2 |\\n\",\n  \"|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\\n\",\n  paste(vapply(rows, function(r) {\n    paste0(\n      \"| \", r$marker,\n      \" | \", r$Piano$t0, \" | \", r$Piano$t1, \" | \", r$Piano$t2, \" | \", r$Piano$tot,\n      \" | \", r$Piano$m0, \" | \", r$Piano$m1, \" | \", r$Piano$m2,\n      \" | \", r$Control$t0, \" | \", r$Control$t1, \" | \", r$Control$t2, \" | \", r$Control$tot,\n      \" | \", r$Control$m0, \" | \", r$Control$m1, \" | \", r$Control$m2,\n      \" | \", r$Overall$t0, \" | \", r$Overall$t1, \" | \", r$Overall$t2, \" | \", r$Overall$tot,\n      \" | \", r$Overall$m0, \" | \", r$Overall$m1, \" | \", r$Overall$m2,\n      \" |\"\n    )\n  }, character(1)), collapse = \"\\n\"),\n  \"\\n\"\n))\n```\n\n| Marker | Piano T0 n | Piano T1 n | Piano T2 n | Piano Total | Piano missing T0 | Piano missing T1 | Piano missing T2 | Control T0 n | Control T1 n | Control T2 n | Control Total | Control missing T0 | Control missing T1 | Control missing T2 | Overall T0 n | Overall T1 n | Overall T2 n | Overall Total | Overall missing T0 | Overall missing T1 | Overall missing T2 |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n| BDNF | 65 | 61 | 50 | 176 | 2 (3.0%) | 6 (9.0%) | 17 (25.4%) | 75 | 61 | 47 | 183 | 2 (2.6%) | 16 (20.8%) | 30 (39.0%) | 140 | 122 | 97 | 359 | 4 (2.8%) | 22 (15.3%) | 47 (32.6%) |\n| TAU | 67 | 63 | 50 | 180 | 1 (1.5%) | 5 (7.4%) | 18 (26.5%) | 75 | 60 | 47 | 182 | 2 (2.6%) | 17 (22.1%) | 30 (39.0%) | 142 | 123 | 97 | 362 | 3 (2.1%) | 22 (15.2%) | 48 (33.1%) |\n| PSD95 | 66 | 63 | 49 | 178 | 2 (2.9%) | 5 (7.4%) | 19 (27.9%) | 73 | 59 | 47 | 179 | 4 (5.2%) | 18 (23.4%) | 30 (39.0%) | 139 | 122 | 96 | 357 | 6 (4.1%) | 23 (15.9%) | 49 (33.8%) |\n\n\n```{.r .cell-code .hidden}\n#| label: tables-per-marker\n#| results: asis\n\n# ---------- helpers ----------\nfmt_mean_sd <- function(x, dm = 2, ds = 1) {\n  m <- mean(x, na.rm = TRUE); s <- sd(x, na.rm = TRUE)\n  sprintf(paste0(\"%.\", dm, \"f \\u00B1 %.\", ds, \"f\"), m, s)\n}\nfmt_median_iqr <- function(x, d = 2) {\n  med <- median(x, na.rm = TRUE)\n  q <- quantile(x, probs = c(0.25, 0.75), na.rm = TRUE, names = FALSE)\n  sprintf(paste0(\"%.\", d, \"f (%.\", d, \"f, %.\", d, \"f)\"), med, q[1], q[2])\n}\nfmt_min_max <- function(x, d = 0) {\n  mn <- min(x, na.rm = TRUE); mx <- max(x, na.rm = TRUE)\n  sprintf(paste0(\"%.\", d, \"f / %.\", d, \"f\"), mn, mx)\n}\nn_nonmiss <- function(x) sum(!is.na(x))\nfmt_missing <- function(x) {\n  n_miss <- sum(is.na(x)); n_tot <- length(x)\n  sprintf(\"%d (%0.1f%%)\", n_miss, 100 * n_miss / n_tot)\n}\nfmt_fm_pct <- function(sex_vec, d = 1) {\n  sex_vec <- trimws(toupper(sex_vec))\n  sex_vec[sex_vec %in% c(\"FEMALE\")] <- \"F\"\n  sex_vec[sex_vec %in% c(\"MALE\")]   <- \"M\"\n  tab <- prop.table(table(sex_vec)) * 100\n  f <- unname(tab[\"F\"]); m <- unname(tab[\"M\"])\n  if (is.na(f)) f <- 0\n  if (is.na(m)) m <- 0\n  sprintf(paste0(\"%.\", d, \"f / %.\", d, \"f\"), f, m)\n}\n\nsumm_one <- function(d) {\n  list(\n    n_participants = nrow(d),\n    age_nonmiss    = n_nonmiss(d$Age_start),\n    age_mean_sd    = fmt_mean_sd(d$Age_start, 2, 1),\n    age_median_iqr = fmt_median_iqr(d$Age_start, 2),\n    age_min_max    = fmt_min_max(d$Age_start, 0),\n    sex_fm_pct     = fmt_fm_pct(d$Sex, 1),\n    sex_missing    = fmt_missing(d$Sex),\n\n    t0_n           = n_nonmiss(d$T0),\n    t1_n           = n_nonmiss(d$T1),\n    t2_n           = n_nonmiss(d$T2),\n    t0_missing     = fmt_missing(d$T0),\n    t1_missing     = fmt_missing(d$T1),\n    t2_missing     = fmt_missing(d$T2),\n    total_samples  = n_nonmiss(d$T0) + n_nonmiss(d$T1) + n_nonmiss(d$T2)\n  )\n}\n\n# ---------- main function: prints ONE table for one marker ----------\nprint_marker_table <- function(df_wide, marker_name,\n                               g_piano = \"Piano\", g_control = \"Controll\") {\n  df <- df_wide\n  df$Gruppe <- trimws(df$Gruppe)\n  df$Sex    <- trimws(df$Sex)\n\n  df_piano   <- subset(df, Gruppe == g_piano)\n  df_control <- subset(df, Gruppe == g_control)\n  df_overall <- df\n\n  P <- summ_one(df_piano)\n  C <- summ_one(df_control)\n  O <- summ_one(df_overall)\n\n  cat(\"\\n\\n### \", marker_name, \"\\n\\n\", sep = \"\")\n  cat(paste0(\n    \"| Characteristic | Piano | Control | Overall |\\n\",\n    \"|---|---:|---:|---:|\\n\",\n    \"| Participants (N) | \", P$n_participants, \" | \", C$n_participants, \" | \", O$n_participants, \" |\\n\",\n    \"| Age non-missing (n) | \", P$age_nonmiss, \" | \", C$age_nonmiss, \" | \", O$age_nonmiss, \" |\\n\",\n    \"| Mean age \\u00B1 SD (years) | \", P$age_mean_sd, \" | \", C$age_mean_sd, \" | \", O$age_mean_sd, \" |\\n\",\n    \"| Median (IQR) age (years) | \", P$age_median_iqr, \" | \", C$age_median_iqr, \" | \", O$age_median_iqr, \" |\\n\",\n    \"| Min / Max age (years) | \", P$age_min_max, \" | \", C$age_min_max, \" | \", O$age_min_max, \" |\\n\",\n    \"| Female / Male (%) | \", P$sex_fm_pct, \" | \", C$sex_fm_pct, \" | \", O$sex_fm_pct, \" |\\n\",\n    \"| Sex missing, n (%) | \", P$sex_missing, \" | \", C$sex_missing, \" | \", O$sex_missing, \" |\\n\",\n    \"| \", marker_name, \" samples at T0 (n) | \", P$t0_n, \" | \", C$t0_n, \" | \", O$t0_n, \" |\\n\",\n    \"| \", marker_name, \" samples at T1 (n) | \", P$t1_n, \" | \", C$t1_n, \" | \", O$t1_n, \" |\\n\",\n    \"| \", marker_name, \" samples at T2 (n) | \", P$t2_n, \" | \", C$t2_n, \" | \", O$t2_n, \" |\\n\",\n    \"| Total \", marker_name, \" samples (T0+T1+T2) | \", P$total_samples, \" | \", C$total_samples, \" | \", O$total_samples, \" |\\n\",\n    \"| Missing T0, n (%) | \", P$t0_missing, \" | \", C$t0_missing, \" | \", O$t0_missing, \" |\\n\",\n    \"| Missing T1, n (%) | \", P$t1_missing, \" | \", C$t1_missing, \" | \", O$t1_missing, \" |\\n\",\n    \"| Missing T2, n (%) | \", P$t2_missing, \" | \", C$t2_missing, \" | \", O$t2_missing, \" |\\n\"\n  ))\n}\n\n# ---------- print the three separate tables ----------\nprint_marker_table(bdnf_median_wide,  \"BDNF\")\n```\n\n\n\n### BDNF\n\n| Characteristic | Piano | Control | Overall |\n|---|---:|---:|---:|\n| Participants (N) | 67 | 77 | 144 |\n| Age non-missing (n) | 67 | 77 | 144 |\n| Mean age ± SD (years) | 69.45 ± 3.2 | 69.70 ± 3.8 | 69.58 ± 3.5 |\n| Median (IQR) age (years) | 69.00 (67.00, 71.00) | 69.00 (67.00, 73.00) | 69.00 (67.00, 71.25) |\n| Min / Max age (years) | 64 / 77 | 62 / 78 | 62 / 78 |\n| Female / Male (%) | 55.2 / 44.8 | 59.7 / 40.3 | 57.6 / 42.4 |\n| Sex missing, n (%) | 0 (0.0%) | 0 (0.0%) | 0 (0.0%) |\n| BDNF samples at T0 (n) | 65 | 75 | 140 |\n| BDNF samples at T1 (n) | 61 | 61 | 122 |\n| BDNF samples at T2 (n) | 50 | 47 | 97 |\n| Total BDNF samples (T0+T1+T2) | 176 | 183 | 359 |\n| Missing T0, n (%) | 2 (3.0%) | 2 (2.6%) | 4 (2.8%) |\n| Missing T1, n (%) | 6 (9.0%) | 16 (20.8%) | 22 (15.3%) |\n| Missing T2, n (%) | 17 (25.4%) | 30 (39.0%) | 47 (32.6%) |\n\n```{.r .cell-code .hidden}\n#| label: tables-per-marker\n#| results: asis\n\nprint_marker_table(tau_median_wide,   \"TAU\")\n```\n\n\n\n### TAU\n\n| Characteristic | Piano | Control | Overall |\n|---|---:|---:|---:|\n| Participants (N) | 68 | 77 | 145 |\n| Age non-missing (n) | 68 | 77 | 145 |\n| Mean age ± SD (years) | 69.43 ± 3.1 | 69.70 ± 3.8 | 69.57 ± 3.5 |\n| Median (IQR) age (years) | 69.00 (67.00, 71.00) | 69.00 (67.00, 73.00) | 69.00 (67.00, 71.00) |\n| Min / Max age (years) | 64 / 77 | 62 / 78 | 62 / 78 |\n| Female / Male (%) | 54.4 / 45.6 | 59.7 / 40.3 | 57.2 / 42.8 |\n| Sex missing, n (%) | 0 (0.0%) | 0 (0.0%) | 0 (0.0%) |\n| TAU samples at T0 (n) | 67 | 75 | 142 |\n| TAU samples at T1 (n) | 63 | 60 | 123 |\n| TAU samples at T2 (n) | 50 | 47 | 97 |\n| Total TAU samples (T0+T1+T2) | 180 | 182 | 362 |\n| Missing T0, n (%) | 1 (1.5%) | 2 (2.6%) | 3 (2.1%) |\n| Missing T1, n (%) | 5 (7.4%) | 17 (22.1%) | 22 (15.2%) |\n| Missing T2, n (%) | 18 (26.5%) | 30 (39.0%) | 48 (33.1%) |\n\n```{.r .cell-code .hidden}\n#| label: tables-per-marker\n#| results: asis\n\nprint_marker_table(psd95_median_wide, \"PSD95\")\n```\n\n\n\n### PSD95\n\n| Characteristic | Piano | Control | Overall |\n|---|---:|---:|---:|\n| Participants (N) | 68 | 77 | 145 |\n| Age non-missing (n) | 68 | 77 | 145 |\n| Mean age ± SD (years) | 69.43 ± 3.1 | 69.70 ± 3.8 | 69.57 ± 3.5 |\n| Median (IQR) age (years) | 69.00 (67.00, 71.00) | 69.00 (67.00, 73.00) | 69.00 (67.00, 71.00) |\n| Min / Max age (years) | 64 / 77 | 62 / 78 | 62 / 78 |\n| Female / Male (%) | 54.4 / 45.6 | 59.7 / 40.3 | 57.2 / 42.8 |\n| Sex missing, n (%) | 0 (0.0%) | 0 (0.0%) | 0 (0.0%) |\n| PSD95 samples at T0 (n) | 66 | 73 | 139 |\n| PSD95 samples at T1 (n) | 63 | 59 | 122 |\n| PSD95 samples at T2 (n) | 49 | 47 | 96 |\n| Total PSD95 samples (T0+T1+T2) | 178 | 179 | 357 |\n| Missing T0, n (%) | 2 (2.9%) | 4 (5.2%) | 6 (4.1%) |\n| Missing T1, n (%) | 5 (7.4%) | 18 (23.4%) | 23 (15.9%) |\n| Missing T2, n (%) | 19 (27.9%) | 30 (39.0%) | 49 (33.8%) |\n### Union demographics across all genes\n\n```{.r .cell-code .hidden}\n#| label: table-union-demographics-genes\n#| results: asis\n\nlibrary(dplyr)\n\ng_piano   <- \"Piano\"\ng_control <- \"Controll\"\n\n# ---- helpers ----\nmean_sd <- function(x) sprintf(\"%.2f \\u00B1 %.1f\", mean(x, na.rm=TRUE), sd(x, na.rm=TRUE))\nmedian_iqr <- function(x) {\n  q <- quantile(x, c(.25,.5,.75), na.rm=TRUE, names = FALSE)\n  sprintf(\"%.2f (%.2f, %.2f)\", q[2], q[1], q[3])\n}\nmin_max <- function(x) sprintf(\"%.0f / %.0f\", min(x, na.rm=TRUE), max(x, na.rm=TRUE))\n\nfmt_missing <- function(x) sprintf(\"%d (%.1f%%)\", sum(is.na(x)), 100 * mean(is.na(x)))\n\nfm_pct <- function(sex_vec) {\n  s <- toupper(trimws(sex_vec))\n  s[s %in% c(\"FEMALE\")] <- \"F\"\n  s[s %in% c(\"MALE\")]   <- \"M\"\n  tab <- prop.table(table(s)) * 100\n  f <- unname(tab[\"F\"]); m <- unname(tab[\"M\"])\n  if (is.na(f)) f <- 0\n  if (is.na(m)) m <- 0\n  sprintf(\"%.1f / %.1f\", f, m)\n}\n\nn_nonmiss <- function(x) sum(!is.na(x))\n\n# ---- UNION master for demographics (unique IDs across all genes) ----\ndemo_union <- bind_rows(\n  bdnf_median_wide  %>% select(ID, Gruppe, Sex, Age_start),\n  tau_median_wide   %>% select(ID, Gruppe, Sex, Age_start),\n  psd95_median_wide %>% select(ID, Gruppe, Sex, Age_start)\n) %>%\n  mutate(\n    Gruppe = trimws(Gruppe),\n    Sex    = trimws(Sex)\n  ) %>%\n  group_by(ID) %>%\n  summarise(\n    Gruppe    = first(na.omit(Gruppe)),\n    Sex       = first(na.omit(Sex)),\n    Age_start = first(na.omit(Age_start)),\n    .groups = \"drop\"\n  )\n\nsumm_demo <- function(d) list(\n  N = nrow(d),\n  age_n = sum(!is.na(d$Age_start)),\n  mean_sd = mean_sd(d$Age_start),\n  med_iqr = median_iqr(d$Age_start),\n  minmax = min_max(d$Age_start),\n  fm = fm_pct(d$Sex),\n  sex_miss = fmt_missing(d$Sex)\n)\n\nP <- summ_demo(filter(demo_union, Gruppe == g_piano))\nC <- summ_demo(filter(demo_union, Gruppe == g_control))\nO <- summ_demo(demo_union)\n\n# ---- gene rows: n and missing per timepoint for each marker ----\nprep_gene <- function(df) mutate(df, Gruppe = trimws(Gruppe))\n\ngene_stats <- function(df, marker) {\n  df <- prep_gene(df)\n  P <- filter(df, Gruppe == g_piano)\n  C <- filter(df, Gruppe == g_control)\n  O <- df\n\n  list(\n    marker = marker,\n    P = list(t0=n_nonmiss(P$T0), t1=n_nonmiss(P$T1), t2=n_nonmiss(P$T2),\n             m0=fmt_missing(P$T0), m1=fmt_missing(P$T1), m2=fmt_missing(P$T2)),\n    C = list(t0=n_nonmiss(C$T0), t1=n_nonmiss(C$T1), t2=n_nonmiss(C$T2),\n             m0=fmt_missing(C$T0), m1=fmt_missing(C$T1), m2=fmt_missing(C$T2)),\n    O = list(t0=n_nonmiss(O$T0), t1=n_nonmiss(O$T1), t2=n_nonmiss(O$T2),\n             m0=fmt_missing(O$T0), m1=fmt_missing(O$T1), m2=fmt_missing(O$T2))\n  )\n}\n\ngenes <- list(\n  gene_stats(bdnf_median_wide,  \"BDNF\"),\n  gene_stats(tau_median_wide,   \"TAU\"),\n  gene_stats(psd95_median_wide, \"PSD95\")\n)\n\n# ---- print unified table ----\ncat(paste0(\n  \"| Characteristic | Piano | Control | Overall |\\n\",\n  \"|---|---:|---:|---:|\\n\",\n  \"| Participants (N) | \", P$N, \" | \", C$N, \" | \", O$N, \" |\\n\",\n  \"| Age non-missing (n) | \", P$age_n, \" | \", C$age_n, \" | \", O$age_n, \" |\\n\",\n  \"| Mean age \\u00B1 SD (years) | \", P$mean_sd, \" | \", C$mean_sd, \" | \", O$mean_sd, \" |\\n\",\n  \"| Median (IQR) age (years) | \", P$med_iqr, \" | \", C$med_iqr, \" | \", O$med_iqr, \" |\\n\",\n  \"| Min / Max age (years) | \", P$minmax, \" | \", C$minmax, \" | \", O$minmax, \" |\\n\",\n  \"| Female / Male (%) | \", P$fm, \" | \", C$fm, \" | \", O$fm, \" |\\n\",\n  \"| Sex missing, n (%) | \", P$sex_miss, \" | \", C$sex_miss, \" | \", O$sex_miss, \" |\\n\"\n))\n```\n\n| Characteristic | Piano | Control | Overall |\n|---|---:|---:|---:|\n| Participants (N) | 67 | 77 | 144 |\n| Age non-missing (n) | 67 | 77 | 144 |\n| Mean age ± SD (years) | 69.45 ± 3.2 | 69.70 ± 3.8 | 69.58 ± 3.5 |\n| Median (IQR) age (years) | 69.00 (67.00, 71.00) | 69.00 (67.00, 73.00) | 69.00 (67.00, 71.25) |\n| Min / Max age (years) | 64 / 77 | 62 / 78 | 62 / 78 |\n| Female / Male (%) | 55.2 / 44.8 | 59.7 / 40.3 | 57.6 / 42.4 |\n| Sex missing, n (%) | 0 (0.0%) | 0 (0.0%) | 0 (0.0%) |\n\n```{.r .cell-code .hidden}\n#| label: table-union-demographics-genes\n#| results: asis\n\nfor (r in genes) {\n  cat(paste0(\n    \"| \", r$marker, \" samples at T0 (n) | \", r$P$t0, \" | \", r$C$t0, \" | \", r$O$t0, \" |\\n\",\n    \"| \", r$marker, \" samples at T1 (n) | \", r$P$t1, \" | \", r$C$t1, \" | \", r$O$t1, \" |\\n\",\n    \"| \", r$marker, \" samples at T2 (n) | \", r$P$t2, \" | \", r$C$t2, \" | \", r$O$t2, \" |\\n\",\n    \"| \", r$marker, \" missing T0, n (%) | \", r$P$m0, \" | \", r$C$m0, \" | \", r$O$m0, \" |\\n\",\n    \"| \", r$marker, \" missing T1, n (%) | \", r$P$m1, \" | \", r$C$m1, \" | \", r$O$m1, \" |\\n\",\n    \"| \", r$marker, \" missing T2, n (%) | \", r$P$m2, \" | \", r$C$m2, \" | \", r$O$m2, \" |\\n\"\n  ))\n}\n```\n\n| BDNF samples at T0 (n) | 65 | 75 | 140 |\n| BDNF samples at T1 (n) | 61 | 61 | 122 |\n| BDNF samples at T2 (n) | 50 | 47 | 97 |\n| BDNF missing T0, n (%) | 2 (3.0%) | 2 (2.6%) | 4 (2.8%) |\n| BDNF missing T1, n (%) | 6 (9.0%) | 16 (20.8%) | 22 (15.3%) |\n| BDNF missing T2, n (%) | 17 (25.4%) | 30 (39.0%) | 47 (32.6%) |\n| TAU samples at T0 (n) | 67 | 75 | 142 |\n| TAU samples at T1 (n) | 63 | 60 | 123 |\n| TAU samples at T2 (n) | 50 | 47 | 97 |\n| TAU missing T0, n (%) | 1 (1.5%) | 2 (2.6%) | 3 (2.1%) |\n| TAU missing T1, n (%) | 5 (7.4%) | 17 (22.1%) | 22 (15.2%) |\n| TAU missing T2, n (%) | 18 (26.5%) | 30 (39.0%) | 48 (33.1%) |\n| PSD95 samples at T0 (n) | 66 | 73 | 139 |\n| PSD95 samples at T1 (n) | 63 | 59 | 122 |\n| PSD95 samples at T2 (n) | 49 | 47 | 96 |\n| PSD95 missing T0, n (%) | 2 (2.9%) | 4 (5.2%) | 6 (4.1%) |\n| PSD95 missing T1, n (%) | 5 (7.4%) | 18 (23.4%) | 23 (15.9%) |\n| PSD95 missing T2, n (%) | 19 (27.9%) | 30 (39.0%) | 49 (33.8%) |\n\n## Summary Statistics be\n\n### \n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ntab <- data.frame(\n  Marker = c(\"BDNF\", \"Tau\", \"PSD95\"),\n  Mean = c(\n    mean(bdnf_mean$Mean, na.rm = TRUE),\n    mean(tau_mean$Mean, na.rm = TRUE),\n    mean(psd95_mean$Mean, na.rm = TRUE)\n  ),\n  SD = c(\n    sd(bdnf_mean$Mean, na.rm = TRUE),\n    sd(tau_mean$Mean, na.rm = TRUE),\n    sd(psd95_mean$Mean, na.rm = TRUE)\n  )\n)\n\ntab$`Mean ± SD` <- sprintf(\"%.3f ± %.3f\", tab$Mean, tab$SD)\ntab <- tab[, c(\"Marker\", \"Mean ± SD\")]\n\n# Print as markdown\ncat(\"| Marker | Mean ± SD |\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n| Marker | Mean ± SD |\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"|--------|-----------|\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|--------|-----------|\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\napply(tab, 1, function(r) cat(sprintf(\"| %s | %s |\\n\", r[1], r[2])))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n| BDNF | 0.070 ± 0.034 |\n| Tau | 0.075 ± 0.020 |\n| PSD95 | 0.031 ± 0.014 |\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n:::\n\n\n## Plots\n\n### Interaction Plots by Gene (mean across CpGs)\n\n\n::: {#cell-fig-interactions-no-group .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-no-group\n#| fig-cap: \"Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95.\"\n#| fig-width: 8\n#| fig-height: 10\n\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(patchwork)\n\nmake_nogroup_plot <- function(df_wide, title,\n                              ylab = \"Mean methylation (mean across CpGs)\") {\n\n  df_long <- df_wide %>%\n    pivot_longer(cols = c(T0, T1, T2),\n                 names_to = \"Zeitpunkt\",\n                 values_to = \"Mean\") %>%\n    mutate(Zeitpunkt = factor(Zeitpunkt, levels = c(\"T0\",\"T1\",\"T2\")))\n\n  sum0 <- df_long %>%\n    group_by(Zeitpunkt) %>%\n    summarise(\n      n = sum(!is.na(Mean)),\n      mean = mean(Mean, na.rm = TRUE),\n      se   = sd(Mean, na.rm = TRUE) / sqrt(n),\n      .groups = \"drop\"\n    )\n\n  ggplot(sum0, aes(x = Zeitpunkt, y = mean, group = 1)) +\n    geom_line() +\n    geom_point() +\n    geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +\n    theme_classic() +\n    labs(title = title, x = \"Time Point\", y = ylab,\n         caption = \"Points show mean across participants; error bars are ±SE.\")\n}\n\np_bdnf0  <- make_nogroup_plot(bdnf_mean_wide,  title = \"BDNF\")\np_tau0   <- make_nogroup_plot(tau_mean_wide,   title = \"Tau\")\np_psd950 <- make_nogroup_plot(psd95_mean_wide, title = \"PSD95\")\n\n(p_bdnf0 / p_tau0 / p_psd950)\n```\n\n::: {.cell-output-display}\n![Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95.](eda_files/figure-ipynb/fig-interactions-no-group-1.png){#fig-interactions-no-group}\n:::\n:::\n\n\n\n::: {#cell-fig-interactions-no-group-with-significance .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-no-group-with-significance\n#| fig-cap: \"Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95. Brackets show pairwise timepoint contrasts (mixed model: Mean ~ Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 10\n\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(lme4)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: Matrix\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'Matrix'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:tidyr':\n\n    expand, pack, unpack\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-no-group-with-significance\n#| fig-cap: \"Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95. Brackets show pairwise timepoint contrasts (mixed model: Mean ~ Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 10\n\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-no-group-with-significance\n#| fig-cap: \"Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95. Brackets show pairwise timepoint contrasts (mixed model: Mean ~ Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 10\n\nlibrary(ggsignif)\n\np_to_star <- function(p){\n  ifelse(is.na(p), \"NA\",\n  ifelse(p < 0.001, \"***\",\n  ifelse(p < 0.01,  \"**\",\n  ifelse(p < 0.05,  \"*\", \"ns\"))))\n}\n\nmake_nogroup_plot <- function(df_wide, title,\n                              ylab = \"Mean methylation (mean across CpGs)\") {\n\n  df_long <- df_wide %>%\n    pivot_longer(cols = c(T0, T1, T2),\n                 names_to = \"Zeitpunkt\",\n                 values_to = \"Mean\") %>%\n    mutate(\n      Zeitpunkt = factor(Zeitpunkt, levels = c(\"T0\",\"T1\",\"T2\")),\n      ID = factor(ID)\n    ) %>%\n    filter(!is.na(Mean))\n\n  # summary stats (SE)\n  sum0 <- df_long %>%\n    group_by(Zeitpunkt) %>%\n    summarise(\n      n = n(),\n      mean = mean(Mean),\n      se   = sd(Mean) / sqrt(n),\n      .groups = \"drop\"\n    )\n\n  # mixed model for timepoint differences (within-subject)\n  fit <- lmer(Mean ~ Zeitpunkt + (1 | ID), data = df_long, REML = TRUE)\n\n  # pairwise contrasts between timepoints\n  pw <- as.data.frame(pairs(emmeans(fit, ~ Zeitpunkt))) %>%\n    transmute(\n      contrast,\n      p.value,\n      label = p_to_star(p.value)\n    ) %>%\n    separate(contrast, into = c(\"x1\", \"x2\"), sep = \" - \")\n\n  # bracket y-positions (stacked)\n  y_top  <- max(sum0$mean + sum0$se, na.rm = TRUE)\n  y_step <- 0.08 * diff(range(sum0$mean, na.rm = TRUE))\n  if (!is.finite(y_step) || y_step == 0) y_step <- 0.01\n\n  pw <- pw %>%\n    mutate(y_position = y_top + y_step * row_number())\n\n  ggplot(sum0, aes(x = Zeitpunkt, y = mean, group = 1)) +\n    geom_line() +\n    geom_point() +\n    geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +\n    ggsignif::geom_signif(\n      data = pw,\n      aes(xmin = x1, xmax = x2, annotations = label, y_position = y_position),\n      manual = TRUE,\n      inherit.aes = FALSE,\n      textsize = 4,\n      tip_length = 0.01\n    ) +\n    theme_classic() +\n    labs(\n      title = title,\n      x = \"Time Point\",\n      y = ylab,\n      caption = \"Error bars are ±SE. Brackets: pairwise timepoint contrasts from mixed model.\"\n    )\n}\n\np_bdnf0  <- make_nogroup_plot(bdnf_mean_wide,  title = \"BDNF\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in ggsignif::geom_signif(data = pw, aes(xmin = x1, xmax = x2,\nannotations = label, : Ignoring unknown aesthetics: xmin, xmax, annotations,\nand y_position\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-no-group-with-significance\n#| fig-cap: \"Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95. Brackets show pairwise timepoint contrasts (mixed model: Mean ~ Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 10\n\np_tau0   <- make_nogroup_plot(tau_mean_wide,   title = \"Tau\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in ggsignif::geom_signif(data = pw, aes(xmin = x1, xmax = x2,\nannotations = label, : Ignoring unknown aesthetics: xmin, xmax, annotations,\nand y_position\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-no-group-with-significance\n#| fig-cap: \"Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95. Brackets show pairwise timepoint contrasts (mixed model: Mean ~ Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 10\n\np_psd950 <- make_nogroup_plot(psd95_mean_wide, title = \"PSD95\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in ggsignif::geom_signif(data = pw, aes(xmin = x1, xmax = x2,\nannotations = label, : Ignoring unknown aesthetics: xmin, xmax, annotations,\nand y_position\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-no-group-with-significance\n#| fig-cap: \"Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95. Brackets show pairwise timepoint contrasts (mixed model: Mean ~ Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 10\n\n(p_bdnf0 / p_tau0 / p_psd950)\n```\n\n::: {.cell-output-display}\n![Methylation levels (mean ± SE) across time points collapsed across groups for BDNF, Tau, and PSD95. Brackets show pairwise timepoint contrasts (mixed model: Mean ~ Zeitpunkt + (1|ID)).](eda_files/figure-ipynb/fig-interactions-no-group-with-significance-1.png){#fig-interactions-no-group-with-significance}\n:::\n:::\n\n\n\n### Interaction Plots by Gene (mean across CpGs)\n\n::: {#cell-fig-interactions-by-gene-mean .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-by-gene-mean\n#| fig-cap: \"Methylation levels (mean ± SE) across time points by group for BDNF, Tau, and PSD95.\"\n#| fig-width: 8\n#| fig-height: 12\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(patchwork)\n\nmake_interaction_plot <- function(df_wide, title, ylab = \"Mean methylation (mean across CpGs)\") {\n\n  df_long <- df_wide %>%\n    pivot_longer(cols = c(T0, T1, T2),\n                 names_to = \"Zeitpunkt\",\n                 values_to = \"Mean\") %>%\n    mutate(\n      Zeitpunkt = factor(Zeitpunkt, levels = c(\"T0\", \"T1\", \"T2\")),\n      Gruppe = factor(Gruppe)\n    )\n\n  summary_stats <- df_long %>%\n    group_by(Zeitpunkt, Gruppe) %>%\n    summarise(\n      n = sum(!is.na(Mean)),\n      mean = mean(Mean, na.rm = TRUE),\n      se = sd(Mean, na.rm = TRUE) / sqrt(n),\n      .groups = \"drop\"\n    )\n\n  ggplot(summary_stats, aes(x = Zeitpunkt, y = mean, group = Gruppe, colour = Gruppe)) +\n    geom_line() +\n    geom_point() +\n    geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +\n    theme_classic() +\n    labs(title = title, x = \"Time Point\", y = ylab, caption = \"Points show mean across participants; error bars are ±SE.\")\n}\n\n# BDNF\np_bdnf <-\nmake_interaction_plot(\n  bdnf_mean_wide,\n  title = \"Interaction Plot of BDNF Methylation Levels by Group and Time\"\n)\n\n# TAU\np_tau <-\nmake_interaction_plot(\n  tau_mean_wide,\n  title = \"Interaction Plot of Tau Methylation Levels by Group and Time\"\n)\n\n# PSD95\np_psd95 <-\nmake_interaction_plot(\n  psd95_mean_wide,\n  title = \"Interaction Plot of PSD95 Methylation Levels by Group and Time\"\n)\n\n\n(p_bdnf / p_tau / p_psd95) + plot_layout(guides = \"collect\") &\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![Methylation levels (mean ± SE) across time points by group for BDNF, Tau, and PSD95.](eda_files/figure-ipynb/fig-interactions-by-gene-mean-1.png){#fig-interactions-by-gene-mean}\n:::\n:::\n\n\n### Interaction Plots by Gene (mean across CpGs) with significance stars\n\n\n::: {#cell-fig-interactions-by-gene-mean-with-significance .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-by-gene-mean-with-significance\n#| fig-cap: \"Methylation levels (mean ± 95% CI) across time points by group for BDNF, Tau, and PSD95. Stars indicate Piano vs Control contrasts within each time point from a mixed model (Mean ~ Gruppe * Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 12\n\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(lme4)\nlibrary(emmeans)\n\np_to_star <- function(p){\n  ifelse(is.na(p), \"NA\",\n  ifelse(p < 0.001, \"***\",\n  ifelse(p < 0.01,  \"**\",\n  ifelse(p < 0.05,  \"*\", \"ns\"))))\n}\n\nmake_interaction_plot_sig <- function(df_wide, title,\n                                      ylab = \"Mean methylation (mean across CpGs)\",\n                                      control_label = \"Controll\",\n                                      piano_label = \"Piano\") {\n\n  # wide -> long\n  df_long <- df_wide %>%\n    pivot_longer(cols = c(T0, T1, T2),\n                 names_to = \"Zeitpunkt\",\n                 values_to = \"Mean\") %>%\n    mutate(\n      Zeitpunkt = factor(Zeitpunkt, levels = c(\"T0\", \"T1\", \"T2\")),\n      Gruppe = factor(Gruppe, levels = c(control_label, piano_label)),\n      ID = factor(ID)\n    ) %>%\n    filter(!is.na(Mean))\n\n  # mixed model (participant-level)\n  fit <- lmer(Mean ~ Gruppe * Zeitpunkt + (1 | ID), data = df_long, REML = TRUE)\n\n  # Piano vs Control at each timepoint\n  emm <- emmeans(fit, ~ Gruppe | Zeitpunkt)\n  contr <- as.data.frame(contrast(emm, method = list(\"Piano - Control\" = c(-1, 1))))\n\n  pvals <- contr %>%\n    transmute(\n      Zeitpunkt,\n      p.value,\n      label = p_to_star(p.value)\n    )\n\n  # summary stats for plot (95% CI)\n  summary_stats <- df_long %>%\n    group_by(Zeitpunkt, Gruppe) %>%\n    summarise(\n      n = n(),\n      mean = mean(Mean),\n      sd = sd(Mean),\n      se = sd / sqrt(n),\n      ci = qt(0.975, df = n - 1) * se,\n      .groups = \"drop\"\n    )\n\n  # y-positions for labels (above the top CI per timepoint)\n  y_pad <- 0.06 * diff(range(summary_stats$mean, na.rm = TRUE))\n  ann <- summary_stats %>%\n    group_by(Zeitpunkt) %>%\n    summarise(y = max(mean + ci, na.rm = TRUE) + y_pad, .groups = \"drop\") %>%\n    left_join(pvals, by = \"Zeitpunkt\")\n\n  ggplot(summary_stats, aes(x = Zeitpunkt, y = mean, group = Gruppe, colour = Gruppe)) +\n    geom_line() +\n    geom_point() +\n    geom_errorbar(aes(ymin = mean - ci, ymax = mean + ci), width = 0.2) +\n    geom_text(data = ann, aes(x = Zeitpunkt, y = y, label = label),\n              inherit.aes = FALSE, vjust = 0, size = 4) +\n    theme_classic() +\n    labs(\n      title = title,\n      x = \"Time Point\",\n      y = ylab,\n      caption = \"Error bars are 95% CI. Stars: Piano vs Control within timepoint from mixed model.\"\n    )\n}\n\n# BDNF\np_bdnf <- make_interaction_plot_sig(\n  bdnf_mean_wide,\n  title = \"Interaction Plot of BDNF Methylation Levels by Group and Time\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-by-gene-mean-with-significance\n#| fig-cap: \"Methylation levels (mean ± 95% CI) across time points by group for BDNF, Tau, and PSD95. Stars indicate Piano vs Control contrasts within each time point from a mixed model (Mean ~ Gruppe * Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 12\n\n# TAU\np_tau <- make_interaction_plot_sig(\n  tau_mean_wide,\n  title = \"Interaction Plot of Tau Methylation Levels by Group and Time\"\n)\n\n# PSD95\np_psd95 <- make_interaction_plot_sig(\n  psd95_mean_wide,\n  title = \"Interaction Plot of PSD95 Methylation Levels by Group and Time\"\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: fig-interactions-by-gene-mean-with-significance\n#| fig-cap: \"Methylation levels (mean ± 95% CI) across time points by group for BDNF, Tau, and PSD95. Stars indicate Piano vs Control contrasts within each time point from a mixed model (Mean ~ Gruppe * Zeitpunkt + (1|ID)).\"\n#| fig-width: 8\n#| fig-height: 12\n\n(p_bdnf / p_tau / p_psd95) + plot_layout(guides = \"collect\") &\n  theme(legend.position = \"right\")\n```\n\n::: {.cell-output-display}\n![Methylation levels (mean ± 95% CI) across time points by group for BDNF, Tau, and PSD95. Stars indicate Piano vs Control contrasts within each time point from a mixed model (Mean ~ Gruppe * Zeitpunkt + (1|ID)).](eda_files/figure-ipynb/fig-interactions-by-gene-mean-with-significance-1.png){#fig-interactions-by-gene-mean-with-significance}\n:::\n:::\n\n\n## Explanation of Methylation Summary Statistics\nChatGPT-help (cf. plots-time-methylation.qmd)\n\nTotally fair to ask again — this is the key conceptual trap in methylation papers, and you’re right at the edge of it. I’ll explain it slowly and cleanly, with your exact data in mind.\n\nThe core issue in one sentence\n\nA CpG is not a participant.\nIf you treat CpGs like independent observations, you inflate N and distort SD/SE.\n\nEverything else follows from that.\n\nWhat your data actually look like\n1️⃣ CpG-level data (long format: BDNF2, TAU2, …)\n\nEach row is:\n\none CpG site × one person × one time point\n\nExample (simplified):\n\nID\tTime\tCpG\tmethylation\n1\tT0\tm148\t0.18\n1\tT0\tm111\t0.23\n1\tT0\tm087\t0.00\n…\t…\t…\t…\n\nSo for one person at one time, you might have 20–30 CpGs.\n\nWhen you do:\n\nmean(BDNF2$methylierung)\nsd(BDNF2$methylierung)\n\n\nyou are computing:\n\n“What is the mean/SD of all CpG measurements pooled together?”\n\nThis mixes three different sources of variation:\n\nDifferences between CpG sites (huge!)\n\nDifferences between people\n\nChanges over time + noise\n\nThat’s why:\n\nSD is large (~0.09–0.10)\n\nSE becomes artificially tiny if you divide by sqrt(nrow(BDNF2))\n\nPlots look “too confident”\n\nThis is not wrong mathematically, but it answers the wrong scientific question.\n\nWhat your paper actually claims to measure\n\nYour tables, text, and mixed models all say things like:\n\n“BDNF methylation level per gene”\n\nThat implies:\n\none methylation value per person per time point\n\nSo you must collapse CpGs first.\n\n2️⃣ Sample-level data (wide format: bdnf_mean_wide, tau_mean_wide)\n\nHere each row is:\n\none person, with CpGs already averaged\n\nExample:\n\nID\tGroup\tT0\tT1\tT2\n1\tControl\t0.075\t0.037\tNA\n2\tPiano\t0.102\t0.060\t0.084\n\nEach value (e.g. 0.075) is:\n\nmean methylation across all CpGs for that person at that time\n\nNow when you compute:\n\nmean(bdnf_mean_wide$T0, na.rm=TRUE)\nsd(bdnf_mean_wide$T0, na.rm=TRUE)\n\n\nyou are asking:\n\n“How much do people differ in their average BDNF methylation at T0?”\n\nThis is exactly what readers expect.\n\nThat’s why:\n\nSD ≈ 0.03–0.04\n\nSE ≈ SD / √N_participants\n\nPlots look sensible\n\nResults match your LMM interpretation\n\nWhy your interaction plots broke\n\nYou originally did this (conceptually):\n\ngroup_by(Time, Group) %>%\nsummarise(\n  mean = mean(methylation),\n  se = sd(methylation) / sqrt(n())\n)\n\n\nBut here:\n\nmethylation = CpG-level values\n\nn() = number of CpGs × people × time\n\nSo SE was:\n\nSD across CpGs ÷ √(CpGs × people)\n\nThat is not the SE of the group mean across people.\n\nThat’s why BDNF “kind of looked OK” (by coincidence) and TAU didn’t.\n\nThe correct mental model (memorize this)\nQuestion\tUnit of analysis\tData to use\n“What is average gene methylation per person?”\tPerson\tCpGs averaged first\n“Do groups differ in gene methylation?”\tPerson\tSample-level mean\n“Does methylation change over time?”\tPerson\tSample-level mean\n“Do CpGs behave differently?”\tCpG\tCpG-level model\n\nNever mix these levels.\n\nWhy your mixed model was actually OK\n\nYour LMM used CpG-level rows, but:\n\nyou used random intercepts for person\n\nyou interpreted fixed effects at the gene level\n\nThat’s defensible if and only if:\n\nyou don’t treat CpGs as independent in descriptives\n\nyou explain that CpGs are repeated measures within person\n\nYour tables/plots must still reflect person-level summaries.\n\nOne sentence you can put in Methods (this resolves everything)\n\n“For descriptive statistics and visualization, methylation values were averaged across all available CpG sites per gene for each participant and time point.”\n\nThat sentence legally aligns:\n\nyour tables\n\nyour plots\n\nyour interpretation\n\nyour reviewer sanity\n\nFinal rule of thumb (print this mentally)\n\nCpGs are repeated measures, not observations.\nPeople are observations.\n\nIf you want, next we can:\n\nre-express the LMM more cleanly (random slope for time, CpG as random effect)\n\ndecide whether to keep CpG-level modeling or simplify to sample-level LMM\n\nJust tell me which way you want to go.\n\ndo this in markdown so i can add it to script\n\n\n\n### Boxplots of mean values\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nboxplot(\n  list(\n    BDNF  = bdnf_mean$Mean,\n    Tau   = tau_mean$Mean,\n    PSD95 = psd95_mean$Mean\n  ),\n  xlab = \"Marker\",\n  ylab = \"Mean\",\n  main = \"Boxplots of Mean Values\"\n)\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/unnamed-chunk-3-1.png)\n:::\n\n```{.r .cell-code .hidden}\nlibrary(ggplot2)\n\ndf <- rbind(\n  data.frame(Marker = \"BDNF\",  Mean = bdnf_mean$Mean),\n  data.frame(Marker = \"Tau\",   Mean = tau_mean$Mean),\n  data.frame(Marker = \"PSD95\", Mean = psd95_mean$Mean)\n)\n\nggplot(df, aes(x = Marker, y = Mean)) +\n  geom_boxplot() +\n  labs(x = \"Marker\", y = \"Mean\", title = \"Boxplots of Mean Values\") +\n  theme_classic()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 12 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/unnamed-chunk-3-2.png)\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\n\ndf <- bind_rows(\n  bdnf_mean  %>% mutate(Gene = \"BDNF\"),\n  tau_mean   %>% mutate(Gene = \"Tau\"),\n  psd95_mean %>% mutate(Gene = \"PSD95\")\n) %>%\n  mutate(\n    Gruppe = as.character(Gruppe),\n    value  = Mean          # rename raw values to avoid name collision\n  )\n\ntab <- df %>%\n  group_by(Gene, Gruppe) %>%\n  summarise(\n    N = sum(is.finite(value)),\n    Mean = mean(value, na.rm = TRUE),\n    SD   = sd(value, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  mutate(`Mean ± SD` = sprintf(\"%.3f ± %.3f\", Mean, SD)) %>%\n  select(Gene, Gruppe, N, `Mean ± SD`) %>%\n  arrange(Gene, Gruppe)\n\n# Markdown print (no NULL)\ncat(\"| Gene | Group | N | Mean ± SD |\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n| Gene | Group | N | Mean ± SD |\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ncat(\"|------|-------|---:|-----------|\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n|------|-------|---:|-----------|\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nfor (i in seq_len(nrow(tab))) {\n  cat(sprintf(\"| %s | %s | %d | %s |\\n\",\n              tab$Gene[i], tab$Gruppe[i], tab$N[i], tab$`Mean ± SD`[i]))\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n| BDNF | Controll | 183 | 0.073 ± 0.034 |\n| BDNF | Piano | 176 | 0.066 ± 0.033 |\n| PSD95 | Controll | 179 | 0.031 ± 0.014 |\n| PSD95 | Piano | 178 | 0.030 ± 0.013 |\n| Tau | Controll | 182 | 0.075 ± 0.020 |\n| Tau | Piano | 180 | 0.075 ± 0.020 |\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# combine into one long data.frame\ndf <- rbind(\n  data.frame(Gene=\"BDNF\",  Group=bdnf_mean$Gruppe,  value=bdnf_mean$Mean),\n  data.frame(Gene=\"Tau\",   Group=tau_mean$Gruppe,   value=tau_mean$Mean),\n  data.frame(Gene=\"PSD95\", Group=psd95_mean$Gruppe, value=psd95_mean$Mean)\n)\n\n# keep only finite values\ndf <- df[is.finite(df$value), ]\ndf$Gene  <- factor(df$Gene,  levels = c(\"BDNF\",\"Tau\",\"PSD95\"))\ndf$Group <- factor(df$Group)   # e.g., Piano / Controll\n\n# one figure: x = Gene with 2 boxes per gene (split by group), one y-axis\nboxplot(\n  value ~ Gene + Group,\n  data = df,\n  xlab = \"Gene\",\n  ylab = \"Mean\",\n  main = \"Gene values by group\",\n  las = 2\n)\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/unnamed-chunk-5-1.png)\n:::\n\n```{.r .cell-code .hidden}\nboxplot(value ~ Gene + Group, data=df,\n        col=rep(1:length(levels(df$Group)), times=length(levels(df$Gene))),\n        xlab=\"Gene\", ylab=\"Mean\", main=\"Gene values by group\", las=2)\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/unnamed-chunk-5-2.png)\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\nlibrary(ggplot2)\n\ndf <- bind_rows(\n  bdnf_mean  %>% mutate(Gene = \"BDNF\"),\n  tau_mean   %>% mutate(Gene = \"Tau\"),\n  psd95_mean %>% mutate(Gene = \"PSD95\")\n) %>%\n  mutate(\n    Gruppe = as.character(Gruppe),\n    value  = Mean\n  ) %>%\n  filter(is.finite(value))\n\nggplot(df, aes(x = Gene, y = value, fill = Gruppe)) +\n  geom_boxplot(position = position_dodge(width = 0.8), outlier.shape = NA) +\n  geom_jitter(aes(color = Gruppe),\n              position = position_jitterdodge(jitter.width = 0.15, dodge.width = 0.8),\n              alpha = 0.4, size = 1.2) +\n  labs(x = \"Gene\", y = \"Mean\", title = \"Gene values by group\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/unnamed-chunk-6-1.png)\n:::\n:::\n\n\n### Time mean values\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmean(bdnf_mean_wide$T0, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06991766\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(bdnf_mean_wide$T0, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03312811\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmean(bdnf_mean_wide$T1, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.06213866\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(bdnf_mean_wide$T1, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02926242\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmean(bdnf_mean_wide$T2, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07886025\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(bdnf_mean_wide$T2, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0373159\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmean(tau_mean_wide$T0, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07346318\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(tau_mean_wide$T0, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0195717\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmean(tau_mean_wide$T1, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0763202\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(tau_mean_wide$T1, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02039475\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmean(tau_mean_wide$T2, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07604121\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(tau_mean_wide$T2, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01928458\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmean(psd95_mean_wide$T0, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0297867\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(psd95_mean_wide$T0, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01571922\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmean(psd95_mean_wide$T1, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03197377\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(psd95_mean_wide$T1, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01321249\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmean(psd95_mean_wide$T2, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03078094\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsd(psd95_mean_wide$T2, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.01030583\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsummary_table <- data.frame(\n  Marker = rep(c(\"BDNF\", \"Tau\", \"PSD95\"), each = 3),\n  Time = rep(c(\"T0\", \"T1\", \"T2\"), times = 3),\n  Mean = c(\n    mean(bdnf_mean_wide$T0, na.rm = TRUE),\n    mean(bdnf_mean_wide$T1, na.rm = TRUE),\n    mean(bdnf_mean_wide$T2, na.rm = TRUE),\n\n    mean(tau_mean_wide$T0, na.rm = TRUE),\n    mean(tau_mean_wide$T1, na.rm = TRUE),\n    mean(tau_mean_wide$T2, na.rm = TRUE),\n\n    mean(psd95_mean_wide$T0, na.rm = TRUE),\n    mean(psd95_mean_wide$T1, na.rm = TRUE),\n    mean(psd95_mean_wide$T2, na.rm = TRUE)\n  ),\n  SD = c(\n    sd(bdnf_mean_wide$T0, na.rm = TRUE),\n    sd(bdnf_mean_wide$T1, na.rm = TRUE),\n    sd(bdnf_mean_wide$T2, na.rm = TRUE),\n\n    sd(tau_mean_wide$T0, na.rm = TRUE),\n    sd(tau_mean_wide$T1, na.rm = TRUE),\n    sd(tau_mean_wide$T2, na.rm = TRUE),\n\n    sd(psd95_mean_wide$T0, na.rm = TRUE),\n    sd(psd95_mean_wide$T1, na.rm = TRUE),\n    sd(psd95_mean_wide$T2, na.rm = TRUE)\n  )\n)\n\nsummary_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Marker Time       Mean         SD\n1   BDNF   T0 0.06991766 0.03312811\n2   BDNF   T1 0.06213866 0.02926242\n3   BDNF   T2 0.07886025 0.03731590\n4    Tau   T0 0.07346318 0.01957170\n5    Tau   T1 0.07632020 0.02039475\n6    Tau   T2 0.07604121 0.01928458\n7  PSD95   T0 0.02978670 0.01571922\n8  PSD95   T1 0.03197377 0.01321249\n9  PSD95   T2 0.03078094 0.01030583\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nsummary_table$`Mean ± SD` <- sprintf(\"%.3f ± %.3f\",\n                                     summary_table$Mean,\n                                     summary_table$SD)\nsummary_table_final <- summary_table[, c(\"Marker\", \"Time\", \"Mean ± SD\")]\nsummary_table_final\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Marker Time     Mean ± SD\n1   BDNF   T0 0.070 ± 0.033\n2   BDNF   T1 0.062 ± 0.029\n3   BDNF   T2 0.079 ± 0.037\n4    Tau   T0 0.073 ± 0.020\n5    Tau   T1 0.076 ± 0.020\n6    Tau   T2 0.076 ± 0.019\n7  PSD95   T0 0.030 ± 0.016\n8  PSD95   T1 0.032 ± 0.013\n9  PSD95   T2 0.031 ± 0.010\n```\n\n\n:::\n:::\n\n\n## Group Differences in Mean Values\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: group-differences\nlibrary(psych)\nlibrary(DescTools)\n\n# Calculate the mode for each dataset\nMode(bdnf_mean$Mean, na.rm = TRUE) # Bimodal: two modes at 0 and 0.063\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.051 0.063\nattr(,\"freq\")\n[1] 9\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\nMode(tau_mean$Mean, na.rm = TRUE) # Mode at 0.066875\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.066875\nattr(,\"freq\")\n[1] 7\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\nMode(psd95_mean$Mean, na.rm = TRUE) # Bimodal: two modes at 0.02377778 and 0.03177778\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02555556 0.03266667 0.03466667 0.03866667\nattr(,\"freq\")\n[1] 4\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\nMode(bdnf_median$Median, na.rm = TRUE) # Mode at 0 (92 occurrences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\nattr(,\"freq\")\n[1] 92\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\nMode(tau_median$Median, na.rm = TRUE) # Mode at 0.02 (65 occurrences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02\nattr(,\"freq\")\n[1] 65\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\nMode(psd95_median$Median, na.rm = TRUE) # Mode at 0 (317 occurrences)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\nattr(,\"freq\")\n[1] 317\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\n# Summarize data by group\ntapply(bdnf_mean$Mean, bdnf_mean$Gruppe, summary, na.rm = TRUE) # Minimal difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.04800 0.07000 0.07326 0.09500 0.16900       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.04600 0.06400 0.06598 0.08825 0.18600       4 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\ntapply(bdnf_median$Median, bdnf_median$Gruppe, summary, na.rm = TRUE) # Minimal difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n 0.0000  0.0025  0.0350  0.0397  0.0600  0.2050       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n 0.0000  0.0000  0.0250  0.0344  0.0500  0.2100       4 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\ntapply(tau_mean$Mean, tau_mean$Gruppe, summary, na.rm = TRUE) # No difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.02813 0.06294 0.07269 0.07515 0.08583 0.14574       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.01250 0.06270 0.07323 0.07510 0.08625 0.16708       1 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\ntapply(tau_median$Median, tau_median$Gruppe, summary, na.rm = TRUE) # No difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.01000 0.02000 0.02011 0.03000 0.12000       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.01000 0.02000 0.01906 0.03000 0.06500       1 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\ntapply(psd95_mean$Mean, psd95_mean$Gruppe, summary, na.rm = TRUE) # No difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.02316 0.03054 0.03131 0.03832 0.13062       3 \n\n$Piano\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.007083 0.021574 0.028556 0.030295 0.036550 0.080000        2 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: group-differences\ntapply(psd95_median$Median, psd95_median$Gruppe, summary, na.rm = TRUE) # No difference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.000000 0.000000 0.000000 0.003101 0.000000 0.060000        3 \n\n$Piano\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.000000 0.000000 0.000000 0.001601 0.000000 0.050000        2 \n```\n\n\n:::\n:::\n\n\n-   Bei BDNF zeigt sich eine leichte Differenz zwischen der Kontrollgruppe (Median: 0.07, Mean: 0.07326) und der Pianogruppe (Median: 0.064, Mean: 0.06598), welche eine niedrigere Metyhlierung (Median: -0.006, Mean: -0.00728) aufwies.\n-   Weiterhin zeigen sich für die arithmetischen Mittel von BDNF und PSD95 zwei Modi.\n-   Tau war unimodal.\n\n### Boxplots\n\n\n::: {#cell-fig-boxplots-genes .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-boxplots-genes\n#| fig-cap: \"Boxplots of gene expression means by time point and gene.\"\n#| fig-width: 9\n\nlibrary(dplyr)\nlibrary(ggplot2)\n\nall_long <- bind_rows(\n  bdnf_mean  %>% mutate(Gene = \"BDNF\"),\n  tau_mean   %>% mutate(Gene = \"TAU\"),\n  psd95_mean %>% mutate(Gene = \"PSD95\")\n) %>%\n  mutate(\n    Zeitpunkt = factor(Zeitpunkt, levels = c(\"T0\",\"T1\",\"T2\")),\n    Gene = factor(Gene, levels = c(\"BDNF\",\"TAU\",\"PSD95\")),\n    GeneTime = factor(\n      paste(Gene, Zeitpunkt, sep = \"_\"),\n      levels = c(\"BDNF_T0\",\"BDNF_T1\",\"BDNF_T2\",\n                 \"TAU_T0\",\"TAU_T1\",\"TAU_T2\",\n                 \"PSD95_T0\",\"PSD95_T1\",\"PSD95_T2\")\n    )\n  )\n\nx <- library(dplyr)\nlibrary(ggplot2)\n\nall_long <- bind_rows(\n  bdnf_mean  %>% mutate(Gene = \"BDNF\"),\n  tau_mean   %>% mutate(Gene = \"TAU\"),\n  psd95_mean %>% mutate(Gene = \"PSD95\")\n) %>%\n  mutate(\n    Zeitpunkt = factor(Zeitpunkt, levels = c(\"T0\",\"T1\",\"T2\")),\n    Gene = factor(Gene, levels = c(\"BDNF\",\"TAU\",\"PSD95\")),\n    GeneTime = factor(\n      paste(Gene, Zeitpunkt, sep = \"_\"),\n      levels = c(\"BDNF_T0\",\"BDNF_T1\",\"BDNF_T2\",\n                 \"TAU_T0\",\"TAU_T1\",\"TAU_T2\",\n                 \"PSD95_T0\",\"PSD95_T1\",\"PSD95_T2\")\n    )\n  )\n\nx <- ggplot(all_long, aes(x = GeneTime, y = Mean, fill = Gene)) +\n  geom_boxplot(na.rm = TRUE, outlier.alpha = 0.6) +\n  geom_vline(xintercept = c(3.5, 6.5), linetype = 2) +\n  scale_x_discrete(labels = rep(c(\"T0\",\"T1\",\"T2\"), 3)) +\n  labs(title = \"Mean gene expression by time point\", x = \"Time (grouped by gene)\", y = \"Mean\", fill = \"Gene\") +\n  theme_bw() +\n  theme(\n    axis.text.x = element_text(size = 10),\n    plot.title = element_text(face = \"bold\")\n  )\n\nx\n```\n\n::: {.cell-output-display}\n![Boxplots of gene expression means by time point and gene.](eda_files/figure-ipynb/fig-boxplots-genes-1.png){#fig-boxplots-genes}\n:::\n:::\n\n\n\n## Time Differences in Mean Values\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: time-differences\n# Methylierung: PSD95 < Tau < BDNF\n\ntapply(bdnf_mean$Mean, bdnf_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 > T1 < T2 (T0 < T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.06991766 0.06213866 0.07886025 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: time-differences\ntapply(bdnf_median$Median, bdnf_median$Zeitpunkt, median, na.rm = TRUE) # T0 > T1 < T2 (T0 < T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   T0    T1    T2 \n0.030 0.025 0.040 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: time-differences\ntapply(tau_mean$Mean, tau_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 < T1 = T2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.07346318 0.07632020 0.07604121 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: time-differences\ntapply(tau_median$Median, tau_median$Zeitpunkt, median, na.rm = TRUE) # T0 = T1 > T2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   T0    T1    T2 \n0.020 0.020 0.015 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: time-differences\n# überhaupt keine Differenz\ntapply(psd95_mean$Mean, psd95_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 < T1 > T2 (T0 = T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.02978670 0.03197377 0.03078094 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: time-differences\ntapply(psd95_median$Median, psd95_median$Zeitpunkt, median, na.rm = TRUE) # all = 0 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT0 T1 T2 \n 0  0  0 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: time-differences\n# noch geringer als Tau und BDNF methyliert\n```\n:::\n\n\n-   Die Gene sind allgemein eher gering methyliert (Mean \\< 0,08, Median \\< 0,04).\n-   Dabei ist PSD95 am geringsten und BDNF am höchsten metyhyliert.\n-   Bei BDNF zeigt sich, dass sich die Mittelwerte (Arithmetisch und Median) von T0 zu T1 leicht absenken und zu T2 wieder über das Niveau von T0 ansteigen.\n-   Bei Tau steigt das arithmetische Mittel der Methylierung leicht von T0 zu T1 und hält das Niveau bei T2.\n-   Bei PSD95 verbleibt der Median der Methylierun gleichbleibend bei 0, während das arithmetische Mittel der Methylierung von T0 zu T1 steigt aber bei T2 wieder auf das Ausgangsniveau zurückfällt.\n\n## Important Point and Interval Estimators\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: descriptives-wide\n\n# Describe the wide format datasets\n## BDNF\ndescribe(bdnf_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad  min    max  range  skew\nID           1 144 108.17 62.41 121.50  109.68 80.80  1.0 202.00 201.00 -0.23\nStandort     2 144   0.62  0.49   1.00    0.66  0.00  0.0   1.00   1.00 -0.51\nGruppe*      3 144   1.47  0.50   1.00    1.46  0.00  1.0   2.00   1.00  0.14\nSex*         4 144   1.42  0.50   1.00    1.41  0.00  1.0   2.00   1.00  0.31\nAge_start    5 144  69.58  3.51  69.00   69.37  2.97 62.0  78.00  16.00  0.55\nCogTel       6 144  31.77  7.23  32.15   31.76  8.52 15.5  49.20  33.70  0.00\nT0           7 140   0.07  0.03   0.06    0.07  0.04  0.0   0.17   0.17  0.29\nT1           8 122   0.06  0.03   0.06    0.06  0.03  0.0   0.16   0.16  0.06\nT2           9  97   0.08  0.04   0.08    0.08  0.03  0.0   0.19   0.19  0.27\n          kurtosis   se\nID           -1.36 5.20\nStandort     -1.75 0.04\nGruppe*      -1.99 0.04\nSex*         -1.92 0.04\nAge_start    -0.47 0.29\nCogTel       -0.77 0.60\nT0           -0.30 0.00\nT1            0.18 0.00\nT2            0.18 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: descriptives-wide\n\ndescribe(bdnf_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad  min    max  range  skew\nID           1 144 108.17 62.41 121.50  109.68 80.80  1.0 202.00 201.00 -0.23\nStandort     2 144   0.62  0.49   1.00    0.66  0.00  0.0   1.00   1.00 -0.51\nGruppe*      3 144   1.47  0.50   1.00    1.46  0.00  1.0   2.00   1.00  0.14\nSex*         4 144   1.42  0.50   1.00    1.41  0.00  1.0   2.00   1.00  0.31\nAge_start    5 144  69.58  3.51  69.00   69.37  2.97 62.0  78.00  16.00  0.55\nCogTel       6 144  31.77  7.23  32.15   31.76  8.52 15.5  49.20  33.70  0.00\nT0           7 140   0.04  0.04   0.03    0.03  0.04  0.0   0.18   0.18  1.14\nT1           8 122   0.03  0.03   0.03    0.03  0.04  0.0   0.12   0.12  0.86\nT2           9  97   0.05  0.04   0.04    0.04  0.04  0.0   0.21   0.21  1.52\n          kurtosis   se\nID           -1.36 5.20\nStandort     -1.75 0.04\nGruppe*      -1.99 0.04\nSex*         -1.92 0.04\nAge_start    -0.47 0.29\nCogTel       -0.77 0.60\nT0            0.78 0.00\nT1           -0.04 0.00\nT2            2.71 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: descriptives-wide\n\n## Tau\ndescribe(tau_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad   min    max  range  skew\nID           1 145 108.39 62.25 122.00  109.95 80.06  1.00 202.00 201.00 -0.24\nStandort     2 145   1.63  0.49   2.00    1.66  0.00  1.00   2.00   1.00 -0.52\nGruppe*      3 145   1.47  0.50   1.00    1.46  0.00  1.00   2.00   1.00  0.12\nSex*         4 145   1.43  0.50   1.00    1.41  0.00  1.00   2.00   1.00  0.29\nAge_start    5 145  69.57  3.50  69.00   69.36  2.97 62.00  78.00  16.00  0.56\nCogTel       6 145  31.77  7.20  32.40   31.77  8.60 15.50  49.20  33.70 -0.01\nT0           7 142   0.07  0.02   0.07    0.07  0.02  0.03   0.17   0.14  0.79\nT1           8 123   0.08  0.02   0.07    0.07  0.02  0.01   0.15   0.13  0.60\nT2           9  97   0.08  0.02   0.07    0.08  0.02  0.03   0.13   0.10  0.37\n          kurtosis   se\nID           -1.35 5.17\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel       -0.75 0.60\nT0            2.54 0.00\nT1            1.01 0.00\nT2            0.10 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: descriptives-wide\n\ndescribe(tau_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad  min    max  range  skew\nID           1 145 108.39 62.25 122.00  109.95 80.06  1.0 202.00 201.00 -0.24\nStandort     2 145   1.63  0.49   2.00    1.66  0.00  1.0   2.00   1.00 -0.52\nGruppe*      3 145   1.47  0.50   1.00    1.46  0.00  1.0   2.00   1.00  0.12\nSex*         4 145   1.43  0.50   1.00    1.41  0.00  1.0   2.00   1.00  0.29\nAge_start    5 145  69.57  3.50  69.00   69.36  2.97 62.0  78.00  16.00  0.56\nCogTel       6 145  31.77  7.20  32.40   31.77  8.60 15.5  49.20  33.70 -0.01\nT0           7 142   0.02  0.01   0.02    0.02  0.01  0.0   0.05   0.05  0.19\nT1           8 123   0.02  0.02   0.02    0.02  0.01  0.0   0.12   0.12  1.93\nT2           9  97   0.02  0.01   0.01    0.02  0.01  0.0   0.06   0.06  0.69\n          kurtosis   se\nID           -1.35 5.17\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel       -0.75 0.60\nT0           -0.95 0.00\nT1            8.21 0.00\nT2            0.13 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: descriptives-wide\n\n## PSD95\ndescribe(psd95_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad   min    max  range  skew\nID           1 145 108.39 62.25 122.00  109.95 80.06  1.00 202.00 201.00 -0.24\nStandort     2 145   1.63  0.49   2.00    1.66  0.00  1.00   2.00   1.00 -0.52\nGruppe*      3 145   1.47  0.50   1.00    1.46  0.00  1.00   2.00   1.00  0.12\nSex*         4 145   1.43  0.50   1.00    1.41  0.00  1.00   2.00   1.00  0.29\nAge_start    5 145  69.57  3.50  69.00   69.36  2.97 62.00  78.00  16.00  0.56\nCogTel       6 145  31.77  7.20  32.40   31.77  8.60 15.50  49.20  33.70 -0.01\nT0           7 139   0.03  0.02   0.03    0.03  0.01  0.00   0.13   0.13  2.27\nT1           8 122   0.03  0.01   0.03    0.03  0.01  0.01   0.07   0.06  0.68\nT2           9  96   0.03  0.01   0.03    0.03  0.01  0.00   0.06   0.05 -0.09\n          kurtosis   se\nID           -1.35 5.17\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel       -0.75 0.60\nT0           11.51 0.00\nT1            0.03 0.00\nT2           -0.41 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: descriptives-wide\n\ndescribe(psd95_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad  min    max  range  skew\nID           1 145 108.39 62.25  122.0  109.95 80.06  1.0 202.00 201.00 -0.24\nStandort     2 145   1.63  0.49    2.0    1.66  0.00  1.0   2.00   1.00 -0.52\nGruppe*      3 145   1.47  0.50    1.0    1.46  0.00  1.0   2.00   1.00  0.12\nSex*         4 145   1.43  0.50    1.0    1.41  0.00  1.0   2.00   1.00  0.29\nAge_start    5 145  69.57  3.50   69.0   69.36  2.97 62.0  78.00  16.00  0.56\nCogTel       6 145  31.77  7.20   32.4   31.77  8.60 15.5  49.20  33.70 -0.01\nT0           7 139   0.00  0.01    0.0    0.00  0.00  0.0   0.05   0.05  3.65\nT1           8 122   0.00  0.01    0.0    0.00  0.00  0.0   0.06   0.06  3.28\nT2           9  96   0.00  0.00    0.0    0.00  0.00  0.0   0.02   0.02  5.48\n          kurtosis   se\nID           -1.35 5.17\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel       -0.75 0.60\nT0           13.50 0.00\nT1           12.12 0.00\nT2           31.81 0.00\n```\n\n\n:::\n:::\n\n\n\n\n## Plotting EDA\n\n### Boxplots\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\neda_bdnf <- cpg\nbdnfcols_to_modify <- 5:14\n\neda_tau <- cpg\ntaucols_to_modify <- 19:67\n\neda_psd95 <- cpg\npsd95cols_to_modify <- 74:116\n\n# Remove the suffix 'BDNF' from the column names in columns 5 to 14\ncolnames(eda_bdnf)[bdnfcols_to_modify] <- sub(\"BDNF$\", \"\", colnames(eda_bdnf)[bdnfcols_to_modify])\n\n# remove \"Tau\ncolnames(eda_tau)[taucols_to_modify] <- sub(\"Tau$\", \"\", colnames(eda_tau)[taucols_to_modify])\n\n#remove PSD\ncolnames(eda_psd95)[psd95cols_to_modify] <- sub(\"PSD95$\", \"\", colnames(eda_psd95)[psd95cols_to_modify])\n\n# View the updated column names\nprint(colnames(eda_bdnf[c(5:14)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m148.\" \"m111.\" \"m087.\" \"m066.\" \"m058.\" \"m039.\" \"m035.\" \"m024.\" \"p018.\"\n[10] \"p020.\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(colnames(eda_tau[c(19:67)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m337.\"   \"m331.\"   \"m323.\"   \"m315.\"   \"m310.\"   \"m306.\"   \"m300.\"  \n [8] \"m293.\"   \"m287.\"   \"m277.\"   \"m249.\"   \"m219.\"   \"m210.\"   \"m207.\"  \n[15] \"m187.\"   \"m181.\"   \"m172.\"   \"m152.\"   \"m147.\"   \"m111.1.\" \"m109.\"  \n[22] \"m105.\"   \"m100.\"   \"m95.\"    \"m93.\"    \"m91.\"    \"m87.\"    \"m85.\"   \n[29] \"m80.\"    \"m73.\"    \"m70.\"    \"m68.\"    \"m58.\"    \"m53.\"    \"m41.\"   \n[36] \"m39.\"    \"m28.\"    \"m25.\"    \"m16.\"    \"m11.\"    \"m4.\"     \"m1.\"    \n[43] \"p3.\"     \"p7.\"     \"p11.\"    \"p19.\"    \"p23.\"    \"p25.\"    \"p27.\"   \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(colnames(eda_psd95[c(72:116)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m465.PSD95\" \"m418.PSD95\" \"m405.\"      \"m400.\"      \"m395.\"     \n [6] \"m392.\"      \"m349.\"      \"m340.\"      \"m329.\"      \"m326.\"     \n[11] \"m294.\"      \"m291.\"      \"m284.\"      \"m282.\"      \"m254.\"     \n[16] \"m249.1.\"    \"m236.\"      \"m226.\"      \"m199.\"      \"m193.\"     \n[21] \"m176.\"      \"m165.\"      \"m163.\"      \"m155.\"      \"m150.\"     \n[26] \"m124.\"      \"m113.\"      \"m92.\"       \"m83.\"       \"m77.\"      \n[31] \"m69.\"       \"m49.\"       \"m35.\"       \"m31.\"       \"m28.1.\"    \n[36] \"m24.\"       \"m18.\"       \"m11.1.\"     \"p23.1.\"     \"p31.\"      \n[41] \"p36.\"       \"p60.\"       \"p91.\"       \"p95.\"       \"p122.\"     \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#dev.new(width=14, height=7)\n#par(mfrow = c(3, 3))\n#layout(matrix(c(0, 1, 0, 2, 2, 2, 3, 3, 3), nrow = 3, byrow = TRUE))\n#with()!\n```\n:::\n\n\n\n\n::: {#cell-fig-boxplot-cpg-bdnf .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-boxplot-cpg-bdnf\n\nboxplot(eda_bdnf[, c(5:14)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the BDNF-CpGs\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/fig-boxplot-cpg-bdnf-1.png){#fig-boxplot-cpg-bdnf}\n:::\n:::\n\n\n\n\n::: {#cell-fig-boxplot-cpg-tau .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-boxplot-cpg-tau\n\nboxplot(eda_tau[, c(19:67)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the Tau-CpGs\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/fig-boxplot-cpg-tau-1.png){#fig-boxplot-cpg-tau}\n:::\n:::\n\n\n\n\n::: {#cell-fig-boxplot-cpg-psd95 .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-boxplot-cpg-psd95\n\nboxplot(eda_psd95[, c(72:116)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the PSD95-CpGs\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/fig-boxplot-cpg-psd95-1.png){#fig-boxplot-cpg-psd95}\n:::\n:::\n\n\n\n::: {#cell-fig-boxplots-cpg-all .cell}\n\n```{.r .cell-code .hidden}\n#| label: fig-boxplots-cpg-all\n#| fig-cap: \"Boxplots of CpG methylation levels for BDNF, Tau, and PSD95.\"\n#| fig-width: 10\n#| fig-height: 8\n\nop <- par(no.readonly = TRUE)\npar(mfrow = c(3, 1), mar = c(6, 4, 3, 1), oma = c(0, 0, 1, 0))\n\nboxplot(eda_bdnf[, 5:14],\n        xlab = \"CpGs\", ylab = \"Methylation Level\",\n        main = \"BDNF CpGs\",\n        las = 2, cex.axis = 0.8)\n\nboxplot(eda_tau[, 19:67],\n        xlab = \"CpGs\", ylab = \"Methylation Level\",\n        main = \"Tau CpGs\",\n        las = 2, cex.axis = 0.6)\n\nboxplot(eda_psd95[, 72:116],\n        xlab = \"CpGs\", ylab = \"Methylation Level\",\n        main = \"PSD95 CpGs\",\n        las = 2, cex.axis = 0.6)\n\npar(op)\n```\n\n::: {.cell-output-display}\n![Boxplots of CpG methylation levels for BDNF, Tau, and PSD95.](eda_files/figure-ipynb/fig-boxplots-cpg-all-1.png){#fig-boxplots-cpg-all}\n:::\n:::\n\n\n\n#### Zoom to methlyated CpGs in Tau and PSD95\nsiehe \"131124_TBM mit Martin.qmd\" ab Zeile 1074\n\n### Violinplots\nSiehe \"Python_violinplots.ipynb\"\n\n\n### Lineplots\n\n\n::: {.cell .hidden}\n\n```{.r .cell-code .hidden}\n#| label: helpers-cpg-long\n#| include: false\n\n# Helper: convert wide CpG data to long format and keep CpG order\n\nmake_long <- function(df, cols) {\nlevs <- names(df)[cols]\ndf %>%\npivot_longer(cols = all_of(cols), names_to = \"CpG\", values_to = \"Expression\") %>%\nmutate(\nCpG        = factor(CpG, levels = levs),\nExpression = suppressWarnings(as.numeric(Expression))\n)\n}\n\n# Helper: median + IQR per CpG\n\nplot_median_iqr <- function(long_df, title) {\nlong_df %>%\ngroup_by(CpG) %>%\nsummarise(\nq25   = quantile(Expression, 0.25, na.rm = TRUE),\nmedian= median(Expression, na.rm = TRUE),\nq75   = quantile(Expression, 0.75, na.rm = TRUE),\n.groups = \"drop\"\n) %>%\nggplot(aes(CpG)) +\ngeom_ribbon(aes(ymin = q25, ymax = q75, group = 1), alpha = 0.25) +\ngeom_line(aes(y = median, group = 1), linewidth = 1) +\ngeom_point(aes(y = median), size = 2) +\nlabs(title = title, x = \"CpG\", y = \"Expression\") +\ntheme_minimal() +\ntheme(axis.text.x = element_text(angle = 45, hjust = 1))\n}\n\n# Helper: decile profiles (10 typical lines)\n\nplot_deciles <- function(long_df, id_col, title) {\nidq <- enquo(id_col)\n\nid_deciles <- long_df %>%\ngroup_by(!!idq) %>%\nsummarise(id_mean = mean(Expression, na.rm = TRUE), .groups = \"drop\") %>%\nmutate(decile = ntile(id_mean, 10))\n\ndecile_cpgl <- long_df %>%\ninner_join(id_deciles, by = as_name(idq)) %>%\ngroup_by(decile, CpG) %>%\nsummarise(median = median(Expression, na.rm = TRUE), .groups = \"drop\")\n\nggplot(decile_cpgl,\naes(CpG, median, group = factor(decile), color = factor(decile))) +\ngeom_line(linewidth = 1) +\ngeom_point(size = 1.5) +\nlabs(title = title, x = \"CpG\", y = \"Median expression\", color = \"Decile\") +\ntheme_minimal() +\ntheme(axis.text.x = element_text(angle = 45, hjust = 1))\n}\n\n# Helper: k-means centroid profiles (~k typical lines)\n\nplot_kmeans <- function(long_df, id_col, k = 8, title = NULL) {\nidq <- enquo(id_col)\n\nwide <- long_df %>%\npivot_wider(\nid_cols    = !!idq,\nnames_from = CpG,\nvalues_from= Expression,\nvalues_fn  = ~ median(.x, na.rm = TRUE),\nvalues_fill= NA_real_\n)\n\nstopifnot(!any(sapply(wide, is.list)))\n\nmat <- wide %>% select(-!!idq) %>% data.matrix()\nfor (j in seq_len(ncol(mat))) {\nmj <- median(mat[, j], na.rm = TRUE)\nmat[is.na(mat[, j]), j] <- mj\n}\n\nset.seed(1)\nkm <- kmeans(scale(mat), centers = k, nstart = 25)\n\ncenters <- as.data.frame(km$centers) %>%\nrownames_to_column(\"cluster\") %>%\npivot_longer(-cluster, names_to = \"CpG\", values_to = \"Expression\") %>%\nmutate(\ncluster = factor(cluster),\nCpG     = factor(CpG, levels = names(wide)[-1])\n)\n\nggplot(centers, aes(CpG, Expression, group = cluster, color = cluster)) +\ngeom_line(linewidth = 1.1) +\ngeom_point(size = 1.4) +\nlabs(\ntitle = ifelse(is.null(title),\n\"Cluster centroid profiles (scaled)\", title),\nx = \"CpG\", y = \"Scaled expression\", color = \"Cluster\"\n) +\ntheme_minimal() +\ntheme(axis.text.x = element_text(angle = 45, hjust = 1))\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\nbdnf_cols <- 5:14\ntau_cols  <- 19:67\npsd_cols  <- 72:116\n\n\n# Long versions (CpG x person)\n\nbdnf_cpg_long  <- make_long(eda_bdnf,  bdnf_cols)\ntau_cpg_long   <- make_long(eda_tau,   tau_cols)\npsd95_cpg_long <- make_long(eda_psd95, psd_cols)\n\n# BDNF\n\nplot_median_iqr(bdnf_cpg_long, \"BDNF CpGs — median with IQR\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-1.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\nplot_deciles(   bdnf_cpg_long, ID.BDNF,  \"BDNF CpGs — ID decile profiles\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 10 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 10 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-2.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\nplot_kmeans(    bdnf_cpg_long, ID.BDNF,  k = 8,\ntitle = \"BDNF CpGs — cluster centroid profiles (scaled)\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-3.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\n# Tau\n\nplot_median_iqr(tau_cpg_long, \"Tau CpGs — median with IQR\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-4.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\nplot_deciles(   tau_cpg_long, ID.Tau,   \"Tau CpGs — ID decile profiles\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 49 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 49 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-5.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\nplot_kmeans(    tau_cpg_long, ID.Tau,   k = 8,\ntitle = \"Tau CpGs — cluster centroid profiles (scaled)\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-6.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\n# PSD95\n\nplot_median_iqr(psd95_cpg_long, \"PSD95 CpGs — median with IQR\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-7.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\nplot_deciles(   psd95_cpg_long, ID.PSD95, \"PSD95 CpGs — ID decile profiles\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 45 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 45 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-8.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-cpg\n\nplot_kmeans(    psd95_cpg_long, ID.PSD95, k = 8,\ntitle = \"PSD95 CpGs — cluster centroid profiles (scaled)\")\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-cpg-9.png)\n:::\n:::\n\n\n\n### Lineplots by Zeitpunkt\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: lineplots-zeit\n\n# Column ranges reused\n\nbdnf_cols <- 5:14\ntau_cols  <- 19:67\npsd_cols  <- 72:116\n\nbdnf_levels <- names(eda_bdnf)[bdnf_cols]\ntau_levels  <- names(eda_tau)[tau_cols]\npsd_levels  <- names(eda_psd95)[psd_cols]\n\nbdnf_time_long <- eda_bdnf %>%\npivot_longer(all_of(bdnf_cols), names_to = \"CpG\", values_to = \"Expression\") %>%\ntransmute(\nGene       = \"BDNF\",\nID         = ID.BDNF,\nZeit       = factor(Zeitpunkt.BDNF),\nCpG        = factor(CpG, levels = bdnf_levels),\nExpression = suppressWarnings(as.numeric(Expression))\n)\n\ntau_time_long <- eda_tau %>%\npivot_longer(all_of(tau_cols), names_to = \"CpG\", values_to = \"Expression\") %>%\ntransmute(\nGene       = \"Tau\",\nID         = ID.Tau,\nZeit       = factor(Zeit.Tau),\nCpG        = factor(CpG, levels = tau_levels),\nExpression = suppressWarnings(as.numeric(Expression))\n)\n\npsd95_time_long <- eda_psd95 %>%\npivot_longer(all_of(psd_cols), names_to = \"CpG\", values_to = \"Expression\") %>%\ntransmute(\nGene       = \"PSD95\",\nID         = ID.PSD95,\nZeit       = factor(Zeitpunkt.PSD95),\nCpG        = factor(CpG, levels = psd_levels),\nExpression = suppressWarnings(as.numeric(Expression))\n)\n\nall_time_long <- bind_rows(bdnf_time_long, tau_time_long, psd95_time_long)\n\n# A) Zeit summary per gene: median ± IQR\n\nzeit_sum <- all_time_long %>%\ngroup_by(Gene, Zeit, CpG) %>%\nsummarise(\nq25   = quantile(Expression, 0.25, na.rm = TRUE),\nmedian= median(Expression, na.rm = TRUE),\nq75   = quantile(Expression, 0.75, na.rm = TRUE),\n.groups = \"drop\"\n)\n\nggplot(zeit_sum, aes(CpG, median, group = Zeit, color = Zeit)) +\ngeom_line(linewidth = 1) +\ngeom_point(size = 1.6) +\ngeom_errorbar(aes(ymin = q25, ymax = q75), width = 0.15, alpha = 0.5) +\nfacet_wrap(~ Gene, scales = \"free_x\", ncol = 1) +\nlabs(title = \"CpG profiles by Zeit (median ± IQR)\",\nx = \"CpG\", y = \"Expression\") +\ntheme_minimal() +\ntheme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 104 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 104 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-zeit-1.png)\n:::\n\n```{.r .cell-code .hidden}\n#| label: lineplots-zeit\n\n# B) Spaghetti per ID + LOESS per Zeit\n\nggplot(all_time_long, aes(CpG, Expression, color = Zeit)) +\ngeom_line(aes(group = interaction(Gene, Zeit, ID)),\nalpha = 0.15, linewidth = 0.4) +\ngeom_point(alpha = 0.15, size = 0.6) +\ngeom_smooth(se = FALSE, linewidth = 1.2) +\nfacet_wrap(~ Gene, scales = \"free_x\", ncol = 1) +\nlabs(title = \"Changes in CpG expression by Zeit (per gene)\",\nx = \"CpG\", y = \"Expression\") +\ntheme_minimal() +\ntheme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2726 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2271 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 2726 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/lineplots-zeit-2.png)\n:::\n:::\n\n\n## CpG summary table\n### BDNF\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: cpg-summary-bdnf\n\ncpgl_table_bdnf <- bdnf_cpg_long %>%\ngroup_by(CpG) %>%\nsummarise(\nn      = n(),\nmean   = mean(Expression, na.rm = TRUE),\nsd     = sd(Expression, na.rm = TRUE),\nmedian = median(Expression, na.rm = TRUE),\nq25    = quantile(Expression, 0.25, na.rm = TRUE),\nq75    = quantile(Expression, 0.75, na.rm = TRUE),\nmin    = min(Expression, na.rm = TRUE),\nmax    = max(Expression, na.rm = TRUE),\n.groups = \"drop\"\n)\n\nprint(cpgl_table_bdnf, n = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 9\n   CpG       n   mean     sd median   q25   q75   min   max\n   <fct> <int>  <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>\n 1 m148.   375 0.145  0.113    0.14  0.05  0.21     0  0.55\n 2 m111.   375 0.109  0.0982   0.09  0.01  0.18     0  0.54\n 3 m087.   375 0.0185 0.0381   0     0     0.02     0  0.31\n 4 m066.   375 0.119  0.112    0.1   0     0.19     0  0.51\n 5 m058.   375 0.123  0.103    0.11  0.04  0.19     0  0.55\n 6 m039.   375 0.0736 0.0833   0.05  0     0.11     0  0.55\n 7 m035.   375 0.0706 0.100    0.03  0     0.1      0  0.66\n 8 m024.   375 0.0120 0.0326   0     0     0        0  0.22\n 9 p018.   375 0.0123 0.0491   0     0     0        0  0.7 \n10 p020.   375 0.0119 0.0389   0     0     0        0  0.3 \n```\n\n\n:::\n:::\n\n\n### Tau\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: cpg-summary-tau\n\ncpgl_table_tau <- tau_cpg_long %>%\ngroup_by(CpG) %>%\nsummarise(\nn = n(),\nmean = mean(Expression, na.rm = TRUE),\nsd = sd(Expression, na.rm = TRUE),\nmedian = median(Expression, na.rm = TRUE),\nq25 = quantile(Expression, 0.25, na.rm = TRUE),\nq75 = quantile(Expression, 0.75, na.rm = TRUE),\nmin = min(Expression, na.rm = TRUE),\nmax = max(Expression, na.rm = TRUE),\n.groups = \"drop\"\n)\n\nprint(cpgl_table_tau, n = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 49 × 9\n   CpG         n   mean     sd median   q25    q75   min   max\n   <fct>   <int>  <dbl>  <dbl>  <dbl> <dbl>  <dbl> <dbl> <dbl>\n 1 m337.     375 0.423  0.170    0.44  0.34 0.52       0  1   \n 2 m331.     375 0.337  0.152    0.35  0.25 0.43       0  0.94\n 3 m323.     375 0.288  0.134    0.28  0.21 0.365      0  0.92\n 4 m315.     375 0.210  0.144    0.2   0.11 0.29       0  0.99\n 5 m310.     375 0.468  0.139    0.47  0.38 0.56       0  0.99\n 6 m306.     375 0.314  0.135    0.32  0.22 0.4        0  0.97\n 7 m300.     375 0.102  0.0931   0.09  0.04 0.14       0  0.92\n 8 m293.     375 0.129  0.107    0.11  0.05 0.175      0  0.98\n 9 m287.     375 0.0393 0.0569   0.01  0    0.06       0  0.33\n10 m277.     375 0.0964 0.0900   0.08  0.03 0.14       0  0.46\n11 m249.     375 0.123  0.119    0.1   0.04 0.178      0  0.99\n12 m219.     375 0.177  0.115    0.17  0.1  0.24       0  0.98\n13 m210.     375 0.109  0.0885   0.1   0.04 0.16       0  0.58\n14 m207.     375 0.202  0.112    0.19  0.13 0.28       0  0.54\n15 m187.     375 0.0454 0.0620   0.03  0    0.06       0  0.74\n16 m181.     375 0.0301 0.0476   0.01  0    0.04       0  0.24\n17 m172.     375 0.0409 0.0506   0.03  0    0.06       0  0.37\n18 m152.     375 0.0271 0.0581   0.02  0    0.04       0  0.92\n19 m147.     375 0.0123 0.0320   0     0    0          0  0.2 \n20 m111.1.   375 0.0570 0.0471   0.05  0.03 0.08       0  0.38\n21 m109.     375 0.0101 0.0350   0     0    0          0  0.33\n22 m105.     375 0.0107 0.0400   0     0    0          0  0.37\n23 m100.     375 0.0319 0.0361   0.03  0.01 0.04       0  0.28\n24 m95.      375 0.0554 0.0572   0.05  0.02 0.08       0  0.6 \n25 m93.      375 0.0113 0.0372   0     0    0          0  0.38\n26 m91.      375 0.0186 0.0350   0     0    0.02       0  0.23\n27 m87.      375 0.0145 0.0549   0     0    0          0  0.52\n28 m85.      375 0.0143 0.0446   0     0    0.0025     0  0.37\n29 m80.      375 0.0873 0.0673   0.08  0.05 0.11       0  0.4 \n30 m73.      375 0.0178 0.0557   0     0    0          0  0.44\n31 m70.      375 0.0162 0.0419   0     0    0.01       0  0.33\n32 m68.      375 0.0413 0.0446   0.03  0    0.07       0  0.43\n33 m58.      375 0.0191 0.0595   0     0    0          0  0.42\n34 m53.      375 0.0191 0.0415   0     0    0.02       0  0.34\n35 m41.      375 0.0159 0.0465   0     0    0          0  0.35\n36 m39.      375 0.0214 0.0486   0     0    0.02       0  0.33\n37 m28.      375 0.0158 0.0515   0     0    0          0  0.46\n38 m25.      375 0.0198 0.0514   0     0    0.01       0  0.37\n39 m16.      375 0.0727 0.0559   0.06  0.04 0.1        0  0.37\n40 m11.      375 0.0242 0.0482   0     0    0.03       0  0.37\n41 m4.       375 0.0182 0.0464   0     0    0.01       0  0.38\n42 m1.       375 0.0150 0.0488   0     0    0          0  0.51\n43 p3.       375 0.0157 0.0651   0     0    0          0  0.88\n44 p7.       375 0.0126 0.0479   0     0    0          0  0.36\n45 p11.      375 0.0475 0.0548   0.03  0.01 0.06       0  0.33\n46 p19.      375 0.0295 0.0469   0.02  0    0.04       0  0.36\n47 p23.      375 0.0275 0.0638   0     0    0.03       0  0.73\n48 p25.      375 0.0373 0.0656   0.01  0    0.05       0  0.53\n49 p27.      375 0.0403 0.0704   0.02  0    0.05       0  0.7 \n```\n\n\n:::\n:::\n\n\n### PSD95\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: cpg-summary-psd95\n\ncpgl_table_psd95 <- psd95_cpg_long %>%\ngroup_by(CpG) %>%\nsummarise(\nn      = n(),\nmean   = mean(Expression, na.rm = TRUE),\nsd     = sd(Expression, na.rm = TRUE),\nmedian = median(Expression, na.rm = TRUE),\nq25    = quantile(Expression, 0.25, na.rm = TRUE),\nq75    = quantile(Expression, 0.75, na.rm = TRUE),\nmin    = min(Expression, na.rm = TRUE),\nmax    = max(Expression, na.rm = TRUE),\n.groups = \"drop\"\n)\n\nprint(cpgl_table_psd95, n = Inf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 45 × 9\n   CpG            n    mean     sd median   q25   q75   min   max\n   <fct>      <int>   <dbl>  <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>\n 1 m465.PSD95   375 0.0252  0.0554   0     0    0.03      0  0.37\n 2 m418.PSD95   375 0.0203  0.0592   0     0    0.01      0  0.51\n 3 m405.        375 0.0204  0.0526   0     0    0.01      0  0.5 \n 4 m400.        375 0.0232  0.0628   0     0    0.01      0  0.5 \n 5 m395.        375 0.0191  0.0594   0     0    0         0  0.72\n 6 m392.        375 0.0132  0.0425   0     0    0.005     0  0.52\n 7 m349.        375 0.0194  0.0538   0     0    0.02      0  0.74\n 8 m340.        375 0.0150  0.0439   0     0    0         0  0.49\n 9 m329.        375 0.0108  0.0575   0     0    0         0  0.88\n10 m326.        375 0.0160  0.0595   0     0    0         0  0.67\n11 m294.        375 0.0173  0.0741   0     0    0         0  0.58\n12 m291.        375 0.0108  0.0452   0     0    0         0  0.52\n13 m284.        375 0.00821 0.0261   0     0    0         0  0.21\n14 m282.        375 0.0124  0.0335   0     0    0         0  0.29\n15 m254.        375 0.0138  0.0405   0     0    0         0  0.36\n16 m249.1.      375 0.0137  0.0602   0     0    0         0  0.58\n17 m236.        375 0.0115  0.0494   0     0    0         0  0.48\n18 m226.        375 0.0120  0.0326   0     0    0         0  0.34\n19 m199.        375 0.0137  0.0417   0     0    0.01      0  0.5 \n20 m193.        375 0.0141  0.0378   0     0    0.01      0  0.32\n21 m176.        375 0.0126  0.0440   0     0    0         0  0.54\n22 m165.        375 0.0178  0.0495   0     0    0.01      0  0.37\n23 m163.        375 0.0145  0.0422   0     0    0         0  0.54\n24 m155.        375 0.0153  0.0576   0     0    0.01      0  0.73\n25 m150.        375 0.0179  0.0574   0     0    0.01      0  0.73\n26 m124.        375 0.0102  0.0460   0     0    0         0  0.54\n27 m113.        375 0.0126  0.0498   0     0    0         0  0.66\n28 m92.         375 0.0249  0.0657   0     0    0.02      0  0.61\n29 m83.         375 0.0248  0.0792   0     0    0.02      0  0.72\n30 m77.         375 0.0119  0.0308   0     0    0.01      0  0.31\n31 m69.         375 0.0161  0.0366   0     0    0.02      0  0.34\n32 m49.         375 0.0265  0.0497   0     0    0.04      0  0.46\n33 m35.         375 0.0503  0.0793   0.03  0    0.08      0  0.96\n34 m31.         375 0.0119  0.0540   0     0    0         0  0.58\n35 m28.1.       375 0.0374  0.0659   0.01  0    0.06      0  0.85\n36 m24.         375 0.0309  0.0444   0     0    0.05      0  0.29\n37 m18.         375 0.0172  0.0495   0     0    0.01      0  0.55\n38 m11.1.       375 0.0275  0.0540   0     0    0.04      0  0.52\n39 p23.1.       375 0.225   0.135    0.22  0.12 0.31      0  0.84\n40 p31.         375 0.00594 0.0431   0     0    0         0  0.68\n41 p36.         375 0.0518  0.110    0     0    0.05      0  0.69\n42 p60.         375 0.111   0.143    0.04  0    0.2       0  1   \n43 p91.         375 0.0193  0.0744   0     0    0         0  0.78\n44 p95.         375 0.234   0.156    0.24  0.1  0.34      0  0.65\n45 p122.        375 0.0271  0.0744   0     0    0.02      0  0.64\n```\n\n\n:::\n:::\n\n\n\n\n## Cross-Tabulations and Chi-Squared Tests\n### BDNF\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: bdnf-wide-clean\n\nbdnf_labels <- read.table(header = TRUE, text = \"\nname      label\nID        'Participant ID'\nStandort  'Site'\nGruppe    'Group'\nSex       'Sex'\nAge_start 'Age at baseline (years)'\nCogTel    'CogTel total score'\nT0        'BDNF at T0'\nT1        'BDNF at T1'\nT2        'BDNF at T2'\n\")\n\nbdnf2 <- bdnf_mean_wide %>%\nmutate(\nID = as.integer(ID),\nStandort = case_when(\nStandort %in% c(0, \"0\") ~ \"Site_0\",\nStandort %in% c(1, \"1\") ~ \"Site_1\",\nTRUE ~ as.character(Standort)\n),\nGruppe = dplyr::recode(Gruppe, \"Controll\" = \"Control\"),\nSex    = dplyr::recode(Sex,    \"F\" = \"Female\", \"M\" = \"Male\"),\nacross(c(Standort, Gruppe, Sex), ~ fct_infreq(as.factor(.x)))\n) %>%\nimport_labels(bdnf_labels, name_from = \"name\", label_from = \"label\") %>%\nas_tibble()\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: bdnf-crosstable-group\n\ncrosstable(\nbdnf2,\nc(Age_start, CogTel, T0:T2, Sex),\nby = Gruppe,\nshowNA= \"ifany\",\ntotal = \"both\"\n) %>%\nas_flextable(keep_id = TRUE)\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/bdnf-crosstable-group-1.png)\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: bdnf-crosstable-strata\n\n#Long by time, with Time*Group strata\n\nbdnf_time_long <- bdnf2 %>%\npivot_longer(T0, names_to = \"Time\", values_to = \"BDNF\") %>%\nmutate(\nTime = factor(Time, levels = c(\"T0\", \"T1\", \"T2\")),\nGruppe = factor(Gruppe),\nID = factor(ID),\nStratum= interaction(Time, Gruppe, drop = TRUE)\n)\n\ncrosstable(\nbdnf_time_long,\nc(Age_start, CogTel, Sex, BDNF),\nby = Stratum,\nshowNA= \"ifany\",\ntotal = \"both\",\ntest = TRUE\n) %>%\nas_flextable()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in crosstable(bdnf_time_long, c(Age_start, CogTel, Sex, BDNF), by = Stratum, : Be aware that automatic global testing should only be done in an exploratory\ncontext, as it would cause extensive alpha inflation otherwise.\nThis warning is displayed once every 8 hours.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/bdnf-crosstable-strata-1.png)\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: bdnf-sex-chi-square\n\ntab <- with(bdnf2, table(Sex, Gruppe))\ntab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Gruppe\nSex      Control Piano\n  Female      46    37\n  Male        31    30\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: bdnf-sex-chi-square\n\nchisq.test(tab)                          # chi-square\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  tab\nX-squared = 0.1429, df = 1, p-value = 0.7054\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: bdnf-sex-chi-square\n\nchi_no_corr <- suppressWarnings(chisq.test(tab, correct = FALSE))\nphi <- sqrt(unname(chi_no_corr$statistic) / sum(tab))\nphi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04558996\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#| label: bdnf-sex-chi-square\n\nprop.test(\nx = c(tab[\"Male\", \"Control\"], tab[\"Male\", \"Piano\"]),\nn = c(colSums(tab)[\"Control\"], colSums(tab)[\"Piano\"])\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(tab[\"Male\", \"Control\"], tab[\"Male\", \"Piano\"]) out of c(colSums(tab)[\"Control\"], colSums(tab)[\"Piano\"])\nX-squared = 0.1429, df = 1, p-value = 0.7054\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.2209109  0.1305833\nsample estimates:\n   prop 1    prop 2 \n0.4025974 0.4477612 \n```\n\n\n:::\n:::\n\n### Tau\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: tau-wide-clean\n\ntau_labels <- read.table(header = TRUE, text = \"\nname      label\nID        'Participant ID'\nStandort  'Site'\nGruppe    'Group'\nSex       'Sex'\nAge_start 'Age at baseline (years)'\nCogTel    'CogTel total score'\nT0        'Tau at T0'\nT1        'Tau at T1'\nT2        'Tau at T2'\n\")\n\ntau2 <- tau_mean_wide %>%\nmutate(\nID = as.integer(ID),\nStandort = case_when(\nStandort %in% c(0, \"0\") ~ \"Site_0\",\nStandort %in% c(1, \"1\") ~ \"Site_1\",\nTRUE ~ as.character(Standort)\n),\nGruppe = dplyr::recode(Gruppe, \"Controll\" = \"Control\"),\nSex    = dplyr::recode(Sex,    \"F\" = \"Female\", \"M\" = \"Male\"),\nacross(c(Standort, Gruppe, Sex), ~ fct_infreq(as.factor(.x)))\n) %>%\nimport_labels(tau_labels, name_from = \"name\", label_from = \"label\") %>%\nas_tibble()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: tau-crosstable-strata\n\ntau_time_long <- tau2 %>%\npivot_longer(T0:T2, names_to = \"Time\", values_to = \"Tau\") %>%\nmutate(\nTime   = factor(Time, levels = c(\"T0\", \"T1\", \"T2\")),\nGruppe = factor(Gruppe),\nID     = factor(ID),\nStratum= interaction(Time, Gruppe, drop = TRUE)\n)\n\ncrosstable(\ntau_time_long,\nc(Age_start, CogTel, Sex, Tau),\nby    = Stratum,\nshowNA= \"ifany\",\ntotal = \"both\",\ntest  = TRUE\n) %>%\nas_flextable()\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/tau-crosstable-strata-1.png)\n:::\n:::\n\n### PSD95\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: psd95-wide-clean\n\npsd95_labels <- read.table(header = TRUE, text = \"\nname      label\nID        'Participant ID'\nStandort  'Site'\nGruppe    'Group'\nSex       'Sex'\nAge_start 'Age at baseline (years)'\nCogTel    'CogTel total score'\nT0        'PSD95 at T0'\nT1        'PSD95 at T1'\nT2        'PSD95 at T2'\n\")\n\npsd952 <- psd95_mean_wide %>%\nmutate(\nID = as.integer(ID),\nStandort = case_when(\nStandort %in% c(0, \"0\") ~ \"Site_0\",\nStandort %in% c(1, \"1\") ~ \"Site_1\",\nTRUE ~ as.character(Standort)\n),\nGruppe = dplyr::recode(Gruppe, \"Controll\" = \"Control\"),\nSex    = dplyr::recode(Sex,    \"F\" = \"Female\", \"M\" = \"Male\"),\nacross(c(Standort, Gruppe, Sex), ~ fct_infreq(as.factor(.x)))\n) %>%\nimport_labels(psd95_labels, name_from = \"name\", label_from = \"label\") %>%\nas_tibble()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| label: psd95-crosstable-strata\n\npsd95_time_long <- psd952 %>%\npivot_longer(T0:T2, names_to = \"Time\", values_to = \"PSD95\") %>%\nmutate(\nTime   = factor(Time, levels = c(\"T0\", \"T1\", \"T2\")),\nGruppe = factor(Gruppe),\nID     = factor(ID),\nStratum= interaction(Time, Gruppe, drop = TRUE)\n)\n\ncrosstable(\npsd95_time_long,\nc(Age_start, CogTel, Sex, PSD95),\nby    = Stratum,\nshowNA= \"ifany\",\ntotal = \"both\",\ntest  = TRUE\n) %>%\nas_flextable()\n```\n\n::: {.cell-output-display}\n![](eda_files/figure-ipynb/psd95-crosstable-strata-1.png)\n:::\n:::\n",
    "supporting": [
      "eda_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}