{
  "hash": "ca8cff906596dbc4818c2201d088353f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ΤΒΜ mit Martin\"\nauthor: \"Jonas J.R. Koberschinski\"\ndate: \"2024-11-13\"\nformat:\n  pdf:\n    documentclass: scrartcl\n    papersize: letter\n---\n\n\n# Data preparation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# load librarys\nlibrary(readxl)\nlibrary(RColorBrewer)\n#library(lme4)\nlibrary(tidyr)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(reticulate)\nuse_virtualenv(\"~/myenv\", required = TRUE)\n#py_config()\n\n# set working directory\nsetwd('/Users/kobi/Desktop/Promotionsdatananalyse mit Excel und Martin')\n\n# load data\n ## BDNF\nbdnf <- read_excel(\"Rohdaten/BDNF_Neuroplastizität_Alter_CpGs_ohne_m11_und_p36_mit_verhalten_vollständig.xlsx\")\nbdnf[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 44\n  TraceFileName     ID Standort Zeitpunkt_als_Zahl Zeitpunkt Platte Group Gruppe\n  <chr>          <dbl>    <dbl>              <dbl> <chr>     <chr>  <chr> <chr> \n1 BDNF-C1_001_0…     1        0                  1 T0        Pl1    Cont… Contr…\n2 BDNF-C1_001_0…     1        0                  2 T1        Pl2    Cont… Contr…\n3 BDNF-C1_002_0…     2        0                  1 T0        Pl1    Piano Piano \n4 BDNF-C1_002_0…     2        0                  2 T1        Pl2    Piano Piano \n5 BDNF-C1_002_0…     2        0                  3 T2        Pl3    Piano Piano \n# ℹ 36 more variables: Gruppe_als_zahl <dbl>, Koordinate <chr>, m148 <dbl>,\n#   m111 <dbl>, m087 <dbl>, m066 <dbl>, m058 <dbl>, m039 <dbl>, m035 <dbl>,\n#   m024 <dbl>, p018 <dbl>, p020 <dbl>, Code <chr>, Sex <chr>, Age_start <dbl>,\n#   B03a_sleep_quality <dbl>, B03b_sleep_duration <chr>,\n#   B03c_sleep_to_recover <chr>, B09a_groesse <dbl>, B09b_gewicht <dbl>,\n#   B14a_rauchen <dbl>, rauchen <dbl>, B14d_wie_viele_zigaretten <chr>,\n#   B14b_rauchen_anfang <dbl>, B14c_raucherjahre <dbl>, …\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n ##Tau\ntau <- read_excel(\"Rohdaten/TAU_CpGs_mit_verhalten_ohne_p61_p59_p34_p29.xlsx\")\ntau[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 380\n  TraceFileName          ID    Zeit  ID_Pl4_Zeit VP_plus_zeitpunkt Platte Gruppe\n  <chr>                  <chr> <chr> <chr>                   <dbl> <chr>  <chr> \n1 TAU-C1_1_T0_Pl1_Tau_C… 1     T0    1                         101 1      Contr…\n2 TAU-C1_1_T1_Pl2_Tau_C… 1     T1    1                         102 2      Contr…\n3 TAU-C1_2_T0_Pl1_Tau_P… 2     T0    2                         201 1      Piano \n4 TAU-C1_2_T1_Pl2_Tau_P… 2     T1    2                         202 2      Piano \n5 TAU-C1_2_T2_Pl3_Tau_P… 2     T2    2                         203 3      Piano \n# ℹ 373 more variables: Koordinate <chr>, m337 <dbl>, m331 <dbl>, m323 <dbl>,\n#   m315 <dbl>, m310 <dbl>, m306 <dbl>, m300 <dbl>, m293 <dbl>, m287 <dbl>,\n#   m277 <dbl>, m249 <dbl>, m219 <dbl>, m210 <dbl>, m207 <dbl>, m187 <dbl>,\n#   m181 <dbl>, m172 <dbl>, m152 <dbl>, m147 <dbl>, m111 <dbl>, m109 <dbl>,\n#   m105 <dbl>, m100 <dbl>, m95 <dbl>, m93 <dbl>, m91 <dbl>, m87 <dbl>,\n#   m85 <dbl>, m80 <dbl>, m73 <dbl>, m70 <dbl>, m68 <dbl>, m58 <dbl>,\n#   m53 <dbl>, m41 <dbl>, m39 <dbl>, m28 <dbl>, m25 <dbl>, m16 <dbl>, …\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n ## PSD95\npsd95 <- read_excel(\"Rohdaten/PSD95_CpGs_mit_verhalten_gr̨ößer.xlsx\")\npsd95[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 376\n  TraceFileName          ID    Zeitpunkt_als_zahle VP_plus_zeitpunkt ID_Pl4_Zeit\n  <chr>                  <chr>               <dbl>             <dbl> <chr>      \n1 PSD95-C1_1_T0_Pl1_PSD… 1                       1               101 1          \n2 PSD95-C1_1_T1_Pl2_PSD… 1                       2               102 1          \n3 PSD95-C1_2_T0_Pl1_PSD… 2                       1               201 2          \n4 PSD95-C1_2_T1_Pl2_PSD… 2                       2               202 2          \n5 PSD95-C1_2_T2_Pl3_PSD… 2                       3               203 2          \n# ℹ 371 more variables: Zeitpunkt <chr>, Platte <chr>, Gruppe <chr>,\n#   Koordinate <chr>, m465 <dbl>, m418 <dbl>, m405 <dbl>, m400 <dbl>,\n#   m395 <dbl>, m392 <dbl>, m349 <dbl>, m340 <dbl>, m329 <dbl>, m326 <dbl>,\n#   m294 <dbl>, m291 <dbl>, m284 <dbl>, m282 <dbl>, m254 <dbl>, m249 <dbl>,\n#   m236 <dbl>, m226 <dbl>, m199 <dbl>, m193 <dbl>, m176 <dbl>, m165 <dbl>,\n#   m163 <dbl>, m155 <dbl>, m150 <dbl>, m124 <dbl>, m113 <dbl>, m92 <dbl>,\n#   m83 <dbl>, m77 <dbl>, m69 <dbl>, m49 <dbl>, m35 <dbl>, m31 <dbl>, …\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#data set with all CpGs in columns for EDA and PCA\ncpg <- read_excel(\"Excel seit Martin/031024_All_Genes_Explorative Datenanylse.xlsx\")\ncpg[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 116\n  `TraceFileName BDNF`       `ID BDNF` `Zeitpunkt BDNF` `Group BDNF` `m148 BDNF`\n  <chr>                          <dbl> <chr>            <chr>              <dbl>\n1 BDNF-C1_001_01_T0_Pl1_Con…         1 T0               Controll            0.18\n2 BDNF-C1_001_02_T1_Pl2_Con…         1 T1               Controll            0.07\n3 BDNF-C1_002_01_T0_Pl1_Pia…         2 T0               Piano               0.14\n4 BDNF-C1_002_02_T1_Pl2_Pia…         2 T1               Piano               0   \n5 BDNF-C1_002_03_T2_Pl3_Pia…         2 T2               Piano               0.16\n# ℹ 111 more variables: `m111 BDNF` <dbl>, `m087 BDNF` <dbl>,\n#   `m066 BDNF` <dbl>, `m058 BDNF` <dbl>, `m039 BDNF` <dbl>, `m035 BDNF` <dbl>,\n#   `m024 BDNF` <dbl>, `p018 BDNF` <dbl>, `p020 BDNF` <dbl>,\n#   `TraceFileName Tau` <chr>, `ID Tau` <dbl>, `Zeit Tau` <chr>,\n#   `Gruppe Tau` <chr>, `m337 Tau` <dbl>, `m331 Tau` <dbl>, `m323 Tau` <dbl>,\n#   `m315 Tau` <dbl>, `m310 Tau` <dbl>, `m306 Tau` <dbl>, `m300 Tau` <dbl>,\n#   `m293 Tau` <dbl>, `m287 Tau` <dbl>, `m277 Tau` <dbl>, `m249 Tau` <dbl>, …\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#TBM <- list(BDNFα, Tauα, PSD95α)\n```\n:::\n\n\n## Subset of the essential variables\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Subsetting \n ## BDNF\n  ### subset(x=⟨Datensatz⟩, subset=⟨Auswahl Zeilen⟩, select=⟨Auswahl Spalten⟩)\nbdnf_subset <- subset(bdnf, select = c(ID, Standort, Zeitpunkt, Gruppe, Sex, Age_start, CogTel))\n\n#Alternative, die eigentlich gehen müsste\n#bdnf_subset_v <- bdnf[,c(\"ID\", \"Standort\", \"Zeitpunkt\", \"Gruppe\", \"Sex\", \"Age_start\", \"CogTel\")]\n#as.data.frame(bdnf_subset_v)\n#bdnf[bdnf_subset_v]\n\n  ### Subset CpGs to calculate mean values for all rows\nbdnf_methylation <- subset(bdnf, select = c(m148:p020)) #subset the CpGs\n\nbdnf_methylation_mean <- apply(bdnf_methylation, 1, mean, na.rm=TRUE) # apply the mean on all rows (1 = per row)\nbdnf_methylation_median <- apply(bdnf_methylation, 1, median, na.rm=TRUE)\n\nbdnf_mean <- cbind(bdnf_subset, bdnf_methylation_mean)\n   colnames(bdnf_mean)[8] <- \"Mean\"\nbdnf_median <- cbind(bdnf_subset, bdnf_methylation_median)\n   colnames(bdnf_median)[8] <- \"Median\"\n\n   ####bdnf_subset$mean <- bdnf_methylation_mean #initial version before median\n   ####bdnf_subset$median <- bdnf_methylation_median\n\n  ### delete 192 u. 193, because of an confusion in values (look at the code and sex variable)\nbdnf_mean <- bdnf_mean[!(bdnf_mean$ID %in% c(192, 193)), ]\nbdnf_mean[bdnf_mean$ID >= 190 & bdnf_mean$ID <= 196, ] #show if deleted\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel    Mean\n337 190        1        T0    Piano   F        69   42.6 0.06300\n338 190        1        T1    Piano   F        69   42.6     NaN\n339 190        1        T2    Piano   F        69   42.6     NaN\n340 191        1        T0 Controll   M        77   36.9 0.05800\n341 191        1        T1 Controll   M        77   36.9 0.08600\n342 191        1        T2 Controll   M        77   36.9 0.08100\n348 194        1        T0 Controll   M        68   28.1 0.06100\n349 195        1        T0 Controll   M        62   37.4 0.01400\n350 195        1        T1 Controll   M        62   37.4 0.10000\n351 195        1        T2 Controll   M        62   37.4 0.10800\n352 196        1        T0 Controll   M        68   36.4 0.05800\n353 196        1        T1 Controll   M        68   36.4 0.06125\n354 196        1        T2 Controll   M        68   36.4 0.16100\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nbdnf_median <- bdnf_median[!(bdnf_median$ID %in% c(192, 193)), ]\nbdnf_median[bdnf_median$ID >= 190 & bdnf_median$ID <= 196, ] #show if deleted\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel Median\n337 190        1        T0    Piano   F        69   42.6  0.000\n338 190        1        T1    Piano   F        69   42.6     NA\n339 190        1        T2    Piano   F        69   42.6     NA\n340 191        1        T0 Controll   M        77   36.9  0.030\n341 191        1        T1 Controll   M        77   36.9  0.075\n342 191        1        T2 Controll   M        77   36.9  0.050\n348 194        1        T0 Controll   M        68   28.1  0.000\n349 195        1        T0 Controll   M        62   37.4  0.000\n350 195        1        T1 Controll   M        62   37.4  0.065\n351 195        1        T2 Controll   M        62   37.4  0.080\n352 196        1        T0 Controll   M        68   36.4  0.010\n353 196        1        T1 Controll   M        68   36.4  0.045\n354 196        1        T2 Controll   M        68   36.4  0.205\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n   ####alternative way\n   ####bdnf_subset <- bdnf_subset %>%\n     ####filter(!(ID %in% c(192, 193)))\nbdnf_mean[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel  Mean\n1  1        0        T0 Controll   F        67   38.9 0.075\n2  1        0        T1 Controll   F        67   38.9 0.037\n3  2        0        T0    Piano   F        76   34.6 0.102\n4  2        0        T1    Piano   F        76   34.6 0.060\n5  2        0        T2    Piano   F        76   34.6 0.084\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nbdnf_median[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel Median\n1  1        0        T0 Controll   F        67   38.9  0.045\n2  1        0        T1 Controll   F        67   38.9  0.020\n3  2        0        T0    Piano   F        76   34.6  0.105\n4  2        0        T1    Piano   F        76   34.6  0.000\n5  2        0        T2    Piano   F        76   34.6  0.085\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n ##Tau\n  ### Subset Tau\ntau_subset <- subset(tau, select = c(ID, standort_aus_andere_quelle, Zeit, Gruppe, Sex, Age_start, CogTel))\ncolnames(tau_subset)[c(2:3)] <- c(\"Standort\", \"Zeitpunkt\") #rename column 2\n\n  ### Subset CpGs to calculate mean values for all rows\ntau_methylation <- subset(tau, select = c(m331:p27))\n\ntau_methylation_mean <- apply(tau_methylation, 1, mean, na.rm = TRUE)\ntau_methylation_median <- apply(tau_methylation, 1, median, na.rm = TRUE)\n \ntau_mean <- cbind(tau_subset, tau_methylation_mean)\n    colnames(tau_mean)[8] <- \"Mean\"\ntau_median <- cbind(tau_subset, tau_methylation_median)\n    colnames(tau_median)[8] <- \"Median\"\n\n  ### delete 192 u. 193\ntau_mean <- tau_mean[!(tau_mean$ID %in% c(192, 193)), ]\ntau_mean[tau_mean$ID >= 190 & tau_mean$ID <= 196, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel       Mean\n337 190        2        T0    Piano   F        69   42.6 0.05187500\n338 190        2        T1    Piano   F        69   42.6 0.06750000\n339 190        2        T2    Piano   F        69   42.6 0.06125000\n340 191        2        T0 Controll   M        77   36.9 0.06416667\n341 191        2        T1 Controll   M        77   36.9 0.06276596\n342 191        2        T2 Controll   M        77   36.9 0.06302326\n348 194        2        T0 Controll   M        68   28.1 0.07666667\n349 195        2        T0 Controll   M        62   37.4 0.05000000\n350 195        2        T1 Controll   M        62   37.4 0.06583333\n351 195        2        T2 Controll   M        62   37.4 0.10500000\n352 196        2        T0 Controll   M        68   36.4 0.07895833\n353 196        2        T1 Controll   M        68   36.4 0.09020833\n354 196        2        T2 Controll   M        68   36.4 0.12541667\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntau_median <- tau_median[!(tau_median$ID %in% c(192, 193)), ]\ntau_median[tau_median$ID >= 190 & tau_median$ID <= 196, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel Median\n337 190        2        T0    Piano   F        69   42.6  0.000\n338 190        2        T1    Piano   F        69   42.6  0.020\n339 190        2        T2    Piano   F        69   42.6  0.000\n340 191        2        T0 Controll   M        77   36.9  0.030\n341 191        2        T1 Controll   M        77   36.9  0.030\n342 191        2        T2 Controll   M        77   36.9  0.000\n348 194        2        T0 Controll   M        68   28.1  0.035\n349 195        2        T0 Controll   M        62   37.4  0.010\n350 195        2        T1 Controll   M        62   37.4  0.020\n351 195        2        T2 Controll   M        62   37.4  0.010\n352 196        2        T0 Controll   M        68   36.4  0.040\n353 196        2        T1 Controll   M        68   36.4  0.020\n354 196        2        T2 Controll   M        68   36.4  0.030\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntau_mean[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel       Mean\n1  1        1        T0 Controll   F        67   38.9 0.08437500\n2  1        1        T1 Controll   F        67   38.9 0.07791667\n3  2        1        T0    Piano   F        76   34.6 0.09645833\n4  2        1        T1    Piano   F        76   34.6 0.07250000\n5  2        1        T2    Piano   F        76   34.6 0.07170213\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntau_median[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel Median\n1  1        1        T0 Controll   F        67   38.9  0.040\n2  1        1        T1 Controll   F        67   38.9  0.035\n3  2        1        T0    Piano   F        76   34.6  0.040\n4  2        1        T1    Piano   F        76   34.6  0.020\n5  2        1        T2    Piano   F        76   34.6  0.020\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n ## PSD95\n  ### Subset Tau\npsd95_subset <- subset(psd95, select = c(ID, standort_aus_andere_quelle, Zeitpunkt, Gruppe, Sex, Age_start, CogTel))\ncolnames(psd95_subset)[2] <- \"Standort\" #rename column 2\n\n  ### Subset CpGs to calculate mean and median values for all rows\npsd95_methylation <- subset(psd95, select = c(m465:p122))\n\npsd95_methylation_mean <- apply(psd95_methylation, 1, mean, na.rm = TRUE)\npsd95_methylation_median <- apply(psd95_methylation, 1, median, na.rm = TRUE)\n\npsd95_mean <- cbind(psd95_subset, psd95_methylation_mean)\n    colnames(psd95_mean)[8] <- \"Mean\" \npsd95_median <- cbind(psd95_subset, psd95_methylation_median)\n    colnames(psd95_median)[8] <- \"Median\"\n\n  ### delete 192 u. 193\npsd95_mean <- psd95_mean[!(psd95_mean$ID %in% c(192, 193)), ]\npsd95_mean[psd95_mean$ID >= 190 & psd95_mean$ID <= 196, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel       Mean\n335 190        2        T0    Piano   F        69   42.6 0.02609756\n336 190        2        T1    Piano   F        69   42.6 0.02930233\n337 190        2        T2    Piano   F        69   42.6 0.03000000\n338 191        2        T0 Controll   M        77   36.9 0.02511111\n339 191        2        T1 Controll   M        77   36.9 0.01666667\n340 191        2        T2 Controll   M        77   36.9 0.02625000\n346 194        2        T0 Controll   M        68   28.1 0.00000000\n347 195        2        T0 Controll   M        62   37.4 0.01870968\n348 195        2        T1 Controll   M        62   37.4 0.04272727\n349 195        2        T2 Controll   M        62   37.4 0.02622222\n350 196        2        T0 Controll   M        68   36.4 0.01909091\n351 196        2        T1 Controll   M        68   36.4 0.03844444\n352 196        2        T2 Controll   M        68   36.4 0.03272727\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npsd95_median <- psd95_median[!(psd95_median$ID %in% c(192, 193)), ]\npsd95_median[psd95_median$ID >= 190 & psd95_median$ID <= 196, ]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel Median\n335 190        2        T0    Piano   F        69   42.6      0\n336 190        2        T1    Piano   F        69   42.6      0\n337 190        2        T2    Piano   F        69   42.6      0\n338 191        2        T0 Controll   M        77   36.9      0\n339 191        2        T1 Controll   M        77   36.9      0\n340 191        2        T2 Controll   M        77   36.9      0\n346 194        2        T0 Controll   M        68   28.1      0\n347 195        2        T0 Controll   M        62   37.4      0\n348 195        2        T1 Controll   M        62   37.4      0\n349 195        2        T2 Controll   M        62   37.4      0\n350 196        2        T0 Controll   M        68   36.4      0\n351 196        2        T1 Controll   M        68   36.4      0\n352 196        2        T2 Controll   M        68   36.4      0\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npsd95_mean[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel       Mean\n1  1        1        T0 Controll   F        67   38.9 0.03977778\n2  1        1        T1 Controll   F        67   38.9 0.01931818\n3  2        1        T0    Piano   F        76   34.6 0.01512195\n4  2        1        T1    Piano   F        76   34.6 0.01155556\n5  2        1        T2    Piano   F        76   34.6 0.04454545\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npsd95_median[1:5,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ID Standort Zeitpunkt   Gruppe Sex Age_start CogTel Median\n1  1        1        T0 Controll   F        67   38.9      0\n2  1        1        T1 Controll   F        67   38.9      0\n3  2        1        T0    Piano   F        76   34.6      0\n4  2        1        T1    Piano   F        76   34.6      0\n5  2        1        T2    Piano   F        76   34.6      0\n```\n\n\n:::\n:::\n\n\n## Pivot time points to columns\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Define the two split_zeitpunkt functions for mean and median\nsplit_zeitpunkt_mean <- function(data) {\n  data %>%\n    pivot_wider(id_cols = c(ID, Standort, Gruppe, Sex, Age_start, CogTel), # no doublets!\n                names_from = Zeitpunkt, # Zeitpunkt long -> wide\n                values_from = Mean)\n}\n\nsplit_zeitpunkt_median <- function(data) {\n  data %>%\n    pivot_wider(id_cols = c(ID, Standort, Gruppe, Sex, Age_start, CogTel), # no doublets!\n                names_from = Zeitpunkt, # Zeitpunkt long -> wide\n                values_from = Median)\n}\n\n# Run the function and check the first few rows\n ## BNDF\nbdnf_mean_wide <- split_zeitpunkt_mean(bdnf_mean)\nhead(bdnf_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n     ID Standort Gruppe   Sex   Age_start CogTel      T0    T1     T2\n  <dbl>    <dbl> <chr>    <chr>     <dbl> <chr>    <dbl> <dbl>  <dbl>\n1     1        0 Controll F            67 38.9     0.075 0.037 NA    \n2     2        0 Piano    F            76 34.6     0.102 0.06   0.084\n3     3        0 Piano    M            69 22.8   NaN     0.029 NA    \n4     4        0 Controll F            75 40.6     0.109 0.021  0.097\n5     5        0 Controll F            73 25.6     0.12  0.041  0.049\n6     8        0 Controll F            67 32.7     0.059 0.082 NA    \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnrow(bdnf_mean_wide) # 144\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 144\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nbdnf_median_wide <- split_zeitpunkt_median(bdnf_median)\nhead(bdnf_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n     ID Standort Gruppe   Sex   Age_start CogTel     T0    T1     T2\n  <dbl>    <dbl> <chr>    <chr>     <dbl> <chr>   <dbl> <dbl>  <dbl>\n1     1        0 Controll F            67 38.9    0.045  0.02 NA    \n2     2        0 Piano    F            76 34.6    0.105  0     0.085\n3     3        0 Piano    M            69 22.8   NA      0    NA    \n4     4        0 Controll F            75 40.6    0.05   0     0.08 \n5     5        0 Controll F            73 25.6    0.085  0.02  0.03 \n6     8        0 Controll F            67 32.7    0.06   0    NA    \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnrow(bdnf_median_wide) # 144\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 144\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n ## Tau\ntau_mean_wide <- split_zeitpunkt_mean(tau_mean)\nhead(tau_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel     T0     T1      T2\n  <chr>    <dbl> <chr>    <chr>     <dbl> <chr>   <dbl>  <dbl>   <dbl>\n1 1            1 Controll F            67 38.9   0.0844 0.0779 NA     \n2 2            1 Piano    F            76 34.6   0.0965 0.0725  0.0717\n3 3            1 Piano    M            69 22.8   0.0542 0.0810 NA     \n4 4            1 Controll F            75 40.6   0.0598 0.0440  0.0492\n5 5            1 Controll F            73 25.6   0.0742 0.0979  0.0654\n6 8            1 Controll F            67 32.7   0.0917 0.146  NA     \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnrow(tau_mean_wide) # 145\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 145\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntau_median_wide <- split_zeitpunkt_median(tau_median)\nhead(tau_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel    T0    T1     T2\n  <chr>    <dbl> <chr>    <chr>     <dbl> <chr>  <dbl> <dbl>  <dbl>\n1 1            1 Controll F            67 38.9   0.04  0.035 NA    \n2 2            1 Piano    F            76 34.6   0.04  0.02   0.02 \n3 3            1 Piano    M            69 22.8   0.01  0.04  NA    \n4 4            1 Controll F            75 40.6   0.015 0.015  0.01 \n5 5            1 Controll F            73 25.6   0.02  0.03   0.025\n6 8            1 Controll F            67 32.7   0.025 0.12  NA    \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnrow(tau_median_wide) # 145\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 145\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n ## PSD95\npsd95_mean_wide <- split_zeitpunkt_mean(psd95_mean)\nhead(psd95_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel     T0     T1      T2\n  <chr>    <dbl> <chr>    <chr>     <dbl> <chr>   <dbl>  <dbl>   <dbl>\n1 1            1 Controll F            67 38.9   0.0398 0.0193 NA     \n2 2            1 Piano    F            76 34.6   0.0151 0.0116  0.0445\n3 3            1 Piano    M            69 22.8   0.0237 0.0133 NA     \n4 4            1 Controll F            75 40.6   0.0273 0.0169  0.0441\n5 5            1 Controll F            73 25.6   0.02   0.0302  0.0178\n6 8            1 Controll F            67 32.7   0.0187 0.0293 NA     \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnrow(psd95_mean_wide) # 145\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 145\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npsd95_median_wide <- split_zeitpunkt_median(psd95_median)\nhead(psd95_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel    T0    T1    T2\n  <chr>    <dbl> <chr>    <chr>     <dbl> <chr>  <dbl> <dbl> <dbl>\n1 1            1 Controll F            67 38.9       0     0 NA   \n2 2            1 Piano    F            76 34.6       0     0  0   \n3 3            1 Piano    M            69 22.8       0     0 NA   \n4 4            1 Controll F            75 40.6       0     0  0.02\n5 5            1 Controll F            73 25.6       0     0  0   \n6 8            1 Controll F            67 32.7       0     0 NA   \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nnrow(psd95_median_wide) # 145\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 145\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#names(bdnf_mean_wide)[1] <- \"ID2\" # rename \"ID\" to \"ID2\" to delete it later\n#names(bdnf_mean_wide)\n```\n:::\n\n\n## Write tables\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nwrite.table(bdnf_mean_wide, file = \"bdnf_mean_wide.txt\", sep = \"\\t\",\n                                                         row.names = FALSE,\n                                                         quote = FALSE)\nwrite.table(tau_mean_wide, file = \"bdnf_mean_wide.txt\", sep = \"\\t\",\n                                                         row.names = FALSE,\n                                                         quote = FALSE)\nwrite.table(psd95_mean_wide, file = \"bdnf_mean_wide.txt\", sep = \"\\t\",\n                                                         row.names = FALSE,\n                                                         quote = FALSE)\n\nwrite.table(bdnf_median_wide, file = \"bdnf_mean_wide.txt\", sep = \"\\t\",\n                                                         row.names = FALSE,\n                                                         quote = FALSE)\nwrite.table(tau_median_wide, file = \"bdnf_mean_wide.txt\", sep = \"\\t\",\n                                                         row.names = FALSE,\n                                                         quote = FALSE)\nwrite.table(psd95_median_wide, file = \"bdnf_mean_wide.txt\", sep = \"\\t\",\n                                                         row.names = FALSE,\n                                                         quote = FALSE)\n```\n:::\n\n\n## Create a new column 'T2-T0'\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#BDNF\n##mean\nbdnf_mean_T2T0 <- bdnf_mean_wide\nbdnf_mean_T2T0$T1 <- NULL\n\nbdnf_mean_T2T0 <- bdnf_mean_T2T0 %>%\n  filter(!is.na(T2), !is.na(T0)) %>%\n  mutate(`T2_T0` = T2 - T0) #does \"T2_T0\" also work?\n\nbdnf_mean_T2T0$CogTel <- as.numeric(bdnf_mean_T2T0$CogTel)\nbdnf_mean_T2T0$Standort <- as.character(bdnf_mean_T2T0$Standort)\nis.numeric(bdnf_mean_T2T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(bdnf_mean_T2T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(bdnf_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n     ID Standort Gruppe   Sex   Age_start CogTel    T0    T2   T2_T0\n  <dbl> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1     2 0        Piano    F            76   34.6 0.102 0.084 -0.0180\n2     4 0        Controll F            75   40.6 0.109 0.097 -0.012 \n3     5 0        Controll F            73   25.6 0.12  0.049 -0.071 \n4     9 0        Controll F            74   24.4 0.055 0.169  0.114 \n5    11 0        Piano    F            71   30.3 0.093 0.14   0.047 \n6    13 0        Controll F            65   42.4 0.06  0.077  0.017 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\nbdnf_median_T2T0 <- bdnf_median_wide\nbdnf_median_T2T0$T1 <- NULL\n\nbdnf_median_T2T0 <- bdnf_median_T2T0 %>%\n  filter(!is.na(T2), !is.na(T0)) %>%\n  mutate(`T2_T0` = T2 - T0) #does \"T2_T0\" also work?\n\nbdnf_median_T2T0$CogTel <- as.numeric(bdnf_median_T2T0$CogTel)\nbdnf_median_T2T0$Standort <- as.character(bdnf_median_T2T0$Standort)\nis.numeric(bdnf_median_T2T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(bdnf_median_T2T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(bdnf_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n     ID Standort Gruppe   Sex   Age_start CogTel    T0    T2   T2_T0\n  <dbl> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1     2 0        Piano    F            76   34.6 0.105 0.085 -0.02  \n2     4 0        Controll F            75   40.6 0.05  0.08   0.03  \n3     5 0        Controll F            73   25.6 0.085 0.03  -0.055 \n4     9 0        Controll F            74   24.4 0.02  0.175  0.155 \n5    11 0        Piano    F            71   30.3 0.065 0.085  0.0200\n6    13 0        Controll F            65   42.4 0.05  0.01  -0.04  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#Tau\n##mean\ntau_mean_T2T0 <- tau_mean_wide\ntau_mean_T2T0$T1 <- NULL\n\ntau_mean_T2T0 <- tau_mean_T2T0 %>%\n  filter(!is.na(T2), !is.na(T0)) %>%\n  mutate(`T2_T0` = T2 - T0) #does \"T2_T0\" also work?\n\ntau_mean_T2T0$CogTel <- as.numeric(tau_mean_T2T0$CogTel)\ntau_mean_T2T0$Standort <- as.character(tau_mean_T2T0$Standort)\nis.numeric(tau_mean_T2T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(tau_mean_T2T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(tau_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel     T0     T2    T2_T0\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl>  <dbl>  <dbl>    <dbl>\n1 2     1        Piano    F            76   34.6 0.0965 0.0717 -0.0248 \n2 4     1        Controll F            75   40.6 0.0598 0.0492 -0.0106 \n3 5     1        Controll F            73   25.6 0.0742 0.0654 -0.00875\n4 9     1        Controll F            74   24.4 0.0977 0.0888 -0.00896\n5 11    1        Piano    F            71   30.3 0.0490 0.0656  0.0167 \n6 13    1        Controll F            65   42.4 0.0408 0.0288 -0.0121 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\ntau_median_T2T0 <- tau_median_wide\ntau_median_T2T0$T1 <- NULL\n\ntau_median_T2T0 <- tau_median_T2T0 %>%\n  filter(!is.na(T2), !is.na(T0)) %>%\n  mutate(`T2_T0` = T2 - T0) #does \"T2_T0\" also work?\n\ntau_median_T2T0$CogTel <- as.numeric(tau_median_T2T0$CogTel)\ntau_median_T2T0$Standort <- as.character(tau_median_T2T0$Standort)\nis.numeric(tau_median_T2T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(tau_median_T2T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(tau_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel    T0    T2  T2_T0\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl>  <dbl>\n1 2     1        Piano    F            76   34.6 0.04  0.02  -0.02 \n2 4     1        Controll F            75   40.6 0.015 0.01  -0.005\n3 5     1        Controll F            73   25.6 0.02  0.025  0.005\n4 9     1        Controll F            74   24.4 0.025 0.02  -0.005\n5 11    1        Piano    F            71   30.3 0.01  0.015  0.005\n6 13    1        Controll F            65   42.4 0     0      0    \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#PSD95\n##mean\npsd95_mean_T2T0 <- psd95_mean_wide\npsd95_mean_T2T0$T1 <- NULL\n\npsd95_mean_T2T0 <- psd95_mean_T2T0 %>%\n  filter(!is.na(T2), !is.na(T0)) %>%\n  mutate(`T2_T0` = T2 - T0) #does \"T2_T0\" also work?\n\npsd95_mean_T2T0$CogTel <- as.numeric(psd95_mean_T2T0$CogTel)\npsd95_mean_T2T0$Standort <- as.character(psd95_mean_T2T0$Standort)\nis.numeric(psd95_mean_T2T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(psd95_mean_T2T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(psd95_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel      T0     T2    T2_T0\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl>   <dbl>  <dbl>    <dbl>\n1 2     1        Piano    F            76   34.6 0.0151  0.0445  0.0294 \n2 4     1        Controll F            75   40.6 0.0273  0.0441  0.0168 \n3 5     1        Controll F            73   25.6 0.02    0.0178 -0.00222\n4 9     1        Controll F            74   24.4 0.0244  0.0278  0.00333\n5 11    1        Piano    F            71   30.3 0.0163  0.0273  0.0110 \n6 13    1        Controll F            65   42.4 0.00591 0.04    0.0341 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\npsd95_median_T2T0 <- psd95_median_wide\npsd95_median_T2T0$T1 <- NULL\n\npsd95_median_T2T0 <- psd95_median_T2T0 %>%\n  filter(!is.na(T2), !is.na(T0)) %>%\n  mutate(`T2_T0` = T2 - T0) #does \"T2_T0\" also work?\n\npsd95_median_T2T0$CogTel <- as.numeric(psd95_median_T2T0$CogTel)\npsd95_median_T2T0$Standort <- as.character(psd95_median_T2T0$Standort)\nis.numeric(psd95_median_T2T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(psd95_median_T2T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(psd95_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel    T0    T2 T2_T0\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl> <dbl>\n1 2     1        Piano    F            76   34.6     0  0     0   \n2 4     1        Controll F            75   40.6     0  0.02  0.02\n3 5     1        Controll F            73   25.6     0  0     0   \n4 9     1        Controll F            74   24.4     0  0     0   \n5 11    1        Piano    F            71   30.3     0  0     0   \n6 13    1        Controll F            65   42.4     0  0     0   \n```\n\n\n:::\n:::\n\n\n## Create a new column 'T1-T0'\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#BDNF\n##mean\nbdnf_mean_T1T0 <- bdnf_mean_wide\nbdnf_mean_T1T0$T2 <- NULL\n\nbdnf_mean_T1T0 <- bdnf_mean_T1T0 %>%\n  filter(!is.na(T1), !is.na(T0)) %>%\n  mutate(`T1_T0` = T1 - T0)\n\nbdnf_mean_T1T0$CogTel <- as.numeric(bdnf_mean_T1T0$CogTel)\nbdnf_mean_T1T0$Standort <- as.character(bdnf_mean_T1T0$Standort)\nis.numeric(bdnf_mean_T1T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(bdnf_mean_T1T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(bdnf_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n     ID Standort Gruppe   Sex   Age_start CogTel    T0    T1  T1_T0\n  <dbl> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl>  <dbl>\n1     1 0        Controll F            67   38.9 0.075 0.037 -0.038\n2     2 0        Piano    F            76   34.6 0.102 0.06  -0.042\n3     4 0        Controll F            75   40.6 0.109 0.021 -0.088\n4     5 0        Controll F            73   25.6 0.12  0.041 -0.079\n5     8 0        Controll F            67   32.7 0.059 0.082  0.023\n6     9 0        Controll F            74   24.4 0.055 0.072  0.017\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\nbdnf_median_T1T0 <- bdnf_median_wide\nbdnf_median_T1T0$T2 <- NULL\n\nbdnf_median_T1T0 <- bdnf_median_T1T0 %>%\n  filter(!is.na(T1), !is.na(T0)) %>%\n  mutate(`T1_T0` = T1 - T0)\n\nbdnf_median_T1T0$CogTel <- as.numeric(bdnf_median_T1T0$CogTel)\nbdnf_median_T1T0$Standort <- as.character(bdnf_median_T1T0$Standort)\nis.numeric(bdnf_median_T1T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(bdnf_median_T1T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(bdnf_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n     ID Standort Gruppe   Sex   Age_start CogTel    T0    T1  T1_T0\n  <dbl> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl>  <dbl>\n1     1 0        Controll F            67   38.9 0.045 0.02  -0.025\n2     2 0        Piano    F            76   34.6 0.105 0     -0.105\n3     4 0        Controll F            75   40.6 0.05  0     -0.05 \n4     5 0        Controll F            73   25.6 0.085 0.02  -0.065\n5     8 0        Controll F            67   32.7 0.06  0     -0.06 \n6     9 0        Controll F            74   24.4 0.02  0.045  0.025\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#Tau\n##mean\ntau_mean_T1T0 <- tau_mean_wide\ntau_mean_T1T0$T2 <- NULL\n\ntau_mean_T1T0 <- tau_mean_T1T0 %>%\n  filter(!is.na(T1), !is.na(T0)) %>%\n  mutate(`T1_T0` = T1 - T0)\n\ntau_mean_T1T0$CogTel <- as.numeric(tau_mean_T1T0$CogTel)\ntau_mean_T1T0$Standort <- as.character(tau_mean_T1T0$Standort)\nis.numeric(tau_mean_T1T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(tau_mean_T1T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(tau_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel     T0     T1    T1_T0\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl>  <dbl>  <dbl>    <dbl>\n1 1     1        Controll F            67   38.9 0.0844 0.0779 -0.00646\n2 2     1        Piano    F            76   34.6 0.0965 0.0725 -0.0240 \n3 3     1        Piano    M            69   22.8 0.0542 0.0810  0.0269 \n4 4     1        Controll F            75   40.6 0.0598 0.0440 -0.0158 \n5 5     1        Controll F            73   25.6 0.0742 0.0979  0.0238 \n6 8     1        Controll F            67   32.7 0.0917 0.146   0.0541 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\ntau_median_T1T0 <- tau_median_wide\ntau_median_T1T0$T2 <- NULL\n\ntau_median_T1T0 <- tau_median_T1T0 %>%\n  filter(!is.na(T1), !is.na(T0)) %>%\n  mutate(`T1_T0` = T1 - T0)\n\ntau_median_T1T0$CogTel <- as.numeric(tau_median_T1T0$CogTel)\ntau_median_T1T0$Standort <- as.character(tau_median_T1T0$Standort)\nis.numeric(tau_median_T1T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(tau_median_T1T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(tau_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel    T0    T1   T1_T0\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1 1     1        Controll F            67   38.9 0.04  0.035 -0.0050\n2 2     1        Piano    F            76   34.6 0.04  0.02  -0.02  \n3 3     1        Piano    M            69   22.8 0.01  0.04   0.03  \n4 4     1        Controll F            75   40.6 0.015 0.015  0     \n5 5     1        Controll F            73   25.6 0.02  0.03   0.01  \n6 8     1        Controll F            67   32.7 0.025 0.12   0.095 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#PSD95\n##mean\npsd95_mean_T1T0 <- psd95_mean_wide\npsd95_mean_T1T0$T2 <- NULL\n\npsd95_mean_T1T0 <- psd95_mean_T1T0 %>%\n  filter(!is.na(T1), !is.na(T0)) %>%\n  mutate(`T1_T0` = T1 - T0)\n\npsd95_mean_T1T0$CogTel <- as.numeric(psd95_mean_T1T0$CogTel)\npsd95_mean_T1T0$Standort <- as.character(psd95_mean_T1T0$Standort)\nis.numeric(psd95_mean_T1T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(psd95_mean_T1T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(psd95_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel     T0     T1    T1_T0\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl>  <dbl>  <dbl>    <dbl>\n1 1     1        Controll F            67   38.9 0.0398 0.0193 -0.0205 \n2 2     1        Piano    F            76   34.6 0.0151 0.0116 -0.00357\n3 3     1        Piano    M            69   22.8 0.0237 0.0133 -0.0103 \n4 4     1        Controll F            75   40.6 0.0273 0.0169 -0.0104 \n5 5     1        Controll F            73   25.6 0.02   0.0302  0.0102 \n6 8     1        Controll F            67   32.7 0.0187 0.0293  0.0107 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\npsd95_median_T1T0 <- psd95_median_wide\npsd95_median_T1T0$T2 <- NULL\n\npsd95_median_T1T0 <- psd95_median_T1T0 %>%\n  filter(!is.na(T1), !is.na(T0)) %>%\n  mutate(`T1_T0` = T1 - T0)\n\npsd95_median_T1T0$CogTel <- as.numeric(psd95_median_T1T0$CogTel)\npsd95_median_T1T0$Standort <- as.character(psd95_median_T1T0$Standort)\nis.numeric(psd95_median_T1T0$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(psd95_median_T1T0$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(psd95_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel    T0    T1 T1_T0\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl> <dbl>\n1 1     1        Controll F            67   38.9     0     0     0\n2 2     1        Piano    F            76   34.6     0     0     0\n3 3     1        Piano    M            69   22.8     0     0     0\n4 4     1        Controll F            75   40.6     0     0     0\n5 5     1        Controll F            73   25.6     0     0     0\n6 8     1        Controll F            67   32.7     0     0     0\n```\n\n\n:::\n:::\n\n\n## Create a new column 'T2-T1'\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#BDNF\n##mean\nbdnf_mean_T2T1 <- bdnf_mean_wide\nbdnf_mean_T2T1$T0 <- NULL\n\nbdnf_mean_T2T1 <- bdnf_mean_T2T1 %>%\n  filter(!is.na(T2), !is.na(T1)) %>%\n  mutate(`T2_T1` = T2 - T1)\n\nbdnf_mean_T2T1$CogTel <- as.numeric(bdnf_mean_T2T1$CogTel)\nbdnf_mean_T2T1$Standort <- as.character(bdnf_mean_T2T1$Standort)\nis.numeric(bdnf_mean_T2T1$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(bdnf_mean_T2T1$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(bdnf_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n     ID Standort Gruppe   Sex   Age_start CogTel    T1    T2   T2_T1\n  <dbl> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1     2 0        Piano    F            76   34.6 0.06  0.084  0.024 \n2     4 0        Controll F            75   40.6 0.021 0.097  0.076 \n3     5 0        Controll F            73   25.6 0.041 0.049  0.008 \n4     9 0        Controll F            74   24.4 0.072 0.169  0.097 \n5    11 0        Piano    F            71   30.3 0.059 0.14   0.081 \n6    13 0        Controll F            65   42.4 0.089 0.077 -0.0120\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\nbdnf_median_T2T1 <- bdnf_median_wide\nbdnf_median_T2T1$T0 <- NULL\n\nbdnf_median_T2T1 <- bdnf_median_T2T1 %>%\n  filter(!is.na(T2), !is.na(T1)) %>%\n  mutate(`T2_T1` = T2 - T1)\n\nbdnf_median_T2T1$CogTel <- as.numeric(bdnf_median_T2T1$CogTel)\nbdnf_median_T2T1$Standort <- as.character(bdnf_median_T2T1$Standort)\nis.numeric(bdnf_median_T2T1$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(bdnf_median_T2T1$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(bdnf_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n     ID Standort Gruppe   Sex   Age_start CogTel    T1    T2 T2_T1\n  <dbl> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl> <dbl>\n1     2 0        Piano    F            76   34.6 0     0.085 0.085\n2     4 0        Controll F            75   40.6 0     0.08  0.08 \n3     5 0        Controll F            73   25.6 0.02  0.03  0.01 \n4     9 0        Controll F            74   24.4 0.045 0.175 0.13 \n5    11 0        Piano    F            71   30.3 0.015 0.085 0.07 \n6    13 0        Controll F            65   42.4 0     0.01  0.01 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#Tau\n##mean\ntau_mean_T2T1 <- tau_mean_wide\ntau_mean_T2T1$T0 <- NULL\n\ntau_mean_T2T1 <- tau_mean_T2T1 %>%\n  filter(!is.na(T2), !is.na(T1)) %>%\n  mutate(`T2_T1` = T2 - T1)\n\ntau_mean_T2T1$CogTel <- as.numeric(tau_mean_T2T1$CogTel)\ntau_mean_T2T1$Standort <- as.character(tau_mean_T2T1$Standort)\nis.numeric(tau_mean_T2T1$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(tau_mean_T2T1$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(tau_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel     T1     T2     T2_T1\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl>  <dbl>  <dbl>     <dbl>\n1 2     1        Piano    F            76   34.6 0.0725 0.0717 -0.000798\n2 4     1        Controll F            75   40.6 0.0440 0.0492  0.00521 \n3 5     1        Controll F            73   25.6 0.0979 0.0654 -0.0325  \n4 9     1        Controll F            74   24.4 0.0976 0.0888 -0.00881 \n5 11    1        Piano    F            71   30.3 0.127  0.0656 -0.0616  \n6 13    1        Controll F            65   42.4 0.0669 0.0288 -0.0381  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\ntau_median_T2T1 <- tau_median_wide\ntau_median_T2T1$T0 <- NULL\n\ntau_median_T2T1 <- tau_median_T2T1 %>%\n  filter(!is.na(T2), !is.na(T1)) %>%\n  mutate(`T2_T1` = T2 - T1)\n\ntau_median_T2T1$CogTel <- as.numeric(tau_median_T2T1$CogTel)\ntau_median_T2T1$Standort <- as.character(tau_median_T2T1$Standort)\nis.numeric(tau_median_T2T1$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(tau_median_T2T1$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(tau_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel    T1    T2   T2_T1\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1 2     1        Piano    F            76   34.6 0.02  0.02   0     \n2 4     1        Controll F            75   40.6 0.015 0.01  -0.005 \n3 5     1        Controll F            73   25.6 0.03  0.025 -0.0050\n4 9     1        Controll F            74   24.4 0.05  0.02  -0.03  \n5 11    1        Piano    F            71   30.3 0.065 0.015 -0.05  \n6 13    1        Controll F            65   42.4 0.03  0     -0.03  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#PSD95\n##mean\npsd95_mean_T2T1 <- psd95_mean_wide\npsd95_mean_T2T1$T0 <- NULL\n\npsd95_mean_T2T1 <- psd95_mean_T2T1 %>%\n  filter(!is.na(T2), !is.na(T1)) %>%\n  mutate(`T2_T1` = T2 - T1)\n\npsd95_mean_T2T1$CogTel <- as.numeric(psd95_mean_T2T1$CogTel)\npsd95_mean_T2T1$Standort <- as.character(psd95_mean_T2T1$Standort)\nis.numeric(psd95_mean_T2T1$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(psd95_mean_T2T1$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(psd95_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel      T1     T2    T2_T1\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl>   <dbl>  <dbl>    <dbl>\n1 2     1        Piano    F            76   34.6 0.0116  0.0445  0.0330 \n2 4     1        Controll F            75   40.6 0.0169  0.0441  0.0272 \n3 5     1        Controll F            73   25.6 0.0302  0.0178 -0.0124 \n4 9     1        Controll F            74   24.4 0.0316  0.0278 -0.00378\n5 11    1        Piano    F            71   30.3 0.00708 0.0273  0.0202 \n6 13    1        Controll F            65   42.4 0.0124  0.04    0.0276 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n##median\npsd95_median_T2T1 <- psd95_median_wide\npsd95_median_T2T1$T0 <- NULL\n\npsd95_median_T2T1 <- psd95_median_T2T1 %>%\n  filter(!is.na(T2), !is.na(T1)) %>%\n  mutate(`T2_T1` = T2 - T1)\n\npsd95_median_T2T1$CogTel <- as.numeric(psd95_median_T2T1$CogTel)\npsd95_median_T2T1$Standort <- as.character(psd95_median_T2T1$Standort)\nis.numeric(psd95_median_T2T1$CogTel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nis.character(psd95_median_T2T1$Standort)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhead(psd95_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  ID    Standort Gruppe   Sex   Age_start CogTel    T1    T2 T2_T1\n  <chr> <chr>    <chr>    <chr>     <dbl>  <dbl> <dbl> <dbl> <dbl>\n1 2     1        Piano    F            76   34.6     0  0     0   \n2 4     1        Controll F            75   40.6     0  0.02  0.02\n3 5     1        Controll F            73   25.6     0  0     0   \n4 9     1        Controll F            74   24.4     0  0     0   \n5 11    1        Piano    F            71   30.3     0  0     0   \n6 13    1        Controll F            65   42.4     0  0     0   \n```\n\n\n:::\n:::\n\n\n# Data analysis\n\n## LM: Regression analysis (Bivariate/multivariate)\n\n### BDNF\n\n#### T2-T0\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# lm mean\nlm_bdnf_mean_T2T0 <- lm(T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = bdnf_mean_T2T0)\n\nsummary(lm_bdnf_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = bdnf_mean_T2T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.081040 -0.024402  0.001351  0.018445  0.107158 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.1356324  0.0847778   1.600    0.113    \nStandort1   -0.0072086  0.0092864  -0.776    0.440    \nGruppePiano -0.0049959  0.0080204  -0.623    0.535    \nSexM         0.0021336  0.0086241   0.247    0.805    \nAge_start   -0.0004659  0.0010994  -0.424    0.673    \nCogTel      -0.0005863  0.0005925  -0.989    0.325    \nT0          -0.9889319  0.1221342  -8.097 2.94e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0382 on 88 degrees of freedom\nMultiple R-squared:  0.4567,\tAdjusted R-squared:  0.4196 \nF-statistic: 12.33 on 6 and 88 DF,  p-value: 5.002e-10\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_bdnf_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df   Sum Sq  Mean Sq F value    Pr(>F)    \nStandort   1 0.000011 0.000011  0.0076   0.93087    \nGruppe     1 0.000106 0.000106  0.0730   0.78770    \nSex        1 0.003131 0.003131  2.1454   0.14656    \nAge_start  1 0.000418 0.000418  0.2866   0.59373    \nCogTel     1 0.008604 0.008604  5.8954   0.01722 *  \nT0         1 0.095686 0.095686 65.5630 2.935e-12 ***\nResiduals 88 0.128432 0.001459                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(lm_bdnf_mean_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_bdnf_mean_T2T0) # call: lm(formula = T2_T0 ~ T0, data = bdnf_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-613.59\nT2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq     RSS     AIC\n- Sex        1  0.000089 0.12852 -615.53\n- Age_start  1  0.000262 0.12869 -615.40\n- Gruppe     1  0.000566 0.12900 -615.17\n- Standort   1  0.000879 0.12931 -614.94\n- CogTel     1  0.001429 0.12986 -614.54\n<none>                   0.12843 -613.59\n- T0         1  0.095686 0.22412 -562.70\n\nStep:  AIC=-615.53\nT2_T0 ~ Standort + Gruppe + Age_start + CogTel + T0\n\n            Df Sum of Sq     RSS     AIC\n- Age_start  1  0.000260 0.12878 -617.33\n- Gruppe     1  0.000569 0.12909 -617.11\n- Standort   1  0.000793 0.12932 -616.94\n- CogTel     1  0.001564 0.13009 -616.38\n<none>                   0.12852 -615.53\n- T0         1  0.097263 0.22578 -563.99\n\nStep:  AIC=-617.33\nT2_T0 ~ Standort + Gruppe + CogTel + T0\n\n           Df Sum of Sq     RSS     AIC\n- Gruppe    1  0.000486 0.12927 -618.98\n- Standort  1  0.000674 0.12945 -618.84\n- CogTel    1  0.001354 0.13014 -618.34\n<none>                  0.12878 -617.33\n- T0        1  0.098638 0.22742 -565.31\n\nStep:  AIC=-618.98\nT2_T0 ~ Standort + CogTel + T0\n\n           Df Sum of Sq     RSS     AIC\n- Standort  1  0.000612 0.12988 -620.53\n- CogTel    1  0.001142 0.13041 -620.14\n<none>                  0.12927 -618.98\n- T0        1  0.098770 0.22804 -567.05\n\nStep:  AIC=-620.53\nT2_T0 ~ CogTel + T0\n\n         Df Sum of Sq     RSS     AIC\n- CogTel  1  0.001300 0.13118 -621.58\n<none>                0.12988 -620.53\n- T0      1  0.098169 0.22805 -569.05\n\nStep:  AIC=-621.58\nT2_T0 ~ T0\n\n       Df Sum of Sq     RSS     AIC\n<none>              0.13118 -621.58\n- T0    1   0.10521 0.23639 -567.63\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ T0, data = bdnf_mean_T2T0)\n\nCoefficients:\n(Intercept)           T0  \n     0.0791      -1.0092  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# lm median\nlm_bdnf_median_T2T0 <- lm(T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = bdnf_median_T2T0)\n\nsummary(lm_bdnf_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = bdnf_median_T2T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.068254 -0.034727 -0.004697  0.014385  0.164933 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0317555  0.1025643   0.310    0.758    \nStandort1   -0.0116255  0.0112941  -1.029    0.306    \nGruppePiano -0.0053464  0.0097131  -0.550    0.583    \nSexM         0.0061892  0.0107670   0.575    0.567    \nAge_start    0.0004576  0.0013291   0.344    0.731    \nCogTel      -0.0002690  0.0007087  -0.380    0.705    \nT0          -1.0130485  0.1292319  -7.839 9.87e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0462 on 88 degrees of freedom\nMultiple R-squared:  0.4535,\tAdjusted R-squared:  0.4163 \nF-statistic: 12.17 on 6 and 88 DF,  p-value: 6.368e-10\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_bdnf_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df   Sum Sq  Mean Sq F value    Pr(>F)    \nStandort   1 0.001974 0.001974  0.9248  0.338841    \nGruppe     1 0.001186 0.001186  0.5555  0.458053    \nSex        1 0.019022 0.019022  8.9101  0.003671 ** \nAge_start  1 0.000000 0.000000  0.0002  0.987930    \nCogTel     1 0.002553 0.002553  1.1959  0.277132    \nT0         1 0.131189 0.131189 61.4499 9.868e-12 ***\nResiduals 88 0.187871 0.002135                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(lm_bdnf_median_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_bdnf_median_T2T0) # call: lm(formula = T2_T0 ~ T0, data = bdnf_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-577.46\nT2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq     RSS     AIC\n- Age_start  1  0.000253 0.18812 -579.33\n- CogTel     1  0.000308 0.18818 -579.30\n- Gruppe     1  0.000647 0.18852 -579.13\n- Sex        1  0.000705 0.18858 -579.10\n- Standort   1  0.002262 0.19013 -578.32\n<none>                   0.18787 -577.46\n- T0         1  0.131189 0.31906 -529.14\n\nStep:  AIC=-579.33\nT2_T0 ~ Standort + Gruppe + Sex + CogTel + T0\n\n           Df Sum of Sq     RSS     AIC\n- CogTel    1  0.000471 0.18859 -581.09\n- Sex       1  0.000722 0.18885 -580.97\n- Gruppe    1  0.000764 0.18889 -580.95\n- Standort  1  0.002532 0.19066 -580.06\n<none>                  0.18812 -579.33\n- T0        1  0.131046 0.31917 -531.11\n\nStep:  AIC=-581.09\nT2_T0 ~ Standort + Gruppe + Sex + T0\n\n           Df Sum of Sq     RSS     AIC\n- Gruppe    1  0.000602 0.18920 -582.79\n- Sex       1  0.000913 0.18951 -582.63\n- Standort  1  0.002868 0.19146 -581.66\n<none>                  0.18859 -581.09\n- T0        1  0.133019 0.32161 -532.39\n\nStep:  AIC=-582.79\nT2_T0 ~ Standort + Sex + T0\n\n           Df Sum of Sq     RSS     AIC\n- Sex       1  0.000874 0.19007 -584.35\n- Standort  1  0.002708 0.19190 -583.44\n<none>                  0.18920 -582.79\n- T0        1  0.133782 0.32298 -533.98\n\nStep:  AIC=-584.35\nT2_T0 ~ Standort + T0\n\n           Df Sum of Sq     RSS     AIC\n- Standort  1  0.002016 0.19209 -585.35\n<none>                  0.19007 -584.35\n- T0        1  0.151751 0.34182 -530.60\n\nStep:  AIC=-585.35\nT2_T0 ~ T0\n\n       Df Sum of Sq     RSS     AIC\n<none>              0.19209 -585.35\n- T0    1   0.15171 0.34380 -532.05\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ T0, data = bdnf_median_T2T0)\n\nCoefficients:\n(Intercept)           T0  \n    0.04732     -1.01259  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#mean\nbdnf_aic_mean_T2T0 <- lm(formula = T2_T0 ~ T0, data = bdnf_mean_T2T0)\nsummary(bdnf_aic_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ T0, data = bdnf_mean_T2T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.078512 -0.025191 -0.001027  0.018726  0.107507 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.079100   0.008699   9.093 1.70e-14 ***\nT0          -1.009192   0.116852  -8.636 1.56e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.03756 on 93 degrees of freedom\nMultiple R-squared:  0.4451,\tAdjusted R-squared:  0.4391 \nF-statistic: 74.59 on 1 and 93 DF,  p-value: 1.563e-13\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(bdnf_aic_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df  Sum Sq  Mean Sq F value    Pr(>F)    \nT0         1 0.10521 0.105210  74.589 1.563e-13 ***\nResiduals 93 0.13118 0.001411                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(bdnf_aic_mean_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\nbdnf_aic_median_T2T0 <- lm(formula = T2_T0 ~ T0, data = bdnf_median_T2T0)\nsummary(bdnf_aic_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ T0, data = bdnf_median_T2T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.047319 -0.036437 -0.007319  0.018027  0.163122 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.04732    0.00613   7.719 1.30e-11 ***\nT0          -1.01259    0.11815  -8.570 2.15e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04545 on 93 degrees of freedom\nMultiple R-squared:  0.4413,\tAdjusted R-squared:  0.4353 \nF-statistic: 73.45 on 1 and 93 DF,  p-value: 2.153e-13\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(bdnf_aic_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df  Sum Sq  Mean Sq F value    Pr(>F)    \nT0         1 0.15171 0.151710  73.452 2.153e-13 ***\nResiduals 93 0.19209 0.002065                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(bdnf_aic_median_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n:::\n\n\n#### T1 - T0\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# mean\nlm_bdnf_mean_T1T0 <- lm(T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = bdnf_mean_T1T0)\n\nsummary(lm_bdnf_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = bdnf_mean_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.063517 -0.018523 -0.000895  0.019733  0.092546 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.1080356  0.0586896   1.841   0.0683 .  \nStandort1    0.0067587  0.0058672   1.152   0.2518    \nGruppePiano -0.0107673  0.0054122  -1.989   0.0491 *  \nSexM        -0.0013455  0.0057653  -0.233   0.8159    \nAge_start   -0.0005596  0.0007764  -0.721   0.4725    \nCogTel      -0.0002027  0.0003931  -0.516   0.6071    \nT0          -0.9850323  0.0831609 -11.845   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02912 on 112 degrees of freedom\nMultiple R-squared:  0.5818,\tAdjusted R-squared:  0.5594 \nF-statistic: 25.97 on 6 and 112 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_bdnf_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df   Sum Sq  Mean Sq  F value  Pr(>F)    \nStandort    1 0.005113 0.005113   6.0288 0.01561 *  \nGruppe      1 0.001184 0.001184   1.3956 0.23996    \nSex         1 0.001195 0.001195   1.4086 0.23780    \nAge_start   1 0.002432 0.002432   2.8683 0.09312 .  \nCogTel      1 0.003249 0.003249   3.8307 0.05281 .  \nT0          1 0.118982 0.118982 140.3015 < 2e-16 ***\nResiduals 112 0.094981 0.000848                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_bdnf_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-834.85\nT1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Sex        1  0.000046 0.095027 -836.79\n- CogTel     1  0.000225 0.095207 -836.57\n- Age_start  1  0.000441 0.095422 -836.30\n- Standort   1  0.001125 0.096107 -835.45\n<none>                   0.094981 -834.85\n- Gruppe     1  0.003356 0.098338 -832.72\n- T0         1  0.118982 0.213963 -740.21\n\nStep:  AIC=-836.79\nT1_T0 ~ Standort + Gruppe + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- CogTel     1  0.000205 0.095233 -838.54\n- Age_start  1  0.000446 0.095474 -838.24\n- Standort   1  0.001091 0.096119 -837.43\n<none>                   0.095027 -836.79\n- Gruppe     1  0.003408 0.098436 -834.60\n- T0         1  0.119764 0.214791 -741.75\n\nStep:  AIC=-838.54\nT1_T0 ~ Standort + Gruppe + Age_start + T0\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1  0.000333 0.095566 -840.12\n- Standort   1  0.001047 0.096279 -839.24\n<none>                   0.095233 -838.54\n- Gruppe     1  0.003248 0.098481 -836.54\n- T0         1  0.123303 0.218536 -741.69\n\nStep:  AIC=-840.12\nT1_T0 ~ Standort + Gruppe + T0\n\n           Df Sum of Sq      RSS     AIC\n- Standort  1  0.001175 0.096740 -840.67\n<none>                  0.095566 -840.12\n- Gruppe    1  0.003155 0.098720 -838.26\n- T0        1  0.125274 0.220839 -742.44\n\nStep:  AIC=-840.67\nT1_T0 ~ Gruppe + T0\n\n         Df Sum of Sq     RSS     AIC\n<none>                0.09674 -840.67\n- Gruppe  1  0.003293 0.10003 -838.68\n- T0      1  0.129069 0.22581 -741.80\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Gruppe + T0, data = bdnf_mean_T1T0)\n\nCoefficients:\n(Intercept)  GruppePiano           T0  \n    0.06732     -0.01054     -1.00255  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# median\nlm_bdnf_median_T1T0 <- lm(T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = bdnf_median_T1T0)\n\nsummary(lm_bdnf_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = bdnf_median_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.043895 -0.022967 -0.004209  0.016705  0.080273 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0031559  0.0586385   0.054    0.957    \nStandort1    0.0030724  0.0059084   0.520    0.604    \nGruppePiano -0.0076696  0.0054012  -1.420    0.158    \nSexM         0.0002724  0.0058718   0.046    0.963    \nAge_start    0.0000714  0.0007742   0.092    0.927    \nCogTel       0.0006949  0.0003906   1.779    0.078 .  \nT0          -0.9676467  0.0753511 -12.842   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02908 on 112 degrees of freedom\nMultiple R-squared:  0.6302,\tAdjusted R-squared:  0.6104 \nF-statistic: 31.81 on 6 and 112 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_bdnf_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df   Sum Sq  Mean Sq  F value    Pr(>F)    \nStandort    1 0.011604 0.011604  13.7257 0.0003303 ***\nGruppe      1 0.001096 0.001096   1.2966 0.2572567    \nSex         1 0.006728 0.006728   7.9580 0.0056649 ** \nAge_start   1 0.001816 0.001816   2.1478 0.1455775    \nCogTel      1 0.000673 0.000673   0.7964 0.3740938    \nT0          1 0.139422 0.139422 164.9127 < 2.2e-16 ***\nResiduals 112 0.094688 0.000845                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_bdnf_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-835.22\nT1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Sex        1  0.000002 0.094690 -837.22\n- Age_start  1  0.000007 0.094695 -837.21\n- Standort   1  0.000229 0.094917 -836.93\n<none>                   0.094688 -835.22\n- Gruppe     1  0.001705 0.096393 -835.10\n- CogTel     1  0.002676 0.097364 -833.90\n- T0         1  0.139422 0.234110 -729.50\n\nStep:  AIC=-837.22\nT1_T0 ~ Standort + Gruppe + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1  0.000007 0.094697 -839.21\n- Standort   1  0.000258 0.094948 -838.89\n<none>                   0.094690 -837.22\n- Gruppe     1  0.001704 0.096394 -837.09\n- CogTel     1  0.002693 0.097383 -835.88\n- T0         1  0.146851 0.241541 -727.78\n\nStep:  AIC=-839.21\nT1_T0 ~ Standort + Gruppe + CogTel + T0\n\n           Df Sum of Sq      RSS     AIC\n- Standort  1  0.000253 0.094951 -840.89\n<none>                  0.094697 -839.21\n- Gruppe    1  0.001733 0.096431 -839.05\n- CogTel    1  0.002778 0.097476 -837.77\n- T0        1  0.148075 0.242772 -729.18\n\nStep:  AIC=-840.89\nT1_T0 ~ Gruppe + CogTel + T0\n\n         Df Sum of Sq      RSS     AIC\n<none>                0.094951 -840.89\n- Gruppe  1  0.001770 0.096721 -840.69\n- CogTel  1  0.002925 0.097875 -839.28\n- T0      1  0.158869 0.253820 -725.88\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Gruppe + CogTel + T0, data = bdnf_median_T1T0)\n\nCoefficients:\n(Intercept)  GruppePiano       CogTel           T0  \n  0.0103891   -0.0077764    0.0007001   -0.9767415  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#mean\nbdnf_aic_mean_T1T0 <- lm(formula = T1_T0 ~ Gruppe + T0, data = bdnf_mean_T1T0)\nsummary(bdnf_aic_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Gruppe + T0, data = bdnf_mean_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.067098 -0.018574 -0.001713  0.019920  0.089938 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.067318   0.006758   9.962   <2e-16 ***\nGruppePiano -0.010539   0.005304  -1.987   0.0493 *  \nT0          -1.002554   0.080588 -12.440   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02888 on 116 degrees of freedom\nMultiple R-squared:  0.5741,\tAdjusted R-squared:  0.5667 \nF-statistic: 78.18 on 2 and 116 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(bdnf_aic_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df   Sum Sq  Mean Sq  F value Pr(>F)    \nGruppe      1 0.001326 0.001326   1.5903 0.2098    \nT0          1 0.129069 0.129069 154.7641 <2e-16 ***\nResiduals 116 0.096740 0.000834                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(bdnf_aic_mean_T1T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\nbdnf_aic_median_T1T0 <- lm(formula = T1_T0 ~ Gruppe + CogTel + T0, data = bdnf_median_T1T0)\nsummary(bdnf_aic_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Gruppe + CogTel + T0, data = bdnf_median_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.042987 -0.022583 -0.004844  0.017251  0.078652 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0103891  0.0128888   0.806   0.4219    \nGruppePiano -0.0077764  0.0053107  -1.464   0.1458    \nCogTel       0.0007001  0.0003720   1.882   0.0623 .  \nT0          -0.9767415  0.0704142 -13.871   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02873 on 115 degrees of freedom\nMultiple R-squared:  0.6291,\tAdjusted R-squared:  0.6195 \nF-statistic: 65.03 on 3 and 115 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(bdnf_aic_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df   Sum Sq  Mean Sq  F value Pr(>F)    \nGruppe      1 0.001307 0.001307   1.5830 0.2109    \nCogTel      1 0.000901 0.000901   1.0912 0.2984    \nT0          1 0.158869 0.158869 192.4150 <2e-16 ***\nResiduals 115 0.094951 0.000826                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(bdnf_aic_median_T1T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n:::\n\n\n#### T2 - T1\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# with T1\n# mean\nlm_bdnf_mean_T2T1 <- lm(T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1, \n                  data = bdnf_mean_T2T1)\n\nsummary(lm_bdnf_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T1, data = bdnf_mean_T2T1)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.08148 -0.02405  0.00025  0.01768  0.10638 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.1377881  0.0871777   1.581    0.118    \nStandort1   -0.0088721  0.0095897  -0.925    0.357    \nGruppePiano -0.0068045  0.0084914  -0.801    0.425    \nSexM         0.0041531  0.0087928   0.472    0.638    \nAge_start   -0.0004293  0.0011224  -0.382    0.703    \nCogTel      -0.0006246  0.0005956  -1.049    0.297    \nT1          -1.0144903  0.1464073  -6.929 7.65e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.03857 on 85 degrees of freedom\nMultiple R-squared:  0.394,\tAdjusted R-squared:  0.3513 \nF-statistic: 9.212 on 6 and 85 DF,  p-value: 9.15e-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_bdnf_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df   Sum Sq  Mean Sq F value    Pr(>F)    \nStandort   1 0.004235 0.004235  2.8468   0.09522 .  \nGruppe     1 0.001767 0.001767  1.1879   0.27883    \nSex        1 0.001834 0.001834  1.2326   0.27004    \nAge_start  1 0.000037 0.000037  0.0249   0.87504    \nCogTel     1 0.002926 0.002926  1.9670   0.16441    \nT1         1 0.071429 0.071429 48.0143 7.646e-10 ***\nResiduals 85 0.126451 0.001488                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_bdnf_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-592.25\nT2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1\n\n            Df Sum of Sq     RSS     AIC\n- Age_start  1  0.000218 0.12667 -594.09\n- Sex        1  0.000332 0.12678 -594.01\n- Gruppe     1  0.000955 0.12741 -593.56\n- Standort   1  0.001273 0.12773 -593.33\n- CogTel     1  0.001636 0.12809 -593.07\n<none>                   0.12645 -592.25\n- T1         1  0.071429 0.19788 -553.05\n\nStep:  AIC=-594.09\nT2_T1 ~ Standort + Gruppe + Sex + CogTel + T1\n\n           Df Sum of Sq     RSS     AIC\n- Sex       1  0.000337 0.12701 -595.85\n- Gruppe    1  0.000864 0.12753 -595.47\n- Standort  1  0.001142 0.12781 -595.27\n- CogTel    1  0.001457 0.12813 -595.04\n<none>                  0.12667 -594.09\n- T1        1  0.071519 0.19819 -554.91\n\nStep:  AIC=-595.85\nT2_T1 ~ Standort + Gruppe + CogTel + T1\n\n           Df Sum of Sq     RSS     AIC\n- Standort  1  0.000839 0.12784 -597.24\n- Gruppe    1  0.000901 0.12791 -597.20\n- CogTel    1  0.001734 0.12874 -596.60\n<none>                  0.12701 -595.85\n- T1        1  0.072326 0.19933 -556.38\n\nStep:  AIC=-597.24\nT2_T1 ~ Gruppe + CogTel + T1\n\n         Df Sum of Sq     RSS     AIC\n- Gruppe  1  0.000844 0.12869 -598.64\n- CogTel  1  0.001881 0.12973 -597.90\n<none>                0.12784 -597.24\n- T1      1  0.074852 0.20270 -556.84\n\nStep:  AIC=-598.64\nT2_T1 ~ CogTel + T1\n\n         Df Sum of Sq     RSS     AIC\n- CogTel  1  0.001533 0.13022 -599.55\n<none>                0.12869 -598.64\n- T1      1  0.075199 0.20389 -558.30\n\nStep:  AIC=-599.55\nT2_T1 ~ T1\n\n       Df Sum of Sq     RSS     AIC\n<none>              0.13022 -599.55\n- T1    1  0.078459 0.20868 -558.16\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ T1, data = bdnf_mean_T2T1)\n\nCoefficients:\n(Intercept)           T1  \n    0.08038     -1.02129  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# median\n\nlm_bdnf_median_T2T1 <- lm(T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1, \n                  data = bdnf_median_T2T1)\n\nsummary(lm_bdnf_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T1, data = bdnf_median_T2T1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.071063 -0.033584 -0.006196  0.012862  0.164566 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0266820  0.1043906   0.256    0.799    \nStandort1   -0.0138619  0.0114494  -1.211    0.229    \nGruppePiano -0.0060132  0.0100621  -0.598    0.552    \nSexM         0.0068137  0.0105552   0.646    0.520    \nAge_start    0.0005582  0.0013497   0.414    0.680    \nCogTel      -0.0002568  0.0007468  -0.344    0.732    \nT1          -1.0357421  0.1810560  -5.721 1.55e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04636 on 85 degrees of freedom\nMultiple R-squared:  0.3283,\tAdjusted R-squared:  0.2809 \nF-statistic: 6.925 on 6 and 85 DF,  p-value: 5.172e-06\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_bdnf_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df   Sum Sq  Mean Sq F value   Pr(>F)    \nStandort   1 0.004636 0.004636  2.1575  0.14557    \nGruppe     1 0.000905 0.000905  0.4212  0.51809    \nSex        1 0.003068 0.003068  1.4279  0.23543    \nAge_start  1 0.001000 0.001000  0.4654  0.49698    \nCogTel     1 0.009349 0.009349  4.3508  0.03999 *  \nT1         1 0.070319 0.070319 32.7248 1.55e-07 ***\nResiduals 85 0.182648 0.002149                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_bdnf_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-558.42\nT2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1\n\n            Df Sum of Sq     RSS     AIC\n- CogTel     1  0.000254 0.18290 -560.29\n- Age_start  1  0.000368 0.18302 -560.24\n- Gruppe     1  0.000767 0.18341 -560.04\n- Sex        1  0.000895 0.18354 -559.97\n- Standort   1  0.003150 0.18580 -558.85\n<none>                   0.18265 -558.42\n- T1         1  0.070319 0.25297 -530.46\n\nStep:  AIC=-560.29\nT2_T1 ~ Standort + Gruppe + Sex + Age_start + T1\n\n            Df Sum of Sq     RSS     AIC\n- Age_start  1  0.000535 0.18344 -562.03\n- Gruppe     1  0.000657 0.18356 -561.96\n- Sex        1  0.001062 0.18396 -561.76\n- Standort   1  0.003289 0.18619 -560.66\n<none>                   0.18290 -560.29\n- T1         1  0.079414 0.26232 -529.12\n\nStep:  AIC=-562.03\nT2_T1 ~ Standort + Gruppe + Sex + T1\n\n           Df Sum of Sq     RSS     AIC\n- Gruppe    1  0.000770 0.18421 -563.64\n- Sex       1  0.001098 0.18454 -563.48\n- Standort  1  0.003895 0.18733 -562.09\n<none>                  0.18344 -562.03\n- T1        1  0.079878 0.26332 -530.77\n\nStep:  AIC=-563.64\nT2_T1 ~ Standort + Sex + T1\n\n           Df Sum of Sq     RSS     AIC\n- Sex       1  0.001112 0.18532 -565.09\n- Standort  1  0.003715 0.18792 -563.80\n<none>                  0.18421 -563.64\n- T1        1  0.079985 0.26419 -532.46\n\nStep:  AIC=-565.09\nT2_T1 ~ Standort + T1\n\n           Df Sum of Sq     RSS     AIC\n- Standort  1  0.002735 0.18805 -565.74\n<none>                  0.18532 -565.09\n- T1        1  0.081970 0.26729 -533.39\n\nStep:  AIC=-565.74\nT2_T1 ~ T1\n\n       Df Sum of Sq     RSS     AIC\n<none>              0.18805 -565.74\n- T1    1  0.083871 0.27192 -533.81\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ T1, data = bdnf_median_T2T1)\n\nCoefficients:\n(Intercept)           T1  \n    0.04861     -1.05553  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#mean\nbdnf_aic_mean_T2T1 <- lm(formula = T2_T1 ~ T1, data = bdnf_mean_T2T1)\nsummary(bdnf_aic_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ T1, data = bdnf_mean_T2T1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.079380 -0.025183 -0.000528  0.017972  0.106684 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.08038    0.00975   8.244 1.28e-12 ***\nT1          -1.02129    0.13869  -7.364 8.18e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.03804 on 90 degrees of freedom\nMultiple R-squared:  0.376,\tAdjusted R-squared:  0.369 \nF-statistic: 54.23 on 1 and 90 DF,  p-value: 8.176e-11\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(bdnf_aic_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df   Sum Sq  Mean Sq F value    Pr(>F)    \nT1         1 0.078459 0.078459  54.225 8.176e-11 ***\nResiduals 90 0.130221 0.001447                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(bdnf_aic_mean_T2T1)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\nbdnf_aic_median_T2T1 <- lm(formula = T2_T1 ~ T1, data = bdnf_median_T2T1)\nsummary(bdnf_aic_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ T1, data = bdnf_median_T2T1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.048613 -0.036392 -0.007504  0.015760  0.161387 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.048613   0.007125   6.823 1.00e-09 ***\nT1          -1.055525   0.166603  -6.336 9.15e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.04571 on 90 degrees of freedom\nMultiple R-squared:  0.3084,\tAdjusted R-squared:  0.3008 \nF-statistic: 40.14 on 1 and 90 DF,  p-value: 9.152e-09\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(bdnf_aic_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df   Sum Sq  Mean Sq F value    Pr(>F)    \nT1         1 0.083871 0.083871   40.14 9.152e-09 ***\nResiduals 90 0.188054 0.002089                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(bdnf_aic_median_T2T1)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n:::\n\n\n#### Plot models\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#?termplot\n\nlibrary(visreg)\n\n#T2-T0\nvisreg(bdnf_aic_mean_T2T0, type=\"conditional\", gg = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: ggplot2\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(bdnf_aic_median_T2T0, gg = TRUE)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#T1-T0\nvisreg(bdnf_aic_mean_T1T0, \"Gruppe\", gg = TRUE)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-14-3.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(bdnf_aic_median_T1T0, \"CogTel\", by = \"Gruppe\", gg = TRUE)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-14-4.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#T2-T1\nvisreg(bdnf_aic_mean_T2T1, gg = TRUE)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-14-5.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(bdnf_aic_median_T2T1, gg = TRUE)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-14-6.png){width=672}\n:::\n:::\n\n\n### Tau\n\n#### T2-T0\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# lm mean\nlm_tau_mean_T2T0 <- lm(T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = tau_mean_T2T0)\n\nsummary(lm_tau_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = tau_mean_T2T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.040343 -0.011086 -0.003595  0.009870  0.048054 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  9.765e-02  4.341e-02   2.249    0.027 *  \nStandort2   -1.731e-04  4.726e-03  -0.037    0.971    \nGruppePiano  7.579e-05  4.073e-03   0.019    0.985    \nSexM         1.686e-05  4.408e-03   0.004    0.997    \nAge_start   -5.018e-04  5.653e-04  -0.888    0.377    \nCogTel      -1.596e-04  2.935e-04  -0.544    0.588    \nT0          -7.493e-01  1.029e-01  -7.284 1.31e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01941 on 88 degrees of freedom\nMultiple R-squared:  0.3971,\tAdjusted R-squared:  0.356 \nF-statistic: 9.662 on 6 and 88 DF,  p-value: 3.729e-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_tau_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df   Sum Sq   Mean Sq F value    Pr(>F)    \nStandort   1 0.000044 0.0000437  0.1161   0.73414    \nGruppe     1 0.000071 0.0000707  0.1877   0.66589    \nSex        1 0.000326 0.0003258  0.8647   0.35498    \nAge_start  1 0.001319 0.0013193  3.5011   0.06465 .  \nCogTel     1 0.000091 0.0000911  0.2419   0.62408    \nT0         1 0.019994 0.0199942 53.0599 1.308e-10 ***\nResiduals 88 0.033160 0.0003768                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(lm_tau_mean_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_tau_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-742.23\nT2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Sex        1 0.0000000 0.033160 -744.23\n- Gruppe     1 0.0000001 0.033161 -744.23\n- Standort   1 0.0000005 0.033161 -744.22\n- CogTel     1 0.0001114 0.033272 -743.91\n- Age_start  1 0.0002969 0.033457 -743.38\n<none>                   0.033160 -742.23\n- T0         1 0.0199942 0.053155 -699.40\n\nStep:  AIC=-744.23\nT2_T0 ~ Standort + Gruppe + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Gruppe     1 0.0000001 0.033161 -746.23\n- Standort   1 0.0000005 0.033161 -746.22\n- CogTel     1 0.0001158 0.033276 -745.89\n- Age_start  1 0.0002969 0.033457 -745.38\n<none>                   0.033160 -744.23\n- T0         1 0.0202774 0.053438 -700.90\n\nStep:  AIC=-746.23\nT2_T0 ~ Standort + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Standort   1 0.0000006 0.033161 -748.22\n- CogTel     1 0.0001203 0.033281 -747.88\n- Age_start  1 0.0003036 0.033464 -747.36\n<none>                   0.033161 -746.23\n- T0         1 0.0202841 0.053445 -702.88\n\nStep:  AIC=-748.22\nT2_T0 ~ Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- CogTel     1 0.0001215 0.033283 -749.88\n- Age_start  1 0.0003069 0.033468 -749.35\n<none>                   0.033161 -748.22\n- T0         1 0.0202842 0.053445 -704.88\n\nStep:  AIC=-749.88\nT2_T0 ~ Age_start + T0\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1 0.0002382 0.033521 -751.20\n<none>                   0.033283 -749.88\n- T0         1 0.0203456 0.053628 -706.56\n\nStep:  AIC=-751.2\nT2_T0 ~ T0\n\n       Df Sum of Sq      RSS     AIC\n<none>              0.033521 -751.20\n- T0    1  0.021485 0.055005 -706.15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ T0, data = tau_mean_T2T0)\n\nCoefficients:\n(Intercept)           T0  \n    0.05836     -0.76245  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# lm median\nlm_tau_median_T2T0 <- lm(T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = tau_median_T2T0)\n\nsummary(lm_tau_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = tau_median_T2T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.028841 -0.011416 -0.002112  0.007742  0.037856 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.782e-02  3.184e-02   1.188    0.238    \nStandort2   -3.984e-03  3.450e-03  -1.155    0.251    \nGruppePiano  3.560e-03  3.095e-03   1.150    0.253    \nSexM        -7.233e-05  3.238e-03  -0.022    0.982    \nAge_start   -1.830e-04  4.087e-04  -0.448    0.656    \nCogTel      -3.182e-04  2.165e-04  -1.470    0.145    \nT0          -8.215e-01  1.212e-01  -6.778 1.33e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01418 on 88 degrees of freedom\nMultiple R-squared:  0.4057,\tAdjusted R-squared:  0.3652 \nF-statistic: 10.01 on 6 and 88 DF,  p-value: 2.068e-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_tau_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df    Sum Sq   Mean Sq F value    Pr(>F)    \nStandort   1 0.0002334 0.0002334  1.1614  0.284125    \nGruppe     1 0.0022326 0.0022326 11.1108  0.001257 ** \nSex        1 0.0002827 0.0002827  1.4072  0.238722    \nAge_start  1 0.0000360 0.0000360  0.1791  0.673180    \nCogTel     1 0.0000549 0.0000549  0.2732  0.602485    \nT0         1 0.0092317 0.0092317 45.9434 1.333e-09 ***\nResiduals 88 0.0176824 0.0002009                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(lm_tau_median_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-15-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_tau_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-801.96\nT2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Sex        1 0.0000001 0.017683 -803.96\n- Age_start  1 0.0000403 0.017723 -803.74\n- Gruppe     1 0.0002658 0.017948 -802.54\n- Standort   1 0.0002680 0.017950 -802.53\n<none>                   0.017682 -801.96\n- CogTel     1 0.0004343 0.018117 -801.66\n- T0         1 0.0092317 0.026914 -764.05\n\nStep:  AIC=-803.96\nT2_T0 ~ Standort + Gruppe + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1 0.0000402 0.017723 -805.74\n- Gruppe     1 0.0002684 0.017951 -804.53\n- Standort   1 0.0003176 0.018000 -804.27\n<none>                   0.017683 -803.96\n- CogTel     1 0.0004508 0.018133 -803.57\n- T0         1 0.0094647 0.027147 -765.23\n\nStep:  AIC=-805.74\nT2_T0 ~ Standort + Gruppe + CogTel + T0\n\n           Df Sum of Sq      RSS     AIC\n- Standort  1 0.0002893 0.018012 -806.21\n- Gruppe    1 0.0002995 0.018022 -806.15\n<none>                  0.017723 -805.74\n- CogTel    1 0.0004129 0.018136 -805.56\n- T0        1 0.0094859 0.027209 -767.02\n\nStep:  AIC=-806.21\nT2_T0 ~ Gruppe + CogTel + T0\n\n         Df Sum of Sq      RSS     AIC\n- Gruppe  1 0.0003342 0.018346 -806.46\n<none>                0.018012 -806.21\n- CogTel  1 0.0004691 0.018481 -805.76\n- T0      1 0.0093380 0.027350 -768.53\n\nStep:  AIC=-806.46\nT2_T0 ~ CogTel + T0\n\n         Df Sum of Sq      RSS     AIC\n<none>                0.018346 -806.46\n- CogTel  1 0.0006297 0.018976 -805.25\n- T0      1 0.0111320 0.029478 -763.41\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ CogTel + T0, data = tau_median_T2T0)\n\nCoefficients:\n(Intercept)       CogTel           T0  \n  0.0260669   -0.0003589   -0.8559741  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# mean\ntau_aic_mean_T2T0 <- lm(formula = T2_T0 ~ T0, data = tau_mean_T2T0)\nsummary(tau_aic_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ T0, data = tau_mean_T2T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.041872 -0.011810 -0.003094  0.011112  0.048302 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.058358   0.007655   7.623 2.06e-11 ***\nT0          -0.762452   0.098756  -7.721 1.29e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01899 on 93 degrees of freedom\nMultiple R-squared:  0.3906,\tAdjusted R-squared:  0.384 \nF-statistic: 59.61 on 1 and 93 DF,  p-value: 1.294e-11\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(tau_aic_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df   Sum Sq   Mean Sq F value    Pr(>F)    \nT0         1 0.021485 0.0214846  59.607 1.294e-11 ***\nResiduals 93 0.033521 0.0003604                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(tau_aic_mean_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\ntau_aic_median_T2T0 <- lm(formula = T2_T0 ~ CogTel + T0, data = tau_median_T2T0)\nsummary(tau_aic_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ CogTel + T0, data = tau_median_T2T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.023535 -0.011171 -0.000913  0.007733  0.039125 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0260669  0.0071211   3.660  0.00042 ***\nCogTel      -0.0003589  0.0002020  -1.777  0.07886 .  \nT0          -0.8559741  0.1145654  -7.471 4.46e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01412 on 92 degrees of freedom\nMultiple R-squared:  0.3834,\tAdjusted R-squared:   0.37 \nF-statistic:  28.6 on 2 and 92 DF,  p-value: 2.189e-10\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(tau_aic_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df    Sum Sq   Mean Sq F value    Pr(>F)    \nCogTel     1 0.0002755 0.0002755  1.3817    0.2428    \nT0         1 0.0111320 0.0111320 55.8232 4.458e-11 ***\nResiduals 92 0.0183462 0.0001994                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(tau_aic_median_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-16-2.png){width=672}\n:::\n:::\n\n\n#### T1 - T0\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# mean\nlm_tau_mean_T1T0 <- lm(T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = tau_mean_T1T0)\n\nsummary(lm_tau_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = tau_mean_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.047288 -0.013601 -0.002155  0.010164  0.062169 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.849e-03  3.909e-02   0.098    0.922    \nStandort2   -1.279e-03  3.867e-03  -0.331    0.741    \nGruppePiano -2.775e-03  3.592e-03  -0.773    0.441    \nSexM        -4.859e-03  3.821e-03  -1.272    0.206    \nAge_start    7.575e-04  5.175e-04   1.464    0.146    \nCogTel       6.373e-05  2.571e-04   0.248    0.805    \nT0          -7.066e-01  9.157e-02  -7.717 4.95e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01942 on 114 degrees of freedom\nMultiple R-squared:  0.3568,\tAdjusted R-squared:  0.3229 \nF-statistic: 10.54 on 6 and 114 DF,  p-value: 2.761e-09\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_tau_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df   Sum Sq   Mean Sq F value    Pr(>F)    \nStandort    1 0.000438 0.0004380  1.1614    0.2835    \nGruppe      1 0.000794 0.0007944  2.1063    0.1494    \nSex         1 0.000031 0.0000305  0.0809    0.7766    \nAge_start   1 0.000091 0.0000906  0.2402    0.6250    \nCogTel      1 0.000039 0.0000391  0.1036    0.7481    \nT0          1 0.022459 0.0224587 59.5449 4.955e-12 ***\nResiduals 114 0.042998 0.0003772                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_tau_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-947.03\nT1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- CogTel     1 0.0000232 0.043021 -948.97\n- Standort   1 0.0000413 0.043039 -948.91\n- Gruppe     1 0.0002251 0.043223 -948.40\n- Sex        1 0.0006101 0.043608 -947.33\n<none>                   0.042998 -947.03\n- Age_start  1 0.0008081 0.043806 -946.78\n- T0         1 0.0224587 0.065456 -898.18\n\nStep:  AIC=-948.97\nT1_T0 ~ Standort + Gruppe + Sex + Age_start + T0\n\n            Df Sum of Sq      RSS     AIC\n- Standort   1 0.0000349 0.043056 -950.87\n- Gruppe     1 0.0002492 0.043270 -950.27\n- Sex        1 0.0006697 0.043691 -949.10\n<none>                   0.043021 -948.97\n- Age_start  1 0.0007869 0.043808 -948.77\n- T0         1 0.0224747 0.065496 -900.11\n\nStep:  AIC=-950.87\nT1_T0 ~ Gruppe + Sex + Age_start + T0\n\n            Df Sum of Sq      RSS     AIC\n- Gruppe     1 0.0002385 0.043294 -952.20\n<none>                   0.043056 -950.87\n- Sex        1 0.0008294 0.043885 -950.56\n- Age_start  1 0.0008381 0.043894 -950.53\n- T0         1 0.0227736 0.065829 -901.49\n\nStep:  AIC=-952.2\nT1_T0 ~ Sex + Age_start + T0\n\n            Df Sum of Sq      RSS     AIC\n<none>                   0.043294 -952.20\n- Age_start  1 0.0008974 0.044192 -951.72\n- Sex        1 0.0008974 0.044192 -951.72\n- T0         1 0.0232147 0.066509 -902.25\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Sex + Age_start + T0, data = tau_mean_T1T0)\n\nCoefficients:\n(Intercept)         SexM    Age_start           T0  \n  0.0034915   -0.0055495    0.0007722   -0.7141952  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# median\n\nlm_tau_median_T1T0 <- lm(T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = tau_median_T1T0)\n\nsummary(lm_tau_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = tau_median_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.024326 -0.009168 -0.002287  0.007000  0.090911 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  2.489e-02  3.270e-02   0.761   0.4481    \nStandort2   -7.766e-03  3.188e-03  -2.436   0.0164 *  \nGruppePiano -8.184e-04  3.022e-03  -0.271   0.7870    \nSexM        -2.782e-03  3.159e-03  -0.881   0.3803    \nAge_start   -5.619e-05  4.254e-04  -0.132   0.8952    \nCogTel       2.067e-04  2.156e-04   0.958   0.3398    \nT0          -9.519e-01  1.189e-01  -8.008  1.1e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01606 on 114 degrees of freedom\nMultiple R-squared:  0.3978,\tAdjusted R-squared:  0.3662 \nF-statistic: 12.55 on 6 and 114 DF,  p-value: 7.921e-11\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_tau_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df    Sum Sq   Mean Sq F value    Pr(>F)    \nStandort    1 0.0011712 0.0011712  4.5406   0.03525 *  \nGruppe      1 0.0002752 0.0002752  1.0670   0.30382    \nSex         1 0.0000137 0.0000137  0.0532   0.81799    \nAge_start   1 0.0000183 0.0000183  0.0709   0.79045    \nCogTel      1 0.0014081 0.0014081  5.4593   0.02121 *  \nT0          1 0.0165410 0.0165410 64.1283 1.096e-12 ***\nResiduals 114 0.0294047 0.0002579                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_tau_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-993.01\nT1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1 0.0000045 0.029409 -994.99\n- Gruppe     1 0.0000189 0.029424 -994.93\n- Sex        1 0.0002001 0.029605 -994.19\n- CogTel     1 0.0002370 0.029642 -994.04\n<none>                   0.029405 -993.01\n- Standort   1 0.0015302 0.030935 -988.87\n- T0         1 0.0165410 0.045946 -941.01\n\nStep:  AIC=-994.99\nT1_T0 ~ Standort + Gruppe + Sex + CogTel + T0\n\n           Df Sum of Sq      RSS     AIC\n- Gruppe    1 0.0000174 0.029427 -996.92\n- Sex       1 0.0001995 0.029609 -996.17\n- CogTel    1 0.0002653 0.029675 -995.90\n<none>                  0.029409 -994.99\n- Standort  1 0.0015268 0.030936 -990.87\n- T0        1 0.0165532 0.045962 -942.96\n\nStep:  AIC=-996.92\nT1_T0 ~ Standort + Sex + CogTel + T0\n\n           Df Sum of Sq      RSS     AIC\n- Sex       1 0.0002027 0.029629 -998.09\n- CogTel    1 0.0002917 0.029718 -997.73\n<none>                  0.029427 -996.92\n- Standort  1 0.0015166 0.030943 -992.84\n- T0        1 0.0169830 0.046410 -943.79\n\nStep:  AIC=-998.09\nT1_T0 ~ Standort + CogTel + T0\n\n           Df Sum of Sq      RSS     AIC\n- CogTel    1 0.0004098 0.030039 -998.43\n<none>                  0.029629 -998.09\n- Standort  1 0.0020231 0.031652 -992.10\n- T0        1 0.0167956 0.046425 -945.75\n\nStep:  AIC=-998.43\nT1_T0 ~ Standort + T0\n\n           Df Sum of Sq      RSS     AIC\n<none>                  0.030039 -998.43\n- Standort  1 0.0018812 0.031920 -993.08\n- T0        1 0.0176220 0.047661 -944.57\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + T0, data = tau_median_T1T0)\n\nCoefficients:\n(Intercept)    Standort2           T0  \n   0.026186    -0.008178    -0.947311  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#mean\ntau_aic_mean_T1T0 <- lm(formula = T1_T0 ~ Sex + Age_start + T0, data = tau_mean_T1T0)\nsummary(tau_aic_mean_T1T0 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Sex + Age_start + T0, data = tau_mean_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.048318 -0.012972 -0.001893  0.010483  0.064319 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0034915  0.0345403   0.101    0.920    \nSexM        -0.0055495  0.0035636  -1.557    0.122    \nAge_start    0.0007722  0.0004959   1.557    0.122    \nT0          -0.7141952  0.0901691  -7.921 1.52e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01924 on 117 degrees of freedom\nMultiple R-squared:  0.3524,\tAdjusted R-squared:  0.3358 \nF-statistic: 21.22 on 3 and 117 DF,  p-value: 4.808e-11\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(tau_aic_mean_T1T0 )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df   Sum Sq   Mean Sq F value    Pr(>F)    \nSex         1 0.000171 0.0001712  0.4626    0.4978    \nAge_start   1 0.000169 0.0001690  0.4567    0.5005    \nT0          1 0.023215 0.0232147 62.7362 1.519e-12 ***\nResiduals 117 0.043294 0.0003700                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(tau_aic_mean_T1T0 )\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\ntau_aic_median_T1T0 <- lm(formula = T1_T0 ~ Standort + T0, data = tau_median_T1T0)\nsummary(tau_aic_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + T0, data = tau_median_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.026976 -0.009325 -0.002503  0.006706  0.092497 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.026186   0.003267   8.016 8.82e-13 ***\nStandort2   -0.008178   0.003008  -2.718  0.00755 ** \nT0          -0.947311   0.113859  -8.320 1.77e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01596 on 118 degrees of freedom\nMultiple R-squared:  0.3849,\tAdjusted R-squared:  0.3744 \nF-statistic: 36.91 on 2 and 118 DF,  p-value: 3.546e-13\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(tau_aic_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df    Sum Sq   Mean Sq F value    Pr(>F)    \nStandort    1 0.0011712 0.0011712  4.6007   0.03401 *  \nT0          1 0.0176220 0.0176220 69.2231 1.766e-13 ***\nResiduals 118 0.0300391 0.0002546                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(tau_aic_median_T1T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n:::\n\n\n#### T2 - T1\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# with T1\n# mean\nlm_tau_mean_T2T1 <- lm(T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1, \n                  data = tau_mean_T2T1)\n\nsummary(lm_tau_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T1, data = tau_mean_T2T1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.046720 -0.012816 -0.001928  0.010971  0.047188 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0991137  0.0455146   2.178   0.0322 *  \nStandort2   -0.0002029  0.0049387  -0.041   0.9673    \nGruppePiano  0.0005400  0.0043976   0.123   0.9026    \nSexM        -0.0002530  0.0046307  -0.055   0.9566    \nAge_start   -0.0004087  0.0006009  -0.680   0.4983    \nCogTel      -0.0001645  0.0003079  -0.534   0.5945    \nT1          -0.8519782  0.1110001  -7.675  2.7e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.02009 on 84 degrees of freedom\nMultiple R-squared:  0.4513,\tAdjusted R-squared:  0.4121 \nF-statistic: 11.52 on 6 and 84 DF,  p-value: 2.292e-09\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_tau_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df   Sum Sq   Mean Sq F value    Pr(>F)    \nStandort   1 0.000305 0.0003050  0.7559   0.38709    \nGruppe     1 0.001226 0.0012258  3.0377   0.08501 .  \nSex        1 0.000412 0.0004121  1.0213   0.31511    \nAge_start  1 0.002106 0.0021061  5.2191   0.02486 *  \nCogTel     1 0.000062 0.0000615  0.1525   0.69718    \nT1         1 0.023774 0.0237737 58.9129 2.696e-11 ***\nResiduals 84 0.033897 0.0004035                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_tau_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-704.47\nT2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1\n\n            Df Sum of Sq      RSS     AIC\n- Standort   1 0.0000007 0.033898 -706.47\n- Sex        1 0.0000012 0.033899 -706.47\n- Gruppe     1 0.0000061 0.033903 -706.45\n- CogTel     1 0.0001152 0.034013 -706.16\n- Age_start  1 0.0001867 0.034084 -705.97\n<none>                   0.033897 -704.47\n- T1         1 0.0237737 0.057671 -658.11\n\nStep:  AIC=-706.47\nT2_T1 ~ Gruppe + Sex + Age_start + CogTel + T1\n\n            Df Sum of Sq      RSS     AIC\n- Sex        1 0.0000022 0.033900 -708.46\n- Gruppe     1 0.0000064 0.033904 -708.45\n- CogTel     1 0.0001180 0.034016 -708.15\n- Age_start  1 0.0001874 0.034086 -707.97\n<none>                   0.033898 -706.47\n- T1         1 0.0237859 0.057684 -660.09\n\nStep:  AIC=-708.46\nT2_T1 ~ Gruppe + Age_start + CogTel + T1\n\n            Df Sum of Sq      RSS     AIC\n- Gruppe     1 0.0000071 0.033907 -710.44\n- CogTel     1 0.0001159 0.034016 -710.15\n- Age_start  1 0.0001860 0.034086 -709.96\n<none>                   0.033900 -708.46\n- T1         1 0.0242805 0.058181 -661.31\n\nStep:  AIC=-710.44\nT2_T1 ~ Age_start + CogTel + T1\n\n            Df Sum of Sq      RSS     AIC\n- CogTel     1 0.0001320 0.034039 -712.09\n- Age_start  1 0.0001936 0.034101 -711.93\n<none>                   0.033907 -710.44\n- T1         1 0.0249972 0.058905 -662.19\n\nStep:  AIC=-712.09\nT2_T1 ~ Age_start + T1\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1 0.0001378 0.034177 -713.72\n<none>                   0.034039 -712.09\n- T1         1 0.0251509 0.059190 -663.75\n\nStep:  AIC=-713.72\nT2_T1 ~ T1\n\n       Df Sum of Sq      RSS     AIC\n<none>              0.034177 -713.72\n- T1    1  0.027605 0.061782 -661.85\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ T1, data = tau_mean_T2T1)\n\nCoefficients:\n(Intercept)           T1  \n    0.06664     -0.86999  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# median\n\nlm_tau_median_T2T1 <- lm(T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1, \n                  data = tau_median_T2T1)\n\nsummary(lm_tau_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T1, data = tau_median_T2T1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.026812 -0.011409 -0.000995  0.008411  0.043535 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0495798  0.0328362   1.510   0.1348    \nStandort2   -0.0048424  0.0036568  -1.324   0.1890    \nGruppePiano  0.0016716  0.0031292   0.534   0.5946    \nSexM        -0.0007908  0.0033156  -0.239   0.8121    \nAge_start   -0.0002316  0.0004260  -0.544   0.5882    \nCogTel      -0.0003803  0.0002224  -1.709   0.0911 .  \nT1          -1.0566455  0.1144433  -9.233 2.02e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01449 on 84 degrees of freedom\nMultiple R-squared:  0.5268,\tAdjusted R-squared:  0.493 \nF-statistic: 15.59 on 6 and 84 DF,  p-value: 6.133e-12\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_tau_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df    Sum Sq   Mean Sq F value    Pr(>F)    \nStandort   1 0.0001965 0.0001965  0.9353   0.33627    \nGruppe     1 0.0002611 0.0002611  1.2427   0.26813    \nSex        1 0.0000795 0.0000795  0.3786   0.54003    \nAge_start  1 0.0001795 0.0001795  0.8546   0.35790    \nCogTel     1 0.0010236 0.0010236  4.8724   0.03002 *  \nT1         1 0.0179089 0.0179089 85.2467 2.016e-14 ***\nResiduals 84 0.0176470 0.0002101                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_tau_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-763.87\nT2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1\n\n            Df Sum of Sq      RSS     AIC\n- Sex        1 0.0000120 0.017659 -765.81\n- Gruppe     1 0.0000600 0.017707 -765.56\n- Age_start  1 0.0000621 0.017709 -765.55\n- Standort   1 0.0003684 0.018015 -763.99\n<none>                   0.017647 -763.87\n- CogTel     1 0.0006139 0.018261 -762.76\n- T1         1 0.0179089 0.035556 -702.12\n\nStep:  AIC=-765.81\nT2_T1 ~ Standort + Gruppe + Age_start + CogTel + T1\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1 0.0000613 0.017720 -767.50\n- Gruppe     1 0.0000621 0.017721 -767.49\n<none>                   0.017659 -765.81\n- Standort   1 0.0004671 0.018126 -765.43\n- CogTel     1 0.0006032 0.018262 -764.75\n- T1         1 0.0179067 0.035566 -704.10\n\nStep:  AIC=-767.5\nT2_T1 ~ Standort + Gruppe + CogTel + T1\n\n           Df Sum of Sq      RSS     AIC\n- Gruppe    1 0.0000812 0.017801 -769.08\n<none>                  0.017720 -767.50\n- Standort  1 0.0004286 0.018149 -767.32\n- CogTel    1 0.0005475 0.018268 -766.73\n- T1        1 0.0182517 0.035972 -705.06\n\nStep:  AIC=-769.08\nT2_T1 ~ Standort + CogTel + T1\n\n           Df Sum of Sq      RSS     AIC\n<none>                  0.017801 -769.08\n- Standort  1 0.0004503 0.018252 -768.81\n- CogTel    1 0.0006381 0.018440 -767.87\n- T1        1 0.0182911 0.036093 -706.76\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Standort + CogTel + T1, data = tau_median_T2T1)\n\nCoefficients:\n(Intercept)    Standort2       CogTel           T1  \n  0.0336882   -0.0049826   -0.0003662   -1.0619892  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#mean\ntau_aic_mean_T2T1 <- lm(formula = T2_T1 ~ T1, data = tau_mean_T2T1)\nsummary(tau_aic_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ T1, data = tau_mean_T2T1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.046583 -0.013234 -0.002427  0.012715  0.047050 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.066639   0.008038   8.290  1.1e-12 ***\nT1          -0.869995   0.102612  -8.478  4.5e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0196 on 89 degrees of freedom\nMultiple R-squared:  0.4468,\tAdjusted R-squared:  0.4406 \nF-statistic: 71.88 on 1 and 89 DF,  p-value: 4.5e-13\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(tau_aic_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df   Sum Sq  Mean Sq F value  Pr(>F)    \nT1         1 0.027605 0.027605  71.885 4.5e-13 ***\nResiduals 89 0.034177 0.000384                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(tau_aic_mean_T2T1)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\ntau_aic_median_T2T1 <- lm(formula = T2_T1 ~ Standort + CogTel + T1, data = tau_median_T2T1)\nsummary(tau_aic_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Standort + CogTel + T1, data = tau_median_T2T1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.024723 -0.012049 -0.001191  0.007389  0.045077 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0336882  0.0075330   4.472 2.33e-05 ***\nStandort2   -0.0049826  0.0033585  -1.484   0.1415    \nCogTel      -0.0003662  0.0002074  -1.766   0.0809 .  \nT1          -1.0619892  0.1123228  -9.455 5.26e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0143 on 87 degrees of freedom\nMultiple R-squared:  0.5227,\tAdjusted R-squared:  0.5062 \nF-statistic: 31.76 on 3 and 87 DF,  p-value: 5.84e-14\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(tau_aic_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df    Sum Sq   Mean Sq F value   Pr(>F)    \nStandort   1 0.0001965 0.0001965  0.9603  0.32983    \nCogTel     1 0.0010070 0.0010070  4.9217  0.02913 *  \nT1         1 0.0182911 0.0182911 89.3931 5.26e-15 ***\nResiduals 87 0.0178015 0.0002046                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(tau_aic_median_T2T1)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n:::\n\n\n#### Plot models\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#T2-T0\nvisreg(tau_aic_mean_T2T0, gg = T)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(tau_aic_median_T2T0, gg = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-3.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#T1-T0\nvisreg(tau_aic_mean_T1T0, gg = F)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-6.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(tau_aic_median_T1T0, gg = F)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-8.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#T2-T1\nvisreg(tau_aic_mean_T2T1, gg = F)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-9.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(tau_aic_median_T2T1, gg = F)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-21-12.png){width=672}\n:::\n:::\n\n\n### PSD95\n\n#### T2-T0\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# lm mean\nlm_psd95_mean_T2T0 <- lm(T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = psd95_mean_T2T0)\n\nsummary(lm_psd95_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = psd95_mean_T2T0)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0273257 -0.0069448  0.0006532  0.0059836  0.0247726 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0542251  0.0231596   2.341   0.0215 *  \nStandort2    0.0007980  0.0025680   0.311   0.7567    \nGruppePiano -0.0026814  0.0021357  -1.256   0.2127    \nSexM        -0.0030649  0.0023351  -1.313   0.1928    \nAge_start   -0.0001681  0.0002992  -0.562   0.5758    \nCogTel      -0.0001505  0.0001565  -0.961   0.3390    \nT0          -1.1559670  0.0757546 -15.259   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01014 on 86 degrees of freedom\nMultiple R-squared:  0.7354,\tAdjusted R-squared:  0.7169 \nF-statistic: 39.83 on 6 and 86 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_psd95_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df    Sum Sq   Mean Sq  F value  Pr(>F)    \nStandort   1 0.0000337 0.0000337   0.3279 0.56837    \nGruppe     1 0.0003528 0.0003528   3.4306 0.06743 .  \nSex        1 0.0001133 0.0001133   1.1014 0.29690    \nAge_start  1 0.0001265 0.0001265   1.2301 0.27049    \nCogTel     1 0.0000044 0.0000044   0.0430 0.83620    \nT0         1 0.0239423 0.0239423 232.8485 < 2e-16 ***\nResiduals 86 0.0088428 0.0001028                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(lm_psd95_mean_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_psd95_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-847.25\nT2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Standort   1 0.0000099 0.008853 -849.15\n- Age_start  1 0.0000324 0.008875 -848.91\n- CogTel     1 0.0000950 0.008938 -848.26\n- Gruppe     1 0.0001621 0.009005 -847.56\n- Sex        1 0.0001771 0.009020 -847.40\n<none>                   0.008843 -847.25\n- T0         1 0.0239423 0.032785 -727.39\n\nStep:  AIC=-849.15\nT2_T0 ~ Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1 0.0000400 0.008893 -850.73\n- CogTel     1 0.0000914 0.008944 -850.19\n- Gruppe     1 0.0001645 0.009017 -849.43\n- Sex        1 0.0001709 0.009024 -849.37\n<none>                   0.008853 -849.15\n- T0         1 0.0239333 0.032786 -729.38\n\nStep:  AIC=-850.73\nT2_T0 ~ Gruppe + Sex + CogTel + T0\n\n         Df Sum of Sq      RSS     AIC\n- CogTel  1 0.0000696 0.008962 -852.00\n- Gruppe  1 0.0001512 0.009044 -851.16\n- Sex     1 0.0001632 0.009056 -851.03\n<none>                0.008893 -850.73\n- T0      1 0.0240242 0.032917 -731.01\n\nStep:  AIC=-852\nT2_T0 ~ Gruppe + Sex + T0\n\n         Df Sum of Sq      RSS     AIC\n- Gruppe  1 0.0001273 0.009090 -852.69\n- Sex     1 0.0001306 0.009093 -852.66\n<none>                0.008962 -852.00\n- T0      1 0.0239548 0.032917 -733.01\n\nStep:  AIC=-852.69\nT2_T0 ~ Sex + T0\n\n       Df Sum of Sq      RSS     AIC\n- Sex   1  0.000130 0.009220 -853.37\n<none>              0.009090 -852.69\n- T0    1  0.024182 0.033271 -734.02\n\nStep:  AIC=-853.37\nT2_T0 ~ T0\n\n       Df Sum of Sq      RSS     AIC\n<none>              0.009220 -853.37\n- T0    1  0.024196 0.033416 -735.61\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ T0, data = psd95_mean_T2T0)\n\nCoefficients:\n(Intercept)           T0  \n    0.03497     -1.14474  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# lm median\nlm_psd95_median_T2T0 <- lm(T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = psd95_median_T2T0)\n\nsummary(lm_psd95_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = psd95_median_T2T0)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0016799 -0.0010474 -0.0002488  0.0000819  0.0182717 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  5.093e-05  6.211e-03   0.008    0.993    \nStandort2   -4.084e-04  6.955e-04  -0.587    0.559    \nGruppePiano -2.979e-04  5.759e-04  -0.517    0.606    \nSexM        -9.549e-04  6.303e-04  -1.515    0.133    \nAge_start    1.391e-05  8.047e-05   0.173    0.863    \nCogTel       1.562e-05  4.203e-05   0.372    0.711    \nT0          -1.036e+00  4.090e-02 -25.330   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.002718 on 86 degrees of freedom\nMultiple R-squared:  0.8891,\tAdjusted R-squared:  0.8814 \nF-statistic:   115 on 6 and 86 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_psd95_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df    Sum Sq   Mean Sq  F value    Pr(>F)    \nStandort   1 0.0001136 0.0001136  15.3747 0.0001767 ***\nGruppe     1 0.0000490 0.0000490   6.6353 0.0117057 *  \nSex        1 0.0001167 0.0001167  15.7891 0.0001468 ***\nAge_start  1 0.0000584 0.0000584   7.9103 0.0060888 ** \nCogTel     1 0.0000183 0.0000183   2.4827 0.1187730    \nT0         1 0.0047407 0.0047407 641.6082 < 2.2e-16 ***\nResiduals 86 0.0006354 0.0000074                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(lm_psd95_median_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-22-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_psd95_median_T2T0) # call: lm(formula = T2_T0 ~ T0, data = bdnf_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-1092.12\nT2_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq       RSS      AIC\n- Age_start  1 0.0000002 0.0006357 -1094.09\n- CogTel     1 0.0000010 0.0006365 -1093.97\n- Gruppe     1 0.0000020 0.0006374 -1093.83\n- Standort   1 0.0000025 0.0006380 -1093.75\n<none>                   0.0006354 -1092.12\n- Sex        1 0.0000170 0.0006524 -1091.67\n- T0         1 0.0047407 0.0053762  -895.53\n\nStep:  AIC=-1094.09\nT2_T0 ~ Standort + Gruppe + Sex + CogTel + T0\n\n           Df Sum of Sq       RSS      AIC\n- CogTel    1 0.0000009 0.0006365 -1095.96\n- Gruppe    1 0.0000021 0.0006378 -1095.78\n- Standort  1 0.0000029 0.0006385 -1095.67\n<none>                  0.0006357 -1094.09\n- Sex       1 0.0000170 0.0006526 -1093.64\n- T0        1 0.0047834 0.0054190  -896.79\n\nStep:  AIC=-1095.96\nT2_T0 ~ Standort + Gruppe + Sex + T0\n\n           Df Sum of Sq       RSS      AIC\n- Gruppe    1 0.0000025 0.0006391 -1097.60\n- Standort  1 0.0000026 0.0006391 -1097.58\n<none>                  0.0006365 -1095.96\n- Sex       1 0.0000190 0.0006555 -1095.23\n- T0        1 0.0048164 0.0054530  -898.21\n\nStep:  AIC=-1097.6\nT2_T0 ~ Standort + Sex + T0\n\n           Df Sum of Sq       RSS      AIC\n- Standort  1 0.0000026 0.0006416 -1099.22\n<none>                  0.0006391 -1097.60\n- Sex       1 0.0000187 0.0006577 -1096.92\n- T0        1 0.0048629 0.0055019  -899.38\n\nStep:  AIC=-1099.22\nT2_T0 ~ Sex + T0\n\n       Df Sum of Sq       RSS      AIC\n<none>              0.0006416 -1099.22\n- Sex   1 0.0000287 0.0006704 -1097.15\n- T0    1 0.0050523 0.0056939  -898.19\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ Sex + T0, data = psd95_median_T2T0)\n\nCoefficients:\n(Intercept)         SexM           T0  \n   0.001167    -0.001127    -1.036552  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#mean\npsd95_aic_mean_T2T0 <- lm(formula = T2_T0 ~ T0, data = psd95_mean_T2T0)\nsummary(psd95_aic_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ T0, data = psd95_mean_T2T0)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0256801 -0.0074213  0.0003359  0.0062237  0.0266314 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.034965   0.002399   14.57   <2e-16 ***\nT0          -1.144742   0.074075  -15.45   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01007 on 91 degrees of freedom\nMultiple R-squared:  0.7241,\tAdjusted R-squared:  0.7211 \nF-statistic: 238.8 on 1 and 91 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(psd95_aic_mean_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df    Sum Sq   Mean Sq F value    Pr(>F)    \nT0         1 0.0241962 0.0241962  238.82 < 2.2e-16 ***\nResiduals 91 0.0092196 0.0001013                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(psd95_aic_mean_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\npsd95_aic_median_T2T0 <- lm(formula = T2_T0 ~ Sex + T0, data = psd95_median_T2T0)\nsummary(psd95_aic_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T0 ~ Sex + T0, data = psd95_median_T2T0)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0011673 -0.0011673 -0.0000406 -0.0000406  0.0188327 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0011673  0.0004080   2.861  0.00525 ** \nSexM        -0.0011267  0.0005614  -2.007  0.04775 *  \nT0          -1.0365516  0.0389376 -26.621  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.00267 on 90 degrees of freedom\nMultiple R-squared:  0.8881,\tAdjusted R-squared:  0.8856 \nF-statistic:   357 on 2 and 90 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(psd95_aic_median_T2T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T0\n          Df    Sum Sq   Mean Sq  F value  Pr(>F)    \nSex        1 0.0000383 0.0000383   5.3771 0.02267 *  \nT0         1 0.0050523 0.0050523 708.6685 < 2e-16 ***\nResiduals 90 0.0006416 0.0000071                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(psd95_aic_median_T2T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-23-2.png){width=672}\n:::\n:::\n\n\n#### T1 - T0\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# mean\nlm_psd95_mean_T1T0 <- lm(T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = psd95_mean_T1T0)\n\nsummary(lm_psd95_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = psd95_mean_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.026832 -0.009188 -0.001510  0.006497  0.031588 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0610346  0.0259974   2.348   0.0207 *  \nStandort2    0.0058052  0.0025807   2.249   0.0265 *  \nGruppePiano -0.0028657  0.0023920  -1.198   0.2335    \nSexM        -0.0046326  0.0025749  -1.799   0.0747 .  \nAge_start   -0.0003657  0.0003433  -1.065   0.2890    \nCogTel      -0.0001519  0.0001715  -0.886   0.3776    \nT0          -0.9738409  0.0744008 -13.089   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01276 on 111 degrees of freedom\nMultiple R-squared:  0.6202,\tAdjusted R-squared:  0.5997 \nF-statistic: 30.21 on 6 and 111 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_psd95_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df    Sum Sq   Mean Sq  F value  Pr(>F)    \nStandort    1 0.0004694 0.0004694   2.8848 0.09222 .  \nGruppe      1 0.0004184 0.0004184   2.5712 0.11167    \nSex         1 0.0000705 0.0000705   0.4332 0.51178    \nAge_start   1 0.0003666 0.0003666   2.2528 0.13621    \nCogTel      1 0.0002956 0.0002956   1.8166 0.18046    \nT0          1 0.0278785 0.0278785 171.3250 < 2e-16 ***\nResiduals 111 0.0180623 0.0001627                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_psd95_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-1022.58\nT1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS      AIC\n- CogTel     1 0.0001277 0.018190 -1023.75\n- Age_start  1 0.0001847 0.018247 -1023.38\n- Gruppe     1 0.0002336 0.018296 -1023.07\n<none>                   0.018062 -1022.58\n- Sex        1 0.0005267 0.018589 -1021.19\n- Standort   1 0.0008234 0.018886 -1019.32\n- T0         1 0.0278785 0.045941  -914.43\n\nStep:  AIC=-1023.75\nT1_T0 ~ Standort + Gruppe + Sex + Age_start + T0\n\n            Df Sum of Sq      RSS      AIC\n- Age_start  1 0.0001310 0.018321 -1024.91\n- Gruppe     1 0.0001875 0.018377 -1024.54\n<none>                   0.018190 -1023.75\n- Sex        1 0.0004531 0.018643 -1022.85\n- Standort   1 0.0007607 0.018951 -1020.92\n- T0         1 0.0280464 0.046236  -915.67\n\nStep:  AIC=-1024.91\nT1_T0 ~ Standort + Gruppe + Sex + T0\n\n           Df Sum of Sq      RSS      AIC\n- Gruppe    1 0.0001703 0.018491 -1025.81\n<none>                  0.018321 -1024.91\n- Sex       1 0.0004832 0.018804 -1023.83\n- Standort  1 0.0008349 0.019156 -1021.65\n- T0        1 0.0282820 0.046603  -916.74\n\nStep:  AIC=-1025.81\nT1_T0 ~ Standort + Sex + T0\n\n           Df Sum of Sq      RSS      AIC\n<none>                  0.018491 -1025.81\n- Sex       1 0.0005303 0.019022 -1024.48\n- Standort  1 0.0008737 0.019365 -1022.37\n- T0        1 0.0285518 0.047043  -917.63\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Sex + T0, data = psd95_mean_T1T0)\n\nCoefficients:\n(Intercept)    Standort2         SexM           T0  \n   0.029346     0.005903    -0.004554    -0.982794  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# median\nlm_psd95_median_T1T0 <- lm(T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0, \n                  data = psd95_median_T1T0)\n\nsummary(lm_psd95_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T0, data = psd95_median_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.010088 -0.004682 -0.002181  0.000559  0.055813 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0232394  0.0196272   1.184   0.2389    \nStandort2    0.0046372  0.0019814   2.340   0.0211 *  \nGruppePiano -0.0019964  0.0018220  -1.096   0.2756    \nSexM        -0.0040228  0.0019464  -2.067   0.0411 *  \nAge_start   -0.0001785  0.0002588  -0.690   0.4917    \nCogTel      -0.0002142  0.0001291  -1.660   0.0998 .  \nT0          -1.2131415  0.1090570 -11.124   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.009604 on 111 degrees of freedom\nMultiple R-squared:  0.5373,\tAdjusted R-squared:  0.5123 \nF-statistic: 21.48 on 6 and 111 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_psd95_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df    Sum Sq   Mean Sq  F value  Pr(>F)    \nStandort    1 0.0000014 0.0000014   0.0156 0.90083    \nGruppe      1 0.0000946 0.0000946   1.0260 0.31330    \nSex         1 0.0000212 0.0000212   0.2295 0.63287    \nAge_start   1 0.0000266 0.0000266   0.2883 0.59236    \nCogTel      1 0.0003309 0.0003309   3.5878 0.06081 .  \nT0          1 0.0114142 0.0114142 123.7416 < 2e-16 ***\nResiduals 111 0.0102389 0.0000922                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_psd95_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-1089.56\nT1_T0 ~ Standort + Gruppe + Sex + Age_start + CogTel + T0\n\n            Df Sum of Sq      RSS     AIC\n- Age_start  1 0.0000439 0.010283 -1091.1\n- Gruppe     1 0.0001107 0.010350 -1090.3\n<none>                   0.010239 -1089.6\n- CogTel     1 0.0002541 0.010493 -1088.7\n- Sex        1 0.0003940 0.010633 -1087.1\n- Standort   1 0.0005052 0.010744 -1085.9\n- T0         1 0.0114142 0.021653 -1003.2\n\nStep:  AIC=-1091.06\nT1_T0 ~ Standort + Gruppe + Sex + CogTel + T0\n\n           Df Sum of Sq      RSS     AIC\n- Gruppe    1 0.0000986 0.010381 -1091.9\n<none>                  0.010283 -1091.1\n- CogTel    1 0.0002215 0.010504 -1090.5\n- Sex       1 0.0003926 0.010675 -1088.6\n- Standort  1 0.0005231 0.010806 -1087.2\n- T0        1 0.0113718 0.021655 -1005.2\n\nStep:  AIC=-1091.93\nT1_T0 ~ Standort + Sex + CogTel + T0\n\n           Df Sum of Sq      RSS     AIC\n<none>                  0.010381 -1091.9\n- CogTel    1 0.0001876 0.010569 -1091.8\n- Sex       1 0.0003957 0.010777 -1089.5\n- Standort  1 0.0005195 0.010901 -1088.2\n- T0        1 0.0113178 0.021699 -1006.9\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Sex + CogTel + T0, data = psd95_median_T1T0)\n\nCoefficients:\n(Intercept)    Standort2         SexM       CogTel           T0  \n  0.0085177    0.0046950   -0.0040313   -0.0001784   -1.1902209  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#mean\npsd95_aic_mean_T1T0 <- lm(formula = T1_T0 ~ Standort + Sex + T0, data = psd95_mean_T1T0)\nsummary(psd95_aic_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Sex + T0, data = psd95_mean_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.027386 -0.009829 -0.002006  0.007223  0.034056 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.029346   0.003053   9.613 2.23e-16 ***\nStandort2    0.005903   0.002543   2.321   0.0221 *  \nSexM        -0.004554   0.002519  -1.808   0.0732 .  \nT0          -0.982794   0.074076 -13.267  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01274 on 114 degrees of freedom\nMultiple R-squared:  0.6112,\tAdjusted R-squared:  0.601 \nF-statistic: 59.74 on 3 and 114 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(psd95_aic_mean_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df    Sum Sq   Mean Sq  F value  Pr(>F)    \nStandort    1 0.0004694 0.0004694   2.8940 0.09164 .  \nSex         1 0.0000488 0.0000488   0.3012 0.58423    \nT0          1 0.0285518 0.0285518 176.0241 < 2e-16 ***\nResiduals 114 0.0184912 0.0001622                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(psd95_aic_mean_T1T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\npsd95_aic_median_T1T0 <- lm(formula = T1_T0 ~ Standort + Sex + CogTel + T0, data = psd95_median_T1T0)\nsummary(psd95_aic_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T1_T0 ~ Standort + Sex + CogTel + T0, data = psd95_median_T1T0)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.009591 -0.004295 -0.002322  0.000192  0.057387 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0085177  0.0042733   1.993   0.0486 *  \nStandort2    0.0046950  0.0019744   2.378   0.0191 *  \nSexM        -0.0040313  0.0019424  -2.075   0.0402 *  \nCogTel      -0.0001784  0.0001248  -1.429   0.1558    \nT0          -1.1902209  0.1072347 -11.099   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.009585 on 113 degrees of freedom\nMultiple R-squared:  0.5308,\tAdjusted R-squared:  0.5142 \nF-statistic: 31.97 on 4 and 113 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(psd95_aic_median_T1T0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_T0\n           Df    Sum Sq   Mean Sq  F value  Pr(>F)    \nStandort    1 0.0000014 0.0000014   0.0157 0.90063    \nSex         1 0.0000276 0.0000276   0.3000 0.58495    \nCogTel      1 0.0003998 0.0003998   4.3518 0.03922 *  \nT0          1 0.0113178 0.0113178 123.1927 < 2e-16 ***\nResiduals 113 0.0103814 0.0000919                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(psd95_aic_median_T1T0)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-25-2.png){width=672}\n:::\n:::\n\n\n#### T2 - T1\n\n##### All variables and step()\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# with T1\n# mean\nlm_psd95_mean_T2T1 <- lm(T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1, \n                  data = psd95_mean_T2T1)\n\nsummary(lm_psd95_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T1, data = psd95_mean_T2T1)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.027806 -0.007097  0.001468  0.006843  0.021887 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0491102  0.0246997   1.988   0.0501 .  \nStandort2    0.0003252  0.0026461   0.123   0.9025    \nGruppePiano -0.0036808  0.0022672  -1.623   0.1083    \nSexM        -0.0036065  0.0024143  -1.494   0.1391    \nAge_start   -0.0001124  0.0003132  -0.359   0.7205    \nCogTel      -0.0002178  0.0001627  -1.339   0.1844    \nT1          -1.0063490  0.0851788 -11.815   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01045 on 82 degrees of freedom\nMultiple R-squared:  0.6417,\tAdjusted R-squared:  0.6155 \nF-statistic: 24.47 on 6 and 82 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_psd95_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df    Sum Sq   Mean Sq  F value  Pr(>F)    \nStandort   1 0.0005680 0.0005680   5.2013 0.02516 *  \nGruppe     1 0.0001680 0.0001680   1.5382 0.21842    \nSex        1 0.0000000 0.0000000   0.0000 0.99844    \nAge_start  1 0.0000533 0.0000533   0.4880 0.48680    \nCogTel     1 0.0000031 0.0000031   0.0284 0.86649    \nT1         1 0.0152443 0.0152443 139.5835 < 2e-16 ***\nResiduals 82 0.0089554 0.0001092                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_psd95_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-805.17\nT2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1\n\n            Df Sum of Sq       RSS     AIC\n- Standort   1 0.0000016 0.0089571 -807.15\n- Age_start  1 0.0000141 0.0089695 -807.03\n- CogTel     1 0.0001957 0.0091511 -805.24\n<none>                   0.0089554 -805.17\n- Sex        1 0.0002437 0.0091992 -804.78\n- Gruppe     1 0.0002879 0.0092433 -804.35\n- T1         1 0.0152443 0.0241997 -718.69\n\nStep:  AIC=-807.15\nT2_T1 ~ Gruppe + Sex + Age_start + CogTel + T1\n\n            Df Sum of Sq       RSS     AIC\n- Age_start  1 0.0000159 0.0089730 -808.99\n- CogTel     1 0.0001940 0.0091511 -807.24\n<none>                   0.0089571 -807.15\n- Sex        1 0.0002622 0.0092193 -806.58\n- Gruppe     1 0.0002892 0.0092463 -806.32\n- T1         1 0.0156774 0.0246345 -719.11\n\nStep:  AIC=-808.99\nT2_T1 ~ Gruppe + Sex + CogTel + T1\n\n         Df Sum of Sq       RSS     AIC\n- CogTel  1 0.0001785 0.0091514 -809.24\n<none>                0.0089730 -808.99\n- Sex     1 0.0002540 0.0092269 -808.51\n- Gruppe  1 0.0002766 0.0092496 -808.29\n- T1      1 0.0157669 0.0247399 -720.73\n\nStep:  AIC=-809.24\nT2_T1 ~ Gruppe + Sex + T1\n\n         Df Sum of Sq       RSS     AIC\n- Sex     1 0.0001927 0.0093441 -809.39\n<none>                0.0091514 -809.24\n- Gruppe  1 0.0002195 0.0093709 -809.13\n- T1      1 0.0156227 0.0247741 -722.61\n\nStep:  AIC=-809.39\nT2_T1 ~ Gruppe + T1\n\n         Df Sum of Sq       RSS     AIC\n<none>                0.0093441 -809.39\n- Gruppe  1 0.0002257 0.0095698 -809.26\n- T1      1 0.0154932 0.0248373 -724.38\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Gruppe + T1, data = psd95_mean_T2T1)\n\nCoefficients:\n(Intercept)  GruppePiano           T1  \n   0.031890    -0.003196    -0.989255  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# median\n\nlm_psd95_median_T2T1 <- lm(T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1, \n                  data = psd95_median_T2T1)\n\nsummary(lm_psd95_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + \n    T1, data = psd95_median_T2T1)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0020378 -0.0010679 -0.0004147  0.0000514  0.0183712 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.718e-04  6.449e-03   0.027    0.979    \nStandort2   -6.199e-04  7.170e-04  -0.865    0.390    \nGruppePiano -2.751e-04  6.032e-04  -0.456    0.650    \nSexM        -7.986e-04  6.459e-04  -1.236    0.220    \nAge_start    8.324e-06  8.349e-05   0.100    0.921    \nCogTel       2.051e-05  4.402e-05   0.466    0.643    \nT1          -9.682e-01  3.775e-02 -25.645   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.002783 on 82 degrees of freedom\nMultiple R-squared:  0.9017,\tAdjusted R-squared:  0.8945 \nF-statistic: 125.3 on 6 and 82 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(lm_psd95_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df    Sum Sq   Mean Sq  F value    Pr(>F)    \nStandort   1 0.0003256 0.0003256  42.0553 6.269e-09 ***\nGruppe     1 0.0000108 0.0000108   1.3994 0.2402406    \nSex        1 0.0000194 0.0000194   2.5077 0.1171371    \nAge_start  1 0.0001146 0.0001146  14.7969 0.0002358 ***\nCogTel     1 0.0002591 0.0002591  33.4643 1.279e-07 ***\nT1         1 0.0050918 0.0050918 657.6484 < 2.2e-16 ***\nResiduals 82 0.0006349 0.0000077                       \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nstep(lm_psd95_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=-1040.71\nT2_T1 ~ Standort + Gruppe + Sex + Age_start + CogTel + T1\n\n            Df Sum of Sq       RSS      AIC\n- Age_start  1 0.0000001 0.0006350 -1042.70\n- Gruppe     1 0.0000016 0.0006365 -1042.49\n- CogTel     1 0.0000017 0.0006366 -1042.48\n- Standort   1 0.0000058 0.0006407 -1041.91\n- Sex        1 0.0000118 0.0006467 -1041.07\n<none>                   0.0006349 -1040.71\n- T1         1 0.0050918 0.0057267  -846.96\n\nStep:  AIC=-1042.7\nT2_T1 ~ Standort + Gruppe + Sex + CogTel + T1\n\n           Df Sum of Sq       RSS      AIC\n- CogTel    1 0.0000016 0.0006366 -1044.48\n- Gruppe    1 0.0000017 0.0006367 -1044.46\n- Standort  1 0.0000062 0.0006412 -1043.83\n- Sex       1 0.0000118 0.0006468 -1043.06\n<none>                  0.0006350 -1042.70\n- T1        1 0.0051374 0.0057723  -848.26\n\nStep:  AIC=-1044.48\nT2_T1 ~ Standort + Gruppe + Sex + T1\n\n           Df Sum of Sq       RSS      AIC\n- Gruppe    1 0.0000023 0.0006388 -1046.16\n- Standort  1 0.0000054 0.0006420 -1045.72\n<none>                  0.0006366 -1044.48\n- Sex       1 0.0000145 0.0006511 -1044.47\n- T1        1 0.0054638 0.0061003  -845.34\n\nStep:  AIC=-1046.16\nT2_T1 ~ Standort + Sex + T1\n\n           Df Sum of Sq       RSS      AIC\n- Standort  1 0.0000052 0.0006440 -1047.44\n<none>                  0.0006388 -1046.16\n- Sex       1 0.0000149 0.0006537 -1046.11\n- T1        1 0.0054730 0.0061119  -847.17\n\nStep:  AIC=-1047.44\nT2_T1 ~ Sex + T1\n\n       Df Sum of Sq       RSS      AIC\n<none>              0.0006440 -1047.44\n- Sex   1 0.0000244 0.0006684 -1046.13\n- T1    1 0.0058086 0.0064527  -844.34\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Sex + T1, data = psd95_median_T2T1)\n\nCoefficients:\n(Intercept)         SexM           T1  \n   0.000991    -0.001050    -0.978602  \n```\n\n\n:::\n:::\n\n\n##### AIC model recommendation\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#mean\npsd95_aic_mean_T2T1 <- lm(formula = T2_T1 ~ Gruppe + T1, data = psd95_mean_T2T1)\nsummary(psd95_aic_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Gruppe + T1, data = psd95_mean_T2T1)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0274098 -0.0067791  0.0004242  0.0067197  0.0239049 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.031890   0.003105  10.269   <2e-16 ***\nGruppePiano -0.003196   0.002217  -1.441    0.153    \nT1          -0.989255   0.082843 -11.941   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01042 on 86 degrees of freedom\nMultiple R-squared:  0.6261,\tAdjusted R-squared:  0.6174 \nF-statistic: 72.01 on 2 and 86 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(psd95_aic_mean_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df    Sum Sq   Mean Sq  F value Pr(>F)    \nGruppe     1 0.0001549 0.0001549   1.4257 0.2357    \nT1         1 0.0154932 0.0154932 142.5935 <2e-16 ***\nResiduals 86 0.0093441 0.0001087                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npar(mfrow = c(2,2))\nplot(psd95_aic_mean_T2T1)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#median\npsd95_aic_median_T2T1 <- lm(formula = T2_T1 ~ Sex + T1, data = psd95_median_T2T1)\nsummary(psd95_aic_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = T2_T1 ~ Sex + T1, data = psd95_median_T2T1)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.0020609 -0.0009910 -0.0003694  0.0000586  0.0190090 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0009910  0.0004167   2.378   0.0196 *  \nSexM        -0.0010496  0.0005815  -1.805   0.0746 .  \nT1          -0.9786022  0.0351377 -27.850   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.002737 on 86 degrees of freedom\nMultiple R-squared:  0.9002,\tAdjusted R-squared:  0.8979 \nF-statistic: 388.1 on 2 and 86 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nanova(psd95_aic_median_T2T1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T2_T1\n          Df    Sum Sq   Mean Sq  F value Pr(>F)    \nSex        1 0.0000035 0.0000035   0.4684 0.4956    \nT1         1 0.0058086 0.0058086 775.6503 <2e-16 ***\nResiduals 86 0.0006440 0.0000075                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot(psd95_aic_median_T2T1)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-27-2.png){width=672}\n:::\n:::\n\n\n#### Plot models\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#T2-T0\nvisreg(psd95_aic_mean_T2T0, gg = T)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(psd95_aic_median_T2T0, gg = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n[[2]]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-3.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#T1-T0\nvisreg(psd95_aic_mean_T1T0, gg = F)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-6.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(psd95_aic_median_T1T0, gg = F)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-8.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-10.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n#T2-T1\nvisreg(psd95_aic_mean_T2T1, gg = F)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-12.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nvisreg(psd95_aic_median_T2T1, gg = F)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-13.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-28-14.png){width=672}\n:::\n:::\n\n\n## GLM: Regression analysis (Bivariate/multivariate)\n\n# EDA \\# Allgenes?\n\n## Gruppendifferenz der Mittelwerte?\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(psych)\nlibrary(DescTools)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'DescTools'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:psych':\n\n    AUC, ICC, SD\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Modes\nMode(bdnf_mean$Mean, na.rm = TRUE) #  8x: 0 u. 0.063 -> bimodal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000 0.063\nattr(,\"freq\")\n[1] 8\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(tau_mean$Mean, na.rm = TRUE) # 6x 0.066875\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.066875\nattr(,\"freq\")\n[1] 6\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(psd95_mean$Mean, na.rm = TRUE) # 3x: 0.02377778 u. 0.03177778 -> bimodal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02377778 0.03177778\nattr(,\"freq\")\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(bdnf_median$Median, na.rm = TRUE) # 92x: 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\nattr(,\"freq\")\n[1] 92\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(tau_median$Median, na.rm = TRUE) # 65x: 0.02\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02\nattr(,\"freq\")\n[1] 65\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMode(psd95_median$Median, na.rm = TRUE) # 317x: 0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\nattr(,\"freq\")\n[1] 317\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#with tapply\n# Minimale Differenz\ntapply(bdnf_mean$Mean, bdnf_mean$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.04800 0.07000 0.07326 0.09500 0.16900       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.04600 0.06400 0.06598 0.08825 0.18600       4 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(bdnf_median$Median, bdnf_median$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n 0.0000  0.0025  0.0350  0.0397  0.0600  0.2050       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n 0.0000  0.0000  0.0250  0.0344  0.0500  0.2100       4 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# überhaupt keine Differenz\ntapply(tau_mean$Mean, tau_mean$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.02813 0.06294 0.07269 0.07515 0.08583 0.14574       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.01250 0.06270 0.07323 0.07510 0.08625 0.16708       1 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(tau_median$Median, tau_median$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.01000 0.02000 0.02011 0.03000 0.12000       1 \n\n$Piano\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.01000 0.02000 0.01906 0.03000 0.06500       1 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# überhaupt keine Differenz\ntapply(psd95_mean$Mean, psd95_mean$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n0.00000 0.02316 0.03054 0.03131 0.03832 0.13062       3 \n\n$Piano\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.007083 0.021574 0.028556 0.030294 0.036550 0.080000        2 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(psd95_median$Median, psd95_median$Gruppe, summary, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$Controll\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.000000 0.000000 0.000000 0.003101 0.000000 0.060000        3 \n\n$Piano\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n0.000000 0.000000 0.000000 0.001601 0.000000 0.050000        2 \n```\n\n\n:::\n:::\n\n\n-   Bei BDNF zeigt sich eine leichte Differenz zwischen der Kontrollgruppe (Median: 0.07, Mean: 0.07326) und der Pianogruppe (Median: 0.064, Mean: 0.06598), welche eine niedrigere Metyhlierung (Median: -0.006, Mean: -0.00728) aufwies.\n-   Weiterhin zeigen sich für die arithmetischen Mittel von BDNF und PSD95 zwei Modi.\n-   Tau war unimodal.\n\n## Zeitdifferenz der Mittelwerte?\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Methylierung: PSD95 < Tau < BDNF\n\ntapply(bdnf_mean$Mean, bdnf_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 > T1 < T2 (T0 < T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.06991766 0.06213866 0.07886025 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(bdnf_median$Median, bdnf_median$Zeitpunkt, median, na.rm = TRUE) # T0 > T1 < T2 (T0 < T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   T0    T1    T2 \n0.030 0.025 0.040 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(tau_mean$Mean, tau_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 < T1 = T2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.07346318 0.07632020 0.07604121 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(tau_median$Median, tau_median$Zeitpunkt, median, na.rm = TRUE) # T0 = T1 > T2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   T0    T1    T2 \n0.020 0.020 0.015 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# überhaupt keine Differenz\ntapply(psd95_mean$Mean, psd95_mean$Zeitpunkt, mean, na.rm = TRUE) # T0 < T1 > T2 (T0 = T2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        T0         T1         T2 \n0.02978670 0.03197377 0.03078094 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntapply(psd95_median$Median, psd95_median$Zeitpunkt, median, na.rm = TRUE) # all = 0 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nT0 T1 T2 \n 0  0  0 \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# noch geringer als Tau und BDNF methyliert\n```\n:::\n\n\n-   Die Gene sind allgemein eher gering methyliert (Mean \\< 0,08, Median \\< 0,04).\n-   Dabei ist PSD95 am geringsten und BDNF am höchsten metyhyliert.\n-   Bei BDNF zeigt sich, dass sich die Mittelwerte (Arithmetisch und Median) von T0 zu T1 leicht absenken und zu T2 wieder über das Niveau von T0 ansteigen.\n-   Bei Tau steigt das arithmetische Mittel der Methylierung leicht von T0 zu T1 und hält das Niveau bei T2.\n-   Bei PSD95 verbleibt der Median der Methylierun gleichbleibend bei 0, während das arithmetische Mittel der Methylierung von T0 zu T1 steigt aber bei T2 wieder auf das Ausgangsniveau zurückfällt.\n\n## EDA for important point and interval estimators\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(psych)\nlibrary(psychTools)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'psychTools'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## BDNF\ndescribe(bdnf_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad min    max  range  skew\nID           1 144 108.17 62.41 121.50  109.68 80.80   1 202.00 201.00 -0.23\nStandort     2 144   0.62  0.49   1.00    0.66  0.00   0   1.00   1.00 -0.51\nGruppe*      3 144   1.47  0.50   1.00    1.46  0.00   1   2.00   1.00  0.14\nSex*         4 144   1.42  0.50   1.00    1.41  0.00   1   2.00   1.00  0.31\nAge_start    5 144  69.58  3.51  69.00   69.37  2.97  62  78.00  16.00  0.55\nCogTel*      6 144  56.42 31.64  57.50   56.23 37.81   1 114.00 113.00  0.03\nT0           7 140   0.07  0.03   0.06    0.07  0.04   0   0.17   0.17  0.29\nT1           8 122   0.06  0.03   0.06    0.06  0.03   0   0.16   0.16  0.06\nT2           9  97   0.08  0.04   0.08    0.08  0.03   0   0.19   0.19  0.27\n          kurtosis   se\nID           -1.36 5.20\nStandort     -1.75 0.04\nGruppe*      -1.99 0.04\nSex*         -1.92 0.04\nAge_start    -0.47 0.29\nCogTel*      -1.11 2.64\nT0           -0.30 0.00\nT1            0.18 0.00\nT2            0.18 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ndescribe(bdnf_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n   mean    sd median trimmed   mad min    max  range  skew\nID           1 144 108.17 62.41 121.50  109.68 80.80   1 202.00 201.00 -0.23\nStandort     2 144   0.62  0.49   1.00    0.66  0.00   0   1.00   1.00 -0.51\nGruppe*      3 144   1.47  0.50   1.00    1.46  0.00   1   2.00   1.00  0.14\nSex*         4 144   1.42  0.50   1.00    1.41  0.00   1   2.00   1.00  0.31\nAge_start    5 144  69.58  3.51  69.00   69.37  2.97  62  78.00  16.00  0.55\nCogTel*      6 144  56.42 31.64  57.50   56.23 37.81   1 114.00 113.00  0.03\nT0           7 140   0.04  0.04   0.03    0.03  0.04   0   0.18   0.18  1.14\nT1           8 122   0.03  0.03   0.03    0.03  0.04   0   0.12   0.12  0.86\nT2           9  97   0.05  0.04   0.04    0.04  0.04   0   0.21   0.21  1.52\n          kurtosis   se\nID           -1.36 5.20\nStandort     -1.75 0.04\nGruppe*      -1.99 0.04\nSex*         -1.92 0.04\nAge_start    -0.47 0.29\nCogTel*      -1.11 2.64\nT0            0.78 0.00\nT1           -0.04 0.00\nT2            2.71 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## Tau\ndescribe(tau_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n  mean    sd median trimmed   mad   min    max  range  skew\nID*          1 145 72.29 41.65  72.00   72.24 53.37  1.00 144.00 143.00  0.01\nStandort     2 145  1.63  0.49   2.00    1.66  0.00  1.00   2.00   1.00 -0.52\nGruppe*      3 145  1.47  0.50   1.00    1.46  0.00  1.00   2.00   1.00  0.12\nSex*         4 145  1.43  0.50   1.00    1.41  0.00  1.00   2.00   1.00  0.29\nAge_start    5 145 69.57  3.50  69.00   69.36  2.97 62.00  78.00  16.00  0.56\nCogTel*      6 145 56.43 31.53  58.00   56.26 37.06  1.00 114.00 113.00  0.03\nT0           7 142  0.07  0.02   0.07    0.07  0.02  0.03   0.17   0.14  0.79\nT1           8 123  0.08  0.02   0.07    0.07  0.02  0.01   0.15   0.13  0.60\nT2           9  97  0.08  0.02   0.07    0.08  0.02  0.03   0.13   0.10  0.37\n          kurtosis   se\nID*          -1.22 3.46\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel*      -1.10 2.62\nT0            2.54 0.00\nT1            1.01 0.00\nT2            0.10 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ndescribe(tau_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n  mean    sd median trimmed   mad min    max  range  skew\nID*          1 145 72.29 41.65  72.00   72.24 53.37   1 144.00 143.00  0.01\nStandort     2 145  1.63  0.49   2.00    1.66  0.00   1   2.00   1.00 -0.52\nGruppe*      3 145  1.47  0.50   1.00    1.46  0.00   1   2.00   1.00  0.12\nSex*         4 145  1.43  0.50   1.00    1.41  0.00   1   2.00   1.00  0.29\nAge_start    5 145 69.57  3.50  69.00   69.36  2.97  62  78.00  16.00  0.56\nCogTel*      6 145 56.43 31.53  58.00   56.26 37.06   1 114.00 113.00  0.03\nT0           7 142  0.02  0.01   0.02    0.02  0.01   0   0.05   0.05  0.19\nT1           8 123  0.02  0.02   0.02    0.02  0.01   0   0.12   0.12  1.93\nT2           9  97  0.02  0.01   0.01    0.02  0.01   0   0.06   0.06  0.69\n          kurtosis   se\nID*          -1.22 3.46\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel*      -1.10 2.62\nT0           -0.95 0.00\nT1            8.21 0.00\nT2            0.13 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## PSD95\ndescribe(psd95_mean_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n  mean    sd median trimmed   mad   min    max  range  skew\nID*          1 145 72.29 41.65  72.00   72.24 53.37  1.00 144.00 143.00  0.01\nStandort     2 145  1.63  0.49   2.00    1.66  0.00  1.00   2.00   1.00 -0.52\nGruppe*      3 145  1.47  0.50   1.00    1.46  0.00  1.00   2.00   1.00  0.12\nSex*         4 145  1.43  0.50   1.00    1.41  0.00  1.00   2.00   1.00  0.29\nAge_start    5 145 69.57  3.50  69.00   69.36  2.97 62.00  78.00  16.00  0.56\nCogTel*      6 145 56.43 31.53  58.00   56.26 37.06  1.00 114.00 113.00  0.03\nT0           7 139  0.03  0.02   0.03    0.03  0.01  0.00   0.13   0.13  2.27\nT1           8 122  0.03  0.01   0.03    0.03  0.01  0.01   0.07   0.06  0.68\nT2           9  96  0.03  0.01   0.03    0.03  0.01  0.00   0.06   0.05 -0.09\n          kurtosis   se\nID*          -1.22 3.46\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel*      -1.10 2.62\nT0           11.51 0.00\nT1            0.03 0.00\nT2           -0.41 0.00\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ndescribe(psd95_median_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          vars   n  mean    sd median trimmed   mad min    max  range  skew\nID*          1 145 72.29 41.65     72   72.24 53.37   1 144.00 143.00  0.01\nStandort     2 145  1.63  0.49      2    1.66  0.00   1   2.00   1.00 -0.52\nGruppe*      3 145  1.47  0.50      1    1.46  0.00   1   2.00   1.00  0.12\nSex*         4 145  1.43  0.50      1    1.41  0.00   1   2.00   1.00  0.29\nAge_start    5 145 69.57  3.50     69   69.36  2.97  62  78.00  16.00  0.56\nCogTel*      6 145 56.43 31.53     58   56.26 37.06   1 114.00 113.00  0.03\nT0           7 139  0.00  0.01      0    0.00  0.00   0   0.05   0.05  3.65\nT1           8 122  0.00  0.01      0    0.00  0.00   0   0.06   0.06  3.28\nT2           9  96  0.00  0.00      0    0.00  0.00   0   0.02   0.02  5.48\n          kurtosis   se\nID*          -1.22 3.46\nStandort     -1.74 0.04\nGruppe*      -2.00 0.04\nSex*         -1.93 0.04\nAge_start    -0.46 0.29\nCogTel*      -1.10 2.62\nT0           13.50 0.00\nT1           12.12 0.00\nT2           31.81 0.00\n```\n\n\n:::\n:::\n\n\n## Plotting EDA\n\n### Boxplots\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\neda_bdnf <- cpg\nbdnfcols_to_modify <- 5:14\n\neda_tau <- cpg\ntaucols_to_modify <- 19:67\n\neda_psd95 <- cpg\npsd95cols_to_modify <- 72:116\n\n# Remove the suffix 'BDNF' from the column names in columns 5 to 14\ncolnames(eda_bdnf)[bdnfcols_to_modify] <- sub(\"BDNF$\", \"\", colnames(eda_bdnf)[bdnfcols_to_modify])\n\n# remove \"Tau\ncolnames(eda_tau)[taucols_to_modify] <- sub(\"Tau$\", \"\", colnames(eda_tau)[taucols_to_modify])\n\n#remove PSD\ncolnames(eda_psd95)[psd95cols_to_modify] <- sub(\"PSD95$\", \"\", colnames(eda_psd95)[psd95cols_to_modify])\n\n# View the updated column names\nprint(colnames(eda_bdnf[c(5:14)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m148 \" \"m111 \" \"m087 \" \"m066 \" \"m058 \" \"m039 \" \"m035 \" \"m024 \" \"p018 \"\n[10] \"p020 \"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(colnames(eda_tau[c(19:67)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m337 \"   \"m331 \"   \"m323 \"   \"m315 \"   \"m310 \"   \"m306 \"   \"m300 \"  \n [8] \"m293 \"   \"m287 \"   \"m277 \"   \"m249 \"   \"m219 \"   \"m210 \"   \"m207 \"  \n[15] \"m187 \"   \"m181 \"   \"m172 \"   \"m152 \"   \"m147 \"   \"m111.1 \" \"m109 \"  \n[22] \"m105 \"   \"m100 \"   \"m95 \"    \"m93 \"    \"m91 \"    \"m87 \"    \"m85 \"   \n[29] \"m80 \"    \"m73 \"    \"m70 \"    \"m68 \"    \"m58 \"    \"m53 \"    \"m41 \"   \n[36] \"m39 \"    \"m28 \"    \"m25 \"    \"m16 \"    \"m11 \"    \"m4 \"     \"m1 \"    \n[43] \"p3 \"     \"p7 \"     \"p11 \"    \"p19 \"    \"p23 \"    \"p25 \"    \"p27 \"   \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprint(colnames(eda_psd95[c(72:116)]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"m465 \"   \"m418 \"   \"m405 \"   \"m400 \"   \"m395 \"   \"m392 \"   \"m349 \"  \n [8] \"m340 \"   \"m329 \"   \"m326 \"   \"m294 \"   \"m291 \"   \"m284 \"   \"m282 \"  \n[15] \"m254 \"   \"m249.1 \" \"m236 \"   \"m226 \"   \"m199 \"   \"m193 \"   \"m176 \"  \n[22] \"m165 \"   \"m163 \"   \"m155 \"   \"m150 \"   \"m124 \"   \"m113 \"   \"m92 \"   \n[29] \"m83 \"    \"m77 \"    \"m69 \"    \"m49 \"    \"m35 \"    \"m31 \"    \"m28.1 \" \n[36] \"m24 \"    \"m18 \"    \"m11.1 \"  \"p23.1 \"  \"p31 \"    \"p36 \"    \"p60 \"   \n[43] \"p91 \"    \"p95 \"    \"p122 \"  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#dev.new(width=14, height=7)\npar(mfrow = c(3, 3))\nlayout(matrix(c(0, 1, 0, 2, 2, 2, 3, 3, 3), nrow = 3, byrow = TRUE))\n#with()!\nboxplot(eda_bdnf[, c(5:14)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the BDNF-CpGs\")\n\nboxplot(eda_tau[, c(19:67)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the Tau-CpGs\")\n\nboxplot(eda_psd95[, c(72:116)], \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the PSD95-CpGs\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\nlibrary(ggplot2)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'ggplot2'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:psych':\n\n    %+%, alpha\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n#Tau\n\ntau_cpg_data <- eda_tau[, 19:39]\n\ntau_cpg_data_long <- stack(tau_cpg_data)\n\ntau_cpg_data_long$Gruppe_Tau <- eda_tau$`Gruppe Tau`\ntau_cpg_data_long$Zeit_Tau <- eda_tau$`Zeit Tau`\n\nboxplot(ind ~ Gruppe_Tau, data = tau_cpg_data_long, \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the Tau-CpGs\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nggplot(tau_cpg_data_long, aes(x = ind, y = values, color = `Gruppe_Tau`)) +\n  geom_boxplot() + \n  labs(x = \"Group Tau\", y = \"Methylation Level\", title = \"CpGs Methylation Levels by Group Tau\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 177 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-33-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nggplot(tau_cpg_data_long, aes(x = ind, y = values, color = `Zeit_Tau`)) +\n  geom_boxplot() + \n  labs(x = \"Zeit Tau\", y = \"Methylation Level\", title = \"CpGs Methylation Levels by Zeit Tau\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 177 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-33-3.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nggplot(tau_cpg_data_long, aes(x = ind, y = values, color = `Gruppe_Tau`)) +\n  geom_point() +\n  geom_line()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 177 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 126 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-33-4.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n  labs(x = \"Group Tau\", y = \"Methylation Level\", title = \"CpGs Methylation Levels by Group Tau\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#PSD95\n\npsd95_cpg_data <- eda_psd95[, 98:116]\n\npsd95_cpg_data_long <- stack(psd95_cpg_data)\n\npsd95_cpg_data_long$Gruppe_psd95 <- eda_psd95$`Gruppe PSD95`\npsd95_cpg_data_long$Zeit_psd95 <- eda_psd95$`Zeitpunkt PSD95`\n\nboxplot(ind ~ Gruppe_psd95, data = psd95_cpg_data_long, \n        xlab = \"CpGs\", \n        ylab = \"Methylation Level\", \n        main = \"Boxplot of the Tau-CpGs\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nggplot(psd95_cpg_data_long, aes(x = ind, y = values, color = `Gruppe_psd95`)) +\n  geom_boxplot() + \n  labs(x = \"Group Tau\", y = \"Methylation Level\", title = \"CpGs Methylation Levels by Group Tau\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 456 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-34-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nggplot(psd95_cpg_data_long, aes(x = ind, y = values, color = `Zeit_psd95`)) +\n  geom_boxplot() + \n  labs(x = \"Zeit Tau\", y = \"Methylation Level\", title = \"CpGs Methylation Levels by Zeit Tau\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 456 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-34-3.png){width=672}\n:::\n:::\n\n\n\n\n### Lineplots\nsee new EDA.qmd\n\n\n# PCA\n\n## BDNF\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncpg_bdnf <- cpg[5:14]\npca_bdnf <- prcomp(na.omit(cpg_bdnf), scale = TRUE)\n\n## plot pc1 and pc2\nplot(pca_bdnf$x[,1], pca_bdnf$x[,2])\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n## make a scree plot\npca_bdnf_var <- pca_bdnf$sdev^2\npca_bdnf_var_per <- round(pca_bdnf_var/sum(pca_bdnf_var)*100, 1)\n\nbarplot(pca_bdnf_var_per, main=\"BDNF Scree Plot\", xlab=\"Principal Component\", ylab=\"Percent Variation\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-35-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n## now make a fancy looking plot that shows the PCs and the variation:\nlibrary(ggplot2)\n\n\npca_bdnf_data <- as.data.frame(pca_bdnf$x)\npca_bdnf_data$ID <- rownames(pca_bdnf)\n\npca_bdnf_data[1:3,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         PC1         PC2        PC3         PC4         PC5         PC6\n1 -0.4983982 -0.09625517  0.5289260 -0.09502929  0.71613262  0.05692434\n2  1.1720441  0.18159948  0.4378651 -0.38193259  0.06752459 -0.05879165\n3 -2.0353002  2.30841912 -1.4098291 -0.36238449 -0.04653962 -1.37059444\n          PC7         PC8         PC9       PC10\n1 -0.15799882 -0.96874552 -0.73151124  0.6833330\n2  0.30117815 -0.09332618 -0.04401237  0.3197704\n3 -0.05712553 -0.44440554 -1.23228847 -1.4763906\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(pca_bdnf_data, aes(PC1, PC2)) +\n  geom_point() +\n  xlab(paste(\"PC1 - \", pca_bdnf_var_per[1], \"%\", sep=\"\")) +\n  ylab(paste(\"PC2 - \", pca_bdnf_var_per[2], \"%\", sep=\"\")) +\n  theme_bw() +\n  ggtitle(\"BDNF PCA Graph\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-35-3.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nbdnf_loading_scores <- pca_bdnf$rotation[,1]\nbdnf_methylation_scores <- abs(bdnf_loading_scores) # what to do of bdnf_methylation_scores?\n  \nlibrary(ggfortify)\npca_bdnf_res <- prcomp(na.omit(bdnf[c(11:20)]), scale = TRUE)\n\nautoplot(pca_bdnf_res, data = na.omit(bdnf[c(1:20)]), colour = 'Zeitpunkt',\n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-35-4.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nautoplot(pca_bdnf_res, data = na.omit(bdnf[c(1:20)]), colour = 'Gruppe', \n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-35-5.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nautoplot(pca_bdnf_res, data = na.omit(bdnf[c(1:22)]), colour = 'Sex', \n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-35-6.png){width=672}\n:::\n:::\n\n\n## Tau\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncpg_tau <- tau[c(9:57)]\npca_tau <- prcomp(na.omit(cpg_tau), scale = TRUE)\n\n## plot pc1 and pc2\nplot(pca_tau$x[,1], pca_tau$x[,2])\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n## make a scree plot\npca_tau_var <- pca_tau$sdev^2\npca_tau_var_per <- round(pca_tau_var/sum(pca_tau_var)*100, 1)\n\nbarplot(pca_tau_var_per, main=\"Tau Scree Plot\", xlab=\"Principal Component\", ylab=\"Percent Variation\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-36-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n## now make a fancy looking plot that shows the PCs and the variation:\nlibrary(ggplot2)\n\n\npca_tau_data <- as.data.frame(pca_tau$x)\npca_tau_data$ID <- rownames(pca_tau)\n\npca_tau_data[1:3,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         PC1        PC2        PC3        PC4         PC5       PC6        PC7\n1 -1.3819533 -0.7723589 -0.1497939 -0.8255788 0.580228997 1.1097423  0.7453586\n2  0.9413986  1.8957482 -1.8432497 -0.5113439 0.006439829 0.3381304 -0.4922156\n3 -2.8051860  0.1268586  1.3089492 -1.4754544 1.383269618 0.3254420 -1.4521685\n          PC8        PC9      PC10       PC11        PC12        PC13\n1 -0.09721616 -0.2145984 1.1261094 -0.1562817  0.07521798 -0.08549565\n2  1.48901252 -1.0289252 0.1594086 -0.4758586  1.11682734 -3.90001841\n3  0.45448119  0.5023209 0.2460753 -1.8408635 -0.90120728  0.50740168\n        PC14       PC15       PC16       PC17       PC18       PC19\n1  0.5876715  0.2571748 -0.4786351  0.3030931  0.6359893 -0.8759168\n2 -1.7626354 -0.6949328 -1.4574158  0.1713398  0.2598557  0.4924712\n3  1.0941291 -0.1581122 -0.4350578 -1.5634038 -0.4342087 -0.2517165\n          PC20       PC21       PC22       PC23       PC24       PC25\n1 -0.028023313 -0.5952623 -0.1414024 -0.7283844  0.8403992 -0.1860633\n2 -0.032765013 -1.5120971 -1.4633075  1.1067587  0.3458078 -0.7956224\n3  0.005762332 -1.5205530 -0.1750097  1.8361136 -0.1698045  0.5892632\n        PC26      PC27       PC28       PC29       PC30       PC31       PC32\n1  0.1242099 0.1995952  0.9042246 -0.2429982  0.5817562 -0.2902614  0.2996957\n2  1.4236614 0.8399747 -0.5923222  2.1732052  0.5287806 -0.6041974  0.8320099\n3 -0.2565404 2.6394070  1.5343056  0.2338289 -0.9271500  1.0454751 -1.1933092\n        PC33       PC34       PC35       PC36       PC37       PC38        PC39\n1  0.4895250 -0.2285274 -0.9431248 -0.3145852 -0.2985718  0.0145554  0.11409038\n2 -1.1517656  0.4853406 -1.3423034 -0.5554157 -0.1993071 -0.2289016 -0.07316783\n3 -0.7428804  0.7343906 -0.4101199 -1.0491344  0.3442827 -0.4879081  0.75944947\n        PC40       PC41       PC42       PC43       PC44       PC45\n1  0.4173199 -0.0738361 -0.7205934  0.5708402  0.4655692 -0.6334262\n2 -1.3263351 -0.3411441  0.8513456 -0.1796426  0.9981185  0.5612230\n3 -0.4137266  0.4624610  0.8652623  0.2884630 -0.2203790 -0.8215023\n          PC46       PC47        PC48       PC49\n1 -0.394740983 -0.8828214  0.09229853 -0.4927227\n2  0.045183409  0.1006513  1.05004595  0.2399484\n3 -0.007963722  0.4694915 -0.58000267  0.6907393\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(pca_tau_data, aes(PC1, PC2)) +\n  geom_point() +\n  xlab(paste(\"PC1 - \", pca_tau_var_per[1], \"%\", sep=\"\")) +\n  ylab(paste(\"PC2 - \", pca_tau_var_per[2], \"%\", sep=\"\")) +\n  theme_bw() +\n  ggtitle(\"Tau PCA Graph\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-36-3.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\ntau_loading_scores <- pca_tau$rotation[,1]\ntau_methylation_scores <- abs(tau_loading_scores) # what to do of tau_methylation_scores?\n  \nlibrary(ggfortify)\npca_tau_res <- prcomp(na.omit(tau[c(9:57)]), scale = TRUE)\n\nautoplot(pca_tau_res, data = na.omit(tau[c(1:57)]), colour = 'Zeit',\n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-36-4.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nautoplot(pca_tau_res, data = na.omit(tau[c(1:57)]), colour = 'Gruppe', \n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-36-5.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nautoplot(pca_tau_res, data = na.omit(tau[c(1:57,357)]), colour = 'Sex', \n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-36-6.png){width=672}\n:::\n:::\n\n\n## PSD95\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncpg_psd95 <- psd95[10:54]\npca_psd95 <- prcomp(na.omit(cpg_psd95), scale = TRUE)\n\n## plot pc1 and pc2\nplot(pca_psd95$x[,1], pca_psd95$x[,2])\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n## make a scree plot\npca_psd95_var <- pca_psd95$sdev^2\npca_psd95_var_per <- round(pca_psd95_var/sum(pca_psd95_var)*100, 1)\n\nbarplot(pca_psd95_var_per, main=\"PSD95 Scree Plot\", xlab=\"Principal Component\", ylab=\"Percent Variation\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-37-2.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\n## now make a fancy looking plot that shows the PCs and the variation:\nlibrary(ggplot2)\n\n\npca_psd95_data <- as.data.frame(pca_psd95$x)\npca_psd95_data$ID <- rownames(pca_psd95)\n\npca_psd95_data[1:3,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          PC1        PC2        PC3         PC4        PC5         PC6\n1 -2.85879342 -0.2418145 1.20087794 -1.23554615 -1.0082756 -1.66023808\n2  0.04144341  1.7594644 0.35767439  0.48834915 -0.3663842 -0.03269961\n3  0.92326567  0.9665959 0.09710472  0.06864842  0.5617707 -0.76101641\n          PC7        PC8         PC9       PC10       PC11        PC12\n1 -0.28088324  2.7168877 -1.22359032  1.6047574 -0.8404363 -0.41833654\n2 -0.05698023 -0.3950535 -0.33043096  0.1048172 -0.3838444  0.29584449\n3  0.61308021  1.5788723 -0.09993921 -0.8642271 -1.1939783  0.06738369\n         PC13       PC14       PC15       PC16        PC17       PC18\n1 -1.89270715 -0.6642204  3.2744670 -1.8462332  1.69705445  1.2607945\n2 -0.06769426 -0.4101253 -0.4371388  0.1849072 -0.04403083 -0.1511606\n3  0.91016466  1.3808576 -0.3571009  0.3639245 -0.89357025 -0.7817385\n        PC19       PC20       PC21        PC22        PC23       PC24\n1 -0.6613414 -1.8809205 -1.0327169 -1.93435454 -0.04848429  1.3770464\n2 -0.3290592  0.2795013  0.0598549 -0.07629996  0.02122475  0.1202249\n3  1.5815698 -0.9694465  0.0579347 -0.10892581 -0.02161555 -0.4911406\n        PC25      PC26        PC27       PC28       PC29       PC30       PC31\n1 -0.5305166 0.5719533 -0.05301698  0.1186769 -0.3076120 -0.3285893 -0.7448268\n2  0.1086488 0.2768093  0.40568208 -0.2776204 -0.9715391  0.2281850 -0.3490462\n3  1.6244475 0.5386738 -0.79059755 -0.5317878 -0.6690955  0.4897704  0.3564923\n        PC32       PC33       PC34        PC35       PC36        PC37\n1 -0.6494182  0.8940321 -0.6075720  0.38289079 -0.2018711  0.06035272\n2 -0.3914331 -0.6230479  0.2858146 -0.61612144 -0.1577528 -0.72065256\n3 -0.6745935 -1.3116696  0.4726334  0.06182365  0.4844632 -0.61752191\n        PC38        PC39        PC40        PC41       PC42       PC43\n1  0.7158445  0.25142474  0.02882617  0.61527861 0.03760039 -0.1248835\n2 -0.8173084  0.06782867  0.19479037 -0.58568826 0.18121824 -0.3884399\n3 -0.4437899 -0.06860361 -0.30955436 -0.02069936 0.48102956 -0.6925315\n        PC44        PC45\n1 -0.6010115 -0.09819888\n2 -0.4604330 -0.06434912\n3 -0.4227139  0.27316119\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nggplot(pca_psd95_data, aes(PC1, PC2)) +\n  geom_point() +\n  xlab(paste(\"PC1 - \", pca_psd95_var_per[1], \"%\", sep=\"\")) +\n  ylab(paste(\"PC2 - \", pca_psd95_var_per[2], \"%\", sep=\"\")) +\n  theme_bw() +\n  ggtitle(\"PSD95 PCA Graph\")\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-37-3.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\npsd95_loading_scores <- pca_psd95$rotation[,1]\npsd95_methylation_scores <- abs(psd95_loading_scores) # what to do of tau_methylation_scores?\n  \nlibrary(ggfortify)\npca_psd95_res <- prcomp(na.omit(psd95[c(10:54)]), scale = TRUE)\n\nautoplot(pca_psd95_res, data = na.omit(psd95[c(1:54)]), colour = 'Zeitpunkt',\n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-37-4.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nautoplot(pca_psd95_res, data = na.omit(psd95[c(1:54)]), colour = 'Gruppe', \n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-37-5.png){width=672}\n:::\n\n```{.r .cell-code .hidden}\nautoplot(pca_psd95_res, data = na.omit(psd95[c(1:54,353)]), colour = 'Sex', \n         loadings = TRUE, loadings.colour = 'blue',\n         loadings.label = TRUE, loadings.label.size = 3)\n```\n\n::: {.cell-output-display}\n![](131124_TBM-mit-Martin_old_wholescript_files/figure-html/unnamed-chunk-37-6.png){width=672}\n:::\n:::\n",
    "supporting": [
      "131124_TBM-mit-Martin_old_wholescript_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}